### ISSUE TITLE
Profiling trips assertion failure when attempting to profile nested kNN with inner_hits

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#103985]
### Elasticsearch Version

8.12

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

When doing a search against a nested kNN field & requesting profiling & attempting to gather inner_hits, an assertion is tripped.

### Steps to Reproduce

The following yaml test added to `100_knn_nested_search` shows the failure:
```
---
"nested kNN search inner_hits & profiling":
  - do:
      search:
        index: test
        body:
          profile: true
          fields: [ "name" ]
          knn:
            field: nested.vector
            query_vector: [-0.5, 90.0, -10, 14.8, -156.0]
            k: 3
            num_candidates: 3
            filter: {term: {name: "rabbit.jpg"}}
            inner_hits: {size: 1, fields: ["nested.paragraph_id"], _source: false}

  - match: {hits.total.value: 1}
  - match: {hits.hits.0._id: "3"}
  - match: {hits.hits.0.fields.name.0: "rabbit.jpg"}
  - match: {hits.hits.0.inner_hits.nested.hits.hits.0.fields.nested.0.paragraph_id.0: "0"}

```

### Logs (if relevant)

```
[2024-01-05T09:45:10,184][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][search][T#2]], exiting java.lang.AssertionError
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.fetch.FetchSearchResult.shardResult(FetchSearchResult.java:64)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:84)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.fetch.subphase.InnerHitsPhase.hitExecute(InnerHitsPhase.java:95)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.fetch.subphase.InnerHitsPhase$1.process(InnerHitsPhase.java:62)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.fetch.FetchProfiler$2.process(FetchProfiler.java:136)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.fetch.FetchPhase$1.nextDoc(FetchPhase.java:163)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:70)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.fetch.FetchPhase.buildSearchHits(FetchPhase.java:169)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:78)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.SearchService.lambda$executeFetchPhase$9(SearchService.java:868)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:73)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:70)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:95)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
