### ISSUE TITLE
[ Ingest | Processor ] Need for a new Validate processor

### ISSUE THREAD

**Issue by vinit-chauhan** [elastic/elasticsearch#110559]
### Description

In Elastic Integrations, there has been an extensive need to validate certain values to ensure correct data is being ingested. Moreover, in the current stage, if there are any changes in type only then we can catch the changes in ingest time. 
The main goal of this processor is to "fail fast" on unanticipated changes from data source.

Use-cases:
- If we have a field sending the MAC Address of a host, there's no easy way ( other than writing a PAIN-less script)  to verify that the value being ingested is in the correct format. 
- To validate any product-specific patterns in value of some fields.

The proposed solution would be to have a `validate` processor which would take a regex pattern and check the values against it and on failure either drop the value or raise an error to catch invalid data at ingest time. 
Once implemented, all we need is the following section in the ingest pipeline. 
 ```
 validate:
     field: some_field
     pattern: "^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"
    on_failure:
        append:
            field: error.message
            value: "invalid value for some_field"
 ```
