### ISSUE TITLE
Permission Error When Installing Plugins on an Elasticsearch Cluster Deployed with ECK on Kubernetes

### ISSUE THREAD

**Issue by yancy-hong** [elastic/elasticsearch#112892]
### Elasticsearch Version

8.12.2

### Installed Plugins

analysis-ik

### Java Version

_bundled_

### OS Version

Ubuntu 22.04

### Problem Description

Installation plugin error:
```sh
bin/elasticsearch-plugin install https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2
...
...
Exception in thread "main" java.nio.file.FileSystemException: /usr/share/elasticsearch/config/analysis-ik: Operation not permitted
```

### Steps to Reproduce

Kubernetes partial configuration file:
```yaml
initContainers:
  - name: install-plugins
    securityContext:
      privileged: true
      runAsUser: 0
    command:
      - sh
      - -c
      - |
        bin/elasticsearch-plugin install https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2
```

The pod init failed, part of the pod describe output:
```sh
Back-off restarting failed container install-plugins in pod elastic-search-es-default-1_elastic
```

Modified the configuration to not install the plugin automatically, and redeployed the pod:
```yaml
initContainers:
  - name: install-plugins
    securityContext:
      privileged: true
      runAsUser: 0
    command:
      - sh
      - -c
      - |
        echo "hello"
```

Used `kubectl exec` to enter the pod and manually install the plugin:
```sh
bin/elasticsearch-plugin install https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2
```

Encountered the following error:
```sh
Exception in thread "main" java.nio.file.FileSystemException: 
     /usr/share/elasticsearch/config/analysis-ik: Operation not permitted
```

Even after adding permissions for the `config/analysis-ik` directory in the Kubernetes configuration, the error still persists:
```yaml
initContainers:
  - name: install-plugins
    securityContext:
      privileged: true
      runAsUser: 0
    command:
      - sh
      - -c
      - |
        mkdir -p config/analysis-ik
        chmod -R 777 config/analysis-ik
        bin/elasticsearch-plugin install https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2
```

Full Kubernetes configuration:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-search
  namespace: elastic
spec:
  version: 8.12.2
  nodeSets:
    - name: default
      count: 2
      config:
        node.store.allow_mmap: false
        node.roles: ["master", "data", "ingest"]
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: sc-es
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 8Gi
                  cpu: 4
                limits:
                  memory: 8Gi
                  cpu: 4
          initContainers:
            - name: install-plugins
              securityContext:
                privileged: true
                runAsUser: 0
              command:
                - sh
                - -c
                - |
                  bin/elasticsearch-plugin install https://get.infini.cloud/elasticsearch/analysis-ik/8.12.2

  transport:
    service:
      metadata:
        name: elastic
      spec:
        type: NodePort
```

`sc-es` StorageClass contents:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: nfs.csi.k8s.io
metadata:
  name: sc-es
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  server: 10.10.10.110
  share: /nfs/elastic/search
```

NFS directory permissions:
```sh
ls -ld /nfs/elastic/search/
drwxrwxrwx 6 root root 4096 Sep 14 12:03 /nfs/elastic/search/
```

Kubernetes `v1.30.5`
