### ISSUE TITLE
Reverse image search by elasticsearch, long time no result.

### ISSUE THREAD

**Issue by hetao29** [elastic/elasticsearch#114483]
### Elasticsearch Version

8.15.2

### Java Version

_bundled_

### OS Version

docker

### Problem Description

I save the vector data in es, like below, and data is 200m records.
```json
PUT /item/_mapping
{
    "properties": {
        "thumbs.thumb_vector": {
            "type": "dense_vector",
            "dims": 2048,
            "similarity": "l2_norm"
        }
    }
}
```
search 
```json
{
    "_knn": {
        "field": "thumbs.thumb_vector",
        "query_vector": [],
        "k": 10,
        "num_candidates": 100
    }
}
```

### Steps to Reproduce

none.

**Comment by benwtrent** [comment]
@hetao29 we are missing a fair bit of information.

Is the "no result" just because of a timeout?

200M at 2048 dimensions, with int8 quantization will basically require `382GB` of off-heap ram. May I inquire how much off-heap ram you have in your test?

**Comment by hetao29** [comment]
> [@hetao29](https://github.com/hetao29) we are missing a fair bit of information.
> 
> Is the "no result" just because of a timeout?
> 
> 200M at 2048 dimensions, with int8 quantization will basically require `382GB` of off-heap ram. May I inquire how much off-heap ram you have in your test?

The dimensions is float type, use the https://github.com/hetao29/image_to_vector to generate, I have 3 docker nodes of below config:

```yml
version: "3.9"
services:
  core:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      ...
```
