### ISSUE TITLE
Better validation of yaml 

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#11485]
Here is an example of an Elasticsearch yml.

```
action: 
  disable_delete_all_indices: "true"
bootstrap: 
  mlockall: "true"
cluster: 
  name: cluster_name
discovery: 
  zen: 
    ping: 
      - 
        multicast: 
          enabled: "false"
      - 
        unicast: 
          - host1
          - host2
          - host3
          - host4
          - host5
          - host6
          - host6
          - host8
gateway: 
  - 
    recover_after_time: 10m
  - 
    recover_after_nodes: 6
  - 
    expected_nodes: 8
http: 
  enabled: "true"
network: 
  host: "some_ip"
node: 
  name: some_name
processors: "24"
script: 
  disable_dynamic: "true"
threadpool: 
  bulk: 
    queue_size: "100"
```

It certainly doesn't look like a usual Elasticsearch yml file we can interpret, but it does pass yaml validation using http://www.yamllint.com/, http://yaml-online-parser.appspot.com/, etc..  And the user can probably tell from the ES log that it is not taking the entries because the cluster name will start up using the default elasticsearch.  But it will be nice to:

* Provide some indication in the log file that it is actually a yaml file that ES cannot parse or interpret
* And maybe additional details on why we cannot parse it.
