### ISSUE TITLE
Elasticsearch 8.17.0 failing to start in minikube with older manifests (used to work with 7.12.1)

### ISSUE THREAD

**Issue by dangerouspython** [elastic/elasticsearch#120176]
### Elasticsearch Version

8.17.0

### Installed Plugins

kibana, istio

### Java Version

_bundled_

### OS Version

Darwin GGN-MAC-10089 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 18:41:43 PST 2024; root:xnu-11215.61.5~2/RELEASE_X86_64 x86_64

### Problem Description

I am using my existing manifests file (mentioned below) to deploy `elasticsearch` (along with `kibana`) new version `8.17.0` into my local minikube instance (which has `istio v1.24.2` deployed in it too). These manifests used to work perfectly with versions `7.12.1` of both `elasticsearch` and `kibana`. 

When the new docker image is used,`kibana` is up and running just fine (with response `200` for the command `curl https://kibana.minikube.me -kLs -o /dev/null -w "%{http_code}\n"`).

But when I run the commad `curl https://elasticsearch.minikube.me -sk`, `elasticsearch` just responds with the following error:
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: delayed connect error: Connection refused
```
_(Earlier, with `v 7.12.1`, a proper JSON response containing the tagline 'You know, for sure' was being sent)_

Here are the manifests that I am using (nothing else has changed apart from the image for `elasticsearch`):
```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: elasticsearch

spec:
    selector:
        matchLabels:
            component: elasticsearch
    template:
        metadata:
            labels:
                component: elasticsearch
        spec:
            containers:
                - name: elasticsearch
                  image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0 # earlier this was 7.12.1
                  env:
                      - name: discovery.type
                        value: single-node
                  ports:
                      - containerPort: 9200
                        name: http
                        protocol: TCP
                  resources:
                      limits:
                          cpu: 500m
                          memory: 1Gi
                      requests:
                          cpu: 500m
                          memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
    name: elasticsearch
    labels:
        service: elasticsearch

spec:
    type: ClusterIP
    selector:
        component: elasticsearch
    ports:
        - port: 9200
          targetPort: 9200

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: elasticsearch-gateway
    namespace: logging

spec:
    selector:
        istio: ingressgateway
    servers:
        - hosts:
              - "elasticsearch.minikube.me"
          port:
              number: 443
              name: https-elasticsearch
              protocol: HTTPS
          tls:
              mode: SIMPLE
              credentialName: my-certificate

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: elasticsearch-vs
    namespace: logging

spec:
    hosts:
        - "elasticsearch.minikube.me"
    gateways:
        - elasticsearch-gateway
    http:
        - route:
              - destination:
                    host: elasticsearch
                    port:
                        number: 9200

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: elasticsearch
    namespace: logging

spec:
    host: elasticsearch
    trafficPolicy:
        tls:
            mode: DISABLE
```

### Steps to Reproduce

Mentioned above in the problem description
