### ISSUE TITLE
Unable to set logging level for docker container

### ISSUE THREAD

**Issue by instantdreams** [elastic/elasticsearch#121595]
### Elasticsearch Version

Version: 8.16.0, Build: docker/12ff76a92922609df4aba61a368e7adf65589749/2024-11-08T10:05:56.292914697Z, JVM: 23

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

Debian 6.1.112-1, Docker version 27.3.1, Docker Compose version v2.29.7

### Problem Description

I have an elasticsearch container using the following compose.yaml file:

```YAML
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    container_name: elasticsearch
    expose:
      - 9200
    env_file:
      - .env
    volumes:
      - ${DIRECTORY_DATA}:/usr/share/elasticsearch/data
      - ${DIRECTORY_SNAPSHOT}:/usr/share/elasticsearch/data/snapshot
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```

With the following .env file:

```
# Directory locations
DIRECTORY_DATA=/srv/elasicsearch/data
DIRECTORY_SNAPSHOT=/srv/elasticsearch/snapshot
# Container specifics
## elastic-search
ES_JAVA_OPTS=-Xms512m -Xmx512m
xpack.security.enabled=true
discovery.type=single-node
path.repo=/usr/share/elasticsearch/data/snapshot
ES_SETTING_LOGGER_ORG_ELASTICSEARCH_DISCOVERY=WARN
logger.org.elasticsearch.discovery=WARN
ES_SETTING_LOGGER_DISCOVERY_LEVEL=WARN
logger.discovery.level=WARN
ES_SETTING_LOGGER_ACTION_LEVEL=WARN
logger.action.level=warn
ES_SETTING_LOGGER_DEPRECIATION_LEVEL=WARN
logger.depreciation.level=warn
#ES_SETTING_ROOTLOGGER_LEVEL=WARN
#logger.level=WARN
```

I am trying to set my log level to warnings only, and have reviewed [application logging](https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html), [configuring ES with docker](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-configuration-methods), but I can't seem to find any clear documentation on just setting the log level.

### Steps to Reproduce

Run with settings above

### Logs (if relevant)

Logs include INFO and DEBUG messages
