### ISSUE TITLE
[ML] "Get deployment stats failed" shown when ML is disabled

### ISSUE THREAD

**Issue by prwhelan** [elastic/elasticsearch#121532]
### Elasticsearch Version

8.17.0

### Java Version

_bundled_

### OS Version

All

### Problem Description

Logs show WARN related to ML errors when ML is disabled:
```
es01-1    | [14:27:20,222][WARN ][o.e.x.i.s.e.ElasticsearchInternalService] Get deployment stats failed, cannot update the endpoint's number of allocations
es01-1    | java.lang.IllegalStateException: failed to find action [cluster:internal/xpack/ml/trained_models/deployments/stats/get] to execute
es01-1    | 	at org.elasticsearch.client.internal.node.NodeClient.transportAction(NodeClient.java:135) ~[elasticsearch-8.17.0.jar:?]
es01-1    | 	at org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:108) ~[elasticsearch-8.17.0.jar:?]
es01-1    | 	at org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:84) ~[elasticsearch-8.17.0.jar:?]
es01-1    | 	at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:140) ~[elasticsearch-8.17.0.jar:?]
es01-1    | 	at org.elasticsearch.client.internal.FilterClient.doExecute(FilterClient.java:56) ~[elasticsearch-8.17.0.jar:?]
es01-1    | 	at org.elasticsearch.client.internal.OriginSettingClient.doExecute(OriginSettingClient.java:44) ~[elasticsearch-8.17.0.jar:?]
es01-1    | 	at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:140) ~[elasticsearch-8.17.0.jar:?]
es01-1    | 	at org.elasticsearch.xpack.inference.services.elasticsearch.ElasticsearchInternalService.updateModelsWithDynamicFields(ElasticsearchInternalService.java:847) ~[?:?]
es01-1    | 	at org.elasticsearch.xpack.inference.action.TransportGetInferenceModelAction.parseModels(TransportGetInferenceModelAction.java:168) ~[?:?]
es01-1    | 	at org.elasticsearch.xpack.inference.action.TransportGetInferenceModelAction.lambda$getAllModels$2(TransportGetInferenceModelAction.java:120) ~[?:?]
es01-1    | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:956) ~[elasticsearch-8.17.0.jar:?]
es01-1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
es01-1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
es01-1    | 	at java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

### Steps to Reproduce

1. Launch docker container for 8.17.0
2. Call `_xpack/usage`

```
version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es01-1
    environment:
      - node.name=es01-1
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo=/usr/share/elasticsearch/backup
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

volumes:
  data01:
    driver: local
  kibana-data01:
    driver: local

networks:
  elastic:
    driver: bridge
```
