### ISSUE TITLE
NPE on mapping merge for dense_vector field

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#125713]
### Elasticsearch Version

8.19+

### Java Version

_bundled_

### OS Version

na

### Problem Description

When attempting to update the mapping of a dense vector field that has dynamically set particular values, it may fail with an NPE. 

Specifically, this will occur with `dims`.

### Steps to Reproduce

```
---
"Test mapping update with dynamic dims":
  - requires:
      cluster_features: "gte_v8.16.0"
      reason: 'updatable dense vector field type for int4 was added in 8.16'
  - requires:
      test_runner_features: [ contains ]
  - do:
      indices.create:
        index: test_index

  - do:
      indices.put_mapping:
        index: test_index
        body:
          properties:
            embedding:
              type: dense_vector
              index_options:
                type: flat
  - do:
      index:
        index: test_index
        id: "40"
        body:
          embedding: [ 1, 1, 1, 11 ]
  - do:
      indices.flush: { }

  - do:
      indices.refresh: {}

  - do:
      indices.put_mapping:
        index: test_index
        body:
          properties:
            embedding:
              type: dense_vector
              index_options:
                type: int4_flat
```

### Logs (if relevant)

```
java.lang.NullPointerException
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.FieldMapper$Parameter.merge(FieldMapper.java:982) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.FieldMapper$Builder.merge(FieldMapper.java:1419) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:406) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:63) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.ObjectMapper$MergeResult.buildMergedMappers(ObjectMapper.java:716) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.ObjectMapper$MergeResult.build(ObjectMapper.java:638) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:234) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.Mapping.merge(Mapping.java:147) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.mergeMappings(MapperService.java:676) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.mergeMappings(MapperService.java:643) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataMappingService$PutMappingExecutor.applyRequest(MetadataMappingService.java:154) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataMappingService$PutMappingExecutor.execute(MetadataMappingService.java:117) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1076) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1039) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:246) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1692) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:465) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1689) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1284) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:465) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1263) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044) 
  at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) 
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095) 
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619) 
  at java.base/java.lang.Thread.run(Thread.java:1447) 
```
