### ISSUE TITLE
Error connecting to Elasticsearch." The Elasticsearch cluster is not reachable from python app in same docker network

### ISSUE THREAD

**Issue by Vijaygawate** [elastic/elasticsearch#127473]
### Elasticsearch Version

8.17

### Java Version

_bundled_

### OS Version

ubuntu

### Problem Description

I am using docker compose to create elasticsearch docker container using below compose file 

```
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=test
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - ES_JAVA_OPTS=-Xmx2g
      #- node.max_local_storage_nodes=6
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=500ms"]
      retries: 300
      interval: 1s
    volumes:
      #- ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      -  ./es_data:/usr/share/elasticsearch/data
```
Now, within the same docker-compose file, I have another Python app that is connecting to this Elasticsearch, but while trying, it says, **Error connecting to Elasticsearch." The Elasticsearch cluster is not reachable**.

Below is the way I am using to connect to elasticsearch

```
# Initialize components
post_process = PostProcessing()
es_connect = ESConnector()
es_host = environ.get("ELASTIC_SEARCH_HOST")
print(es_host)
es_user = environ.get("ELASTIC_SEARCH_NAME")
print(es_user)
es_password = environ.get("ELASTIC_SEARCH_PASSWORD")
print(es_password)
es = es_connect.connect_elasticsearch(es_host, es_user, es_password)
```
but when I am doing 
Telnet from another running container to the Elasticsearch container IP it is connecting to.

Am I using the old way of connecting to Elasticsearch, or what am I missing? I have tried with the Elasticsearch host and container IP as well but no luck

### Steps to Reproduce

custom app
