### ISSUE TITLE
"Unable to find client with name [default]" when using Azure Workload Identity for Azure repository

### ISSUE THREAD

**Issue by frasdav** [elastic/elasticsearch#128658]
### Elasticsearch Version

8.18.0

### Java Version

_bundled_

### OS Version

 AKSUbuntu-2204gen2containerd-202505.14.0

### Problem Description

I've followed the steps in https://www.elastic.co/docs/deploy-manage/tools/snapshot-and-restore/azure-repository to use Workload Identity Federation to authenticate an Azure repository, but I'm given the following error when verifying the connection:

`Unable to find client with name [default]`

### Steps to Reproduce

With ECK 2.16.1 installed, deploy the following resources:

```
---
# Source: eck-stack/charts/eck-kibana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prd
  labels:
    helm.sh/chart: eck-kibana-0.14.1
    app.kubernetes.io/name: eck-kibana
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: "nginx"
  rules:
  - host: "prd.foo.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prd-kb-http
            port:
              number: 5601
---
# Source: eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: prd
  labels:
    helm.sh/chart: eck-elasticsearch-0.14.1
    app.kubernetes.io/name: eck-elasticsearch
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  http:
    service:
      spec:
        type: LoadBalancer
  version: 8.18.0
  monitoring:
    logs:
      elasticsearchRefs:
      - name: monitoring
    metrics:
      elasticsearchRefs:
      - name: monitoring
  nodeSets:
    
    - config:
        node.roles:
        - master
      count: 1
      name: master
      podTemplate:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 1
                memory: 2Gi
          initContainers:
          - command:
            - sh
            - -c
            - sysctl -w vm.max_map_count=262144
            name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
          secureSettings:
          - secretName: keystore
          serviceAccountName: workload-identity
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: managed-csi-premium
    - config:
        node.roles:
        - data_hot
        - data_content
        - ingest
      count: 1
      name: hot
      podTemplate:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi
          initContainers:
          - command:
            - sh
            - -c
            - sysctl -w vm.max_map_count=262144
            name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
          secureSettings:
          - secretName: keystore
          serviceAccountName: workload-identity
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: managed-csi-premium
    - config:
        node.roles:
        - data_cold
      count: 1
      name: cold
      podTemplate:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi
          initContainers:
          - command:
            - sh
            - -c
            - sysctl -w vm.max_map_count=262144
            name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
          secureSettings:
          - secretName: keystore
          serviceAccountName: workload-identity
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: managed-csi-premium
    - config:
        node.roles:
        - data_frozen
      count: 1
      name: frozen
      podTemplate:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi
          initContainers:
          - command:
            - sh
            - -c
            - sysctl -w vm.max_map_count=262144
            name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
          secureSettings:
          - secretName: keystore
          serviceAccountName: workload-identity
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: managed-csi-premium
---
# Source: eck-stack/charts/eck-kibana/templates/kibana.yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: prd
  labels:
    helm.sh/chart: eck-kibana-0.14.1
    app.kubernetes.io/name: eck-kibana
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  version: 8.17.4
  count: 1
  elasticsearchRef:
    name: prd
  config:
    
    server.publicBaseUrl: https://prd.foo.com
  podTemplate:
    
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "52bf0fcd-740b-4e14-ae64-902dff87b8a0"
  name: workload-identity
---
apiVersion: v1
kind: Secret
metadata:
  name: keystore
type: Opaque
stringData:
  azure.client.default.account: sa0sbx0sbx0uks0eckdemo
---
apiVersion: v1
kind: Secret
metadata:
  name: eck-trial-license
  labels:
    license.k8s.elastic.co/type: enterprise_trial
  annotations:
    elastic.co/eula: accepted
```

Workload Identity itself is working fine, because I can do this on the same cluster:

```
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    azure.workload.identity/use: "true"
  name: azcli
  namespace: elastic
spec:
  serviceAccountName: workload-identity
  containers:
    - name: azcli
      image: mcr.microsoft.com/azure-cli:latest
      args:
        - /bin/bash
        - -c
        - sleep 9999
```
..and then:
```
kubectl exec -ti azcli -n elastic -- /bin/sh
az login --identity
```

### Logs (if relevant)

```
elasticsearch [2025-05-30T08:06:11,154[][WARN [][r.suppressed             [] [prd-es-master-0[] path: /_snapshot/Test/_verify, params: {repository=Test}, status: 500 org.elasticsearch.repositories.RepositoryVerificationException: [Test[] path  is not accessible on master node
elasticsearch Caused by: org.elasticsearch.common.settings.SettingsException: Unable to find client with name [default[]
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.AzureStorageService.getClientSettings(AzureStorageService.java:99)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.AzureStorageService.client(AzureStorageService.java:89)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.AzureBlobStore.getAzureBlobServiceClientClient(AzureBlobStore.java:632)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.AzureBlobStore.asyncClient(AzureBlobStore.java:628)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.AzureBlobStore.lambda$executeSingleUpload$19(AzureBlobStore.java:462)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:47)
elasticsearch     at java.base/java.security.AccessController.doPrivileged(AccessController.java:251)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:46)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.AzureBlobStore.executeSingleUpload(AzureBlobStore.java:461)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:386)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:116)
elasticsearch     at org.elasticsearch.repository.azure@8.18.0/org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlobAtomic(AzureBlobContainer.java:111)
elasticsearch     at org.elasticsearch.server@8.18.0/org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:2211)
elasticsearch     at org.elasticsearch.server@8.18.0/org.elasticsearch.repositories.RepositoriesService$4.doRun(RepositoriesService.java:549)
elasticsearch     at org.elasticsearch.server@8.18.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
elasticsearch     at org.elasticsearch.server@8.18.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
elasticsearch     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
elasticsearch     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
elasticsearch     at java.base/java.lang.Thread.run(Thread.java:1447)
```
