### ISSUE TITLE
[snapshot] support multiple credentials in elasticsearch.yml

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12935]
Based on https://github.com/elastic/elasticsearch-cloud-azure/pull/93#issuecomment-131810017

We need to support in  `elasticsearch.yml` multiple credentials.
We could imagine that as a generic feature whatever repository type you want to use.

Let say that we can now create something like:

```yml
cloud:
    azure:
        storage:
            azure1:
              account: your_azure_storage_account1
              key: your_azure_storage_key1
              default: true
            azure2:
              account: your_azure_storage_account2
              key: your_azure_storage_key2
            azure3:
              account: your_azure_storage_account3
              key: your_azure_storage_key3
```

Then when we create the repo, we can specify which credentials we want to use:

```
# use credentials 2
PUT _snapshot/my_backup2
{
  "type": "azure",
  "settings": {
      "creadentials": "azure2",
      "container": "backup_container",
      "base_path": "backups"
  }
}

# This one will use the one marked as "default"
PUT _snapshot/my_backup3
{
  "type": "azure"
}
```
