### ISSUE TITLE
Bug with simple_query_string, minimum_should_match, and multiple fields.

### ISSUE THREAD

**Issue by davidlbowen** [elastic/elasticsearch#13884]
```
# With a one-word query and minimum_should_match=-50%, adding extra non-matching fields should not matter.
# Tested on v1.7.2.

# delete and re-create the index
curl -XDELETE localhost:9200/test
curl -XPUT localhost:9200/test

echo 

 # insert a document
curl -XPUT 'http://localhost:9200/test/test/1' -d '
 { "title": "test document"}
 '
curl -XPOST 'http://localhost:9200/test/_refresh'

echo 

 # this correctly finds the document (f1 is a non-existent field)
 curl -XGET 'http://localhost:9200/test/test/_search' -d '{
  "query" : {
    "simple_query_string" : {
      "fields" : [ "title", "f1" ],
      "query" : "test",
      "minimum_should_match" : "-50%"
    }
  }
 }
'

echo 

# this incorrectly does not find the document (f1 and f2 are non-existent fields)
curl -XGET 'http://localhost:9200/test/test/_search' -d '{
  "query" : {
    "simple_query_string" : {
      "fields" : [ "title", "f1", "f2" ],
      "query" : "test",
      "minimum_should_match" : "-50%"
    }
  }
 }
'

echo
```

**Comment by clintongormley** [comment]
This does look like a bug.  The min_should_match is being applied at the wrong level:

    GET /test/test/_validate/query?explain
    {
      "query" : {
        "simple_query_string" : {
          "fields" : [ "title", "f1", "f2" ],
          "query" : "test",
          "minimum_should_match" : "-50%"
        }
      }
    }

Returns an explanation of:

    +((f1:test title:test f2:test)~2)

While the `query_string` and `multi_match` equivalents return:

    +(title:test | f1:test | f2:test)

**Comment by cbuescher** [comment]
I had a look and saw that `simple_query_string` iterates over all fields for each token in the query string and combines them all in boolean query `should` clauses, and we apply the `minimum_should_match` on the whole result. 

@clintongormley As far as I understand you, we should parse parse the query string for each field separately, apply the `minimum_should_match` there and then combine the result in an overall Boolean query. This however raised another question for me. Suppose we have two terms like `"query" : "test document"` instead, then currently we we get:

'''
(f1:test title:test f2:test) (f1:document title:document f2:document))~1
'''

If we would instead create the query per field individually we would get something like

'''
((title:test title:document)~1 (f1:test f1:document)~1 (f2:test f2:document)~1)
'''

While treating the query string for each field indicidually looks like the right behaviour in this case, I wonder if this will break other cases. wdyt?

**Comment by clintongormley** [comment]
@cbuescher the `query_string` query takes the same approach as your first output, ie:

    ((f1:test title:test f2:test) (f1:document title:document f2:document))~1

I think the bug is maybe a bit more subtle.  A query across 3 fields for two terms with min should match 80% results in:

    bool:
        min_should_match: 80% (==1)
        should:
          bool:
            should: [ f1:term1, f2:term1, f3:term1]
          bool:
            should: [ f1:term2, f2:term2, f3:term2]

however with only one term it is producing:

    bool:
      min_should_match: 80% (==2) 
      should: [ f1:term1, f2:term1, f3:term1]

In other words, min should match is being applied to the wrong `bool` query.  Instead, even the one term case should be wrapped in another `bool` query, and the min should match should be applied at that level.

**Comment by cbuescher** [comment]
@clintongormley Yes, I think thats what I meant. I'm working on a PR that applies the `minimum_should_match` to sub-queries that only target one field. That way your examples above would change to something like

```
bool:    
    should:
      bool:
        min_should_match: 80% (==1)
        should: [ f1:term1, f1:term2]
      bool:
        min_should_match: 80% (==1)
        should: [ f2:term1, f2:term2]
      bool:
        min_should_match: 80% (==1)
        should: [ f3:term1, f3:term2]
```
and for one term

```
bool:    
    should:
      bool:
        min_should_match: 80% (==0)
        should: [ f1:term1]
      bool:
        min_should_match: 80% (==0)
        should: [ f2:term1]
      bool:
        min_should_match: 80% (==0)
        should: [ f3:term1]
```
In the later case we already additionally simplify one-term bool queries to TermQueries.
