### ISSUE TITLE
copy_to of mapper attachments metadata field isn't working

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#14946]
_From @gpaul on November 17, 2015 10:43_

The following set of steps against a fresh elasticsearch 2.0.0 instance with v3.0.2 of this plugin installed shows that copy_to isn't working for the name field. I doubt it is working for the other metadata fields, either.

You can copy/paste this in your shell.
```
# create a mapping
curl -XPOST 'http://localhost:9200/test_copyto' -d '{
  "mappings": {
    "person": {
      "properties": {
        "copy_dst": { "type": "string" },
        "doc": {
	  "type": "attachment",
	  "fields": {
	    "name": { "copy_to": "copy_dst" }
          }
	}
      }
    }
  }
}'
## => {"acknowledged":true}


# index a document, specifying a document name
curl -XPOST 'http://localhost:9200/test_copyto/person/1' -d '{
  "doc": {
    "_content": "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0=",
    "_name": "my-attachment-name.doc"
  }
}'
## => {"_index":"test_copyto","_type":"person","_id":"1","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}


# search for the document by its contents
curl -XPOST 'http://localhost:9200/test_copyto/person/_search' -d '
{
  "query": {
    "query_string": {
      "default_field": "doc.content",
      "fields": ["copy_dst", "doc.content"],
      "query": "ipsum"
    }
  }
}
'
## => {"took":5,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits": "total":1,"max_score":0.04119441,"hits":[{"_index":"test_copyto","_type":"person","_id":"1","_score":0.04119441,"_source":{
#  "doc": {
#    "_content": "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0=",
#    "_name": "my-attachment-name.doc"
#  }
#}}]}}


# search for the document by its name
curl -XPOST 'http://localhost:9200/test_copyto/person/_search' -d '
{
  "query": {
    "query_string": {
      "default_field": "doc.name",
      "fields": ["doc.name"],
      "query": "my-test.doc"
    }
  }
}
'
## => {"took":5,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":0.02250402,"hits":[{"_index":"test_copyto","_type":"person","_id":"1","_score":0.02250402,"_source":{
#  "doc": {
#    "_content": "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0=",
#    "_name": "my-attachment-name.doc"
#  }
#}}]}}

# search for the document by the copy_dst field
curl -XPOST 'http://localhost:9200/test_copyto/person/_search' -d '
{
  "query": {
    "query_string": {
      "default_field": "copy_dst",
      "fields": ["copy_dst"],
      "query": "my-test.doc"
    }
  }
}
'
## => {"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
```

_Copied from original issue: elastic/elasticsearch-mapper-attachments#190_

**Comment by dadoonet** [comment]
_From @gpaul on November 23, 2015 13:37_

Ping. Should I open this issue against the main elasticsearch repository now that this plugin is moving there?

**Comment by dadoonet** [comment]
Did you try the same script with elasticsearch 1.7? I'd like to know if it's a regression or if it has always been there.

I know that copy_to feature is supposed to work for the extracted text but I don't think it worked for metadata.

If I'm right (so it's not an issue but more a feature request), then you can open it in elasticsearch repo.
If I'm wrong (so it's a regression), then keep it here.

**Comment by dadoonet** [comment]
_From @gpaul on November 23, 2015 14:58_

It seems like a regression:
elasticsearch 1.7.0 with mapper-attachments 2.7.1
yields
```
curl -XPOST 'http://localhost:9200/test_copyto/person/_search' -d '
 {
   "query": {
     "query_string": {
       "default_field": "copy_dst",
       "fields": ["copy_dst"],
       "query": "my-test.doc"
     }
   }
 }
 '
#{"took":3,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":0.02250402,"hits":[{"_index":"test_copyto","_type":"person","_id":"1","_score":0.02250402,"_source":{
#  "doc": {
#    "_content": "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0=",
#    "_name": "my-test.doc"
#  }
#}}]}}

**Comment by dadoonet** [comment]
Thank you @gpaul

**Comment by dadoonet** [comment]
_From @hhoechtl on November 23, 2015 15:2_

It's also not working with the .content field

**Comment by dadoonet** [comment]
I created a test for elasticsearch 1.7 and it is working well in 1.x series:

```java
@Test
public void testCopyToMetaData() throws Exception {
    String mapping = copyToStringFromClasspath("/org/elasticsearch/index/mapper/attachment/test/integration/simple/copy-to-metadata.json");
    byte[] txt = copyToBytesFromClasspath("/org/elasticsearch/index/mapper/attachment/test/sample-files/text-in-english.txt");

    client().admin().indices().putMapping(putMappingRequest("test").type("person").source(mapping)).actionGet();

    index("test", "person", jsonBuilder().startObject()
            .startObject("file")
            .field("_content", txt)
            .field("_name", "name")
            .endObject()
            .endObject());
    refresh();

    CountResponse countResponse = client().prepareCount("test").setQuery(queryStringQuery("name").defaultField("file.name")).execute().get();
    assertThatWithError(countResponse.getCount(), equalTo(1l));

    countResponse = client().prepareCount("test").setQuery(queryStringQuery("name").defaultField("copy")).execute().get();
    assertThatWithError(countResponse.getCount(), equalTo(1l));
}
```

I created a test for 2.* branches which demonstrates the regression from 2.0.
It can be reused to fix this issue: https://github.com/elastic/elasticsearch-mapper-attachments/commit/30aeda668a9090f28929a74d59b9bf81e1738161:

```yml
"Copy To Feature":

    - do:
        indices.create:
            index: test
            body:
              mappings:
                doc:
                  properties:
                    copy_dst:
                      type: string
                    doc:
                      type: attachment
                      fields:
                        name:
                          copy_to: copy_dst
    - do:
        cluster.health:
          wait_for_status: yellow

    - do:
        index:
            index: test
            type: doc
            id: 1
            body:
              doc:
                _content: "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0="
                _name: "name"

    - do:
        indices.refresh: {}

    - do:
        search:
            index: test
            body:
                query:
                    match:
                        doc.content: "ipsum"

    - match: { hits.total: 1 }

    - do:
        search:
            index: test
            body:
                query:
                    match:
                        doc.name: "name"

    - match: { hits.total: 1 }

    - do:
        search:
            index: test
            body:
                query:
                    match:
                        copy_dst: "name"

    - match: { hits.total: 1 }
```

@rjernst Could you give a look please?
