### ISSUE TITLE
Index creation via tribe node

### ISSUE THREAD

**Issue by rashidkpc** [elastic/elasticsearch#15620]
Currently the tribe node does not support things like index and mapping creation. This presents a problem for Kibana users that utilize a tribe node, requiring them to first point kibana at a single cluster, then stop it and point it at the tribe node. 

Ideally the tribe node could be configured to route requests matching a given pattern to a particular cluster. It could be configured much the way we do the `tribe.blocks` section today, but say, `tribe.route`. This would/could also work for users that need to write to indices that exist on several clusters that a tribe node points to

Something like:

```
tribe:
  routes:
    indices.create: 
      .kibana: cluster1
    indices.write:
      myIndex-*: cluster2
```
