### ISSUE TITLE
Inconsistent results using tribe node with transport client

### ISSUE THREAD

**Issue by nirajpatel** [elastic/elasticsearch#15928]
Hi! I am using a tribe node with the transport client to connect to 2 clusters. When I look at **_cat/indices** I see consistent indexes. When I use the transport client with the below **does the specified index exist?** request I get true 50% of the time and false 50% of the time although the index does in fact exist.

Code:

``` java
public boolean indexExists(String index, TransportClient client) {
    return client.admin().indices().exists(new IndicesExistsRequest(index)).actionGet().isExists();
}
```

YML settings:

```
tribe:
    t1:
        cluster.name: clusterone
        discovery.zen.ping.multicast.enabled: false
        discovery.zen.ping.unicast.hosts: clusterone-master-a,clusterone-master-b,clusterone-master-c
    t2:
        cluster.name: clustertwo
        discovery.zen.ping.multicast.enabled: false
        discovery.zen.ping.unicast.hosts: clustertwo-master-a,clustertwo-master-b,clustertwo-master-c
```
