### ISSUE TITLE
Failed to create repository Unknown [repository] type [azure]

### ISSUE THREAD

**Issue by jorgemrsantos** [elastic/elasticsearch#16558]
I just installed the azure plugin and I'm getting this weird error when I try to create the repository:

```sh
curl -XPUT 'http://localhost:9200/_snapshot/azure_backup' -d '{"type": "azure", "settings": { "container": "backups"}}'
```

returns

```
{"error":{"root_cause":[{"type":"repository_exception","reason":"[azure_backup] failed to create repository"}],"type":"repository_exception","reason":"[azure_backup] failed to create repository","caused_by":{"type":"illegal_argument_exception","reason":"Unknown [repository] type [azure]"}},"status":500}
```

I don't think its about my the configuration as I was getting the same error for an S3 type repository, installed the S3 plugin and started getting  "No bucket defined for s3 gateway" which makes sense to me.

I'm just using the repo for EC snapshots and my config is pretty straightforward:

```
cloud:
   azure:
      management:
          subscription.id: xxxxx
      storage:
          accountfilipe:
              account: elasticsearch
              key: xxxxx
``` 

Please help 😩😩😩
