### ISSUE TITLE
service_account is not filtered in GCS repository

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#18946]
Related to #18945 and to this https://github.com/elastic/elasticsearch/commit/35d3bdab84fa05c71e8ae019aaf661759c8b1622#commitcomment-17914150

In GCS Repository plugin we defined a `service_account` setting which is defined as `Property.Filtered`.

```java
public static final Setting<String> SERVICE_ACCOUNT = simpleString("service_account", Property.NodeScope, Property.Dynamic, Property.Filtered);
```

But as this setting is not registered when the plugin starts, it's not shaded when you ask for `GET _snapshot/gcsrepo`.

We should either remove `Filtered` if it does not make any sense to filter it or register the setting or wait for a fix for #18945.

If we want to keep it, we can add a REST test like this one: https://github.com/elastic/elasticsearch/blob/master/plugins/repository-s3/src/test/resources/rest-api-spec/test/repository_s3/20_repository.yaml

```yaml
# Integration tests for Repository GCS component
#
"GCS repository can be registered":
    - do:
        snapshot.create_repository:
          repository: test_repo_gcs_1
          verify: false
          body:
            type: gcs
            settings:
              service_account: "whatever"

    # Get repository
    - do:
        snapshot.get_repository:
          repository: test_repo_gcs_1

    - is_true: test_repo_gcs_1
    - is_false: test_repo_gcs_1.settings.service_account
```
