### ISSUE TITLE
File based Unicast Host Provider

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#20323]
The unicast host list determines the list of port and ips an Elasticsearch node ping when it starts up and tries to find the cluster. The same list is used upon master lost and election start.

It has been long requested to be able to update this list via an API. That presented a challenge since, unlike other setting changes, this information can not be easily serialized in the cluster state as it needs to be used when the node, for example, is restarted.

An alternative is for us to develop a plugin that, similarly to the current EC2 discovery plugin, monitors a separate (configurable) file and supplies the list of port/ips stored in it when needed (i.e., when pinging starts).

The format for the file should be simple and contain one hostname/ip per line (in the same format the current yml file supports).

**Comment by djschny** [comment]
Can it be a URL? That way folks to point it git repo URL, file on disk, apache hosted file, etc. to make global updating for the cluster much easier.

**Comment by nik9000** [comment]
> That way folks to point it git repo URL, file on disk, apache hosted file, etc. to make global updating for the cluster much easier.

I feel like a local file is the most stable thing and the best thing if you have any sort of configuration management system. I get that we could get http for free with the JVM but this opens up a whole can of worms I'd rather not deal with like "what about https? what about certs? what about `git://`?"

**Comment by jasontedor** [comment]
> Can it be a URL? That way folks to point it git repo URL, file on disk, apache hosted file, etc. to make global updating for the cluster much easier.

These can't easily be watched, but a file on disk can. And if we could connect to arbitrary resources via a URI, now we have a whole ton of complexity to worry about if the service is down. Finally, every respectable configuration management system can source from these suggestions and push updated configs to the relevant nodes. I really think can and should just keep it simple here.

**Comment by bleskes** [comment]
>  I really think can and should just keep it simple here.
+1

Note that urls can bring a whole can of worms? what if they time out? how long should we wait? should we cache last results? etc.

> These can't easily be watched, but a file on disk can

We don't really need to watch (although possible) - we can just read the file content when a ping round starts.

**Comment by s1monw** [comment]
++ to keep it simple! The way to manage a file in a central / global way is know and proven, let's not reinvent the wheel.

**Comment by jasontedor** [comment]
> We don't really need to watch (although possible) - we can just read the file content when a ping round starts.

Sure, that's fine, but I do think it's operationally more friendly to emit a log line communicating that the new configuration file was picked up.

**Comment by muradm** [comment]
Does this feature intended to close the gap with discovery tools like Consul, Etcd etc? If yes or no, what is the intended use case?

**Comment by bleskes** [comment]
> close the gap with discovery tools like Consul, Etcd etc? 

Care to describe the specifics of that gap? Without it it's hard to give a definitive answer.

**Comment by muradm** [comment]
Elasticsearch currently relying on zen unicast discovery, where I have to provide list of hosts in advance. But in automated environment I don't know actual IP addresses or hosts that will be assigned to servers, containers, VMs etc. Explaining my last case:

This basically leads for such ugly configurations like below.
```
  logs-es:
    container_name: logs-es-${HOSTNAME}
    hostname: logs-es-${HOSTNAME}
    logging:
      options:
        tag: logs-es
    image: elasticsearch:5.0.0-alpha5
    volumes_from:
      - logs-es-data
    command: >
      -Ecluster.name=rwb-logs -Enode.data=true -Enode.master=true
      -Ediscovery.zen.minimum_master_nodes=2
      -Ediscovery.zen.ping.unicast.hosts=logs-es-lab1,logs-es-lab2,logs-es-lab3
    restart: unless-stopped
    environment:
      SERVICE_NAME: logs-es
      SERVICE_9200_TAGS: ${HOSTNAME},traefik.frontend.rule=Host:logs-es
      SERVICE_9300_TAGS: ${HOSTNAME},traefik.enable=false
      ES_JAVA_OPTS: "-Xms2G -Xmx2G"
    depends_on:
      - registrator
    extra_hosts:
      - "logs-es-lab1:10.20.5.1"
      - "logs-es-lab2:10.20.5.2"
      - "logs-es-lab3:10.20.5.3"
    networks:
      service:
        ipv4_address: ${LOGS_ES_HOSTADDR}
```
This is a snippet from long `docker-compose.yml` file. With current Elasticsearch I have to specify host names and IP addresses. There is already another related issue #14441. As mentioned above, the main problem I think that should be solved, is that we don't know in advance IP address or host names. Which is actually the basic property of scalable environment.

Consul (or any other similar tool) manage DNS entries for hosts, containers etc. And also services. In this example, 3 Elasticsearch instances once booted, will have the following entry in DNS:
```
# nslookup logs-es-9200.service.consul
Server:		10.10.110.31
Address:	10.10.110.31#53

Name:	logs-es-9200.service.consul
Address: 10.20.5.1
Name:	logs-es-9200.service.consul
Address: 10.20.5.3
Name:	logs-es-9200.service.consul
Address: 10.20.5.2
```
With proper tagging in Consul, I also get per instance lookups.
```
# nslookup lab1.logs-es-9200.service.consul
Server:		10.10.110.31
Address:	10.10.110.31#53

Name:	lab1.logs-es-9200.service.consul
Address: 10.20.5.1

# nslookup lab2.logs-es-9200.service.consul
Server:		10.10.110.31
Address:	10.10.110.31#53

Name:	lab2.logs-es-9200.service.consul
Address: 10.20.5.2

# nslookup lab3.logs-es-9200.service.consul
Server:		10.10.110.31
Address:	10.10.110.31#53

Name:	lab3.logs-es-9200.service.consul
Address: 10.20.5.3
```
From the above, I can generate any type of configuration file. For instance [consul-template](https://github.com/hashicorp/consul-template) tool can generate that. For Etcd it is [confd](http://www.confd.io/). I believe that similar tools exists for other environments. So problem here is not in configuration file it self.

Because of #14441, I have to do:
```
    extra_hosts:
      - "logs-es-lab1:10.20.5.1"
      - "logs-es-lab2:10.20.5.2"
      - "logs-es-lab3:10.20.5.3"
    networks:
      service:
        ipv4_address: ${LOGS_ES_HOSTADDR}
```
I.e. preassign hostnames and IP addresses. Because when there is no instance running, i.e. not at all, if in zen unicast hosts list I put
```
[ "lab1.logs-es-9200.service.consul", "lab2.logs-es-9200.service.consul", "lab3.logs-es-9200.service.consul" ]
```
or any other configuration file which ever will be provided, Elasticsearch will not work. It will fail, because DNS will return error as `can't find host`.

Let's say lab4 is going to start, once service is changed in Consul catalog, consul-template will update configurations to:

```[ "lab1.logs-es-9200.service.consul", "lab2.logs-es-9200.service.consul", "lab3.logs-es-9200.service.consul", "lab4.logs-es-9200.service.consul" ]```

Configuration file generating tool, if necessary restart processes. In gossip like clusters, even restart is not needed.
If really necessary to inform the process about update, you can implement kill -HUP to force file re-reading. Also can be done by configuration generating tool.

So basically, if we are running in service discoverable environment, in some or another way, we can generate the configuration file and inform the process or restart it.

Of course, may be I don't see the intended use case for externalizing unicast hosts list. Instead of doing that, I would appreciate that #14441 is solved. Or one of these become more standard and the part of base:

* [SRV discovery](https://github.com/github/elasticsearch-srv-discovery) - this tries to relay on DNS
* [Consul](https://github.com/lithiumtech/elasticsearch-consul-discovery)
* [Etcd](https://github.com/nuxeo/elasticsearch-cloud-etcd)

None of them are working out of the box. However in my opinion:

* DNS is pretty standard. Just resolve a service domain name, and get list of cluster members. Since DNS is UDP based, no worms like mentioned above. Of course still DNS query timeout, but this is really standard.

* KV store is almost pretty standard, many environments implement that. Consul, Docker, Etcd etc. As how much inter operating they are, needs to be investigated of course.

In any case, year 2016.. having one configuration file? :-)
