### ISSUE TITLE
Query with filter returns wrong documents

### ISSUE THREAD

**Issue by Thermi** [elastic/elasticsearch#21885]
**Elasticsearch version**:  2.4.2

**Plugins installed**: [cloud-aws]

**JVM version**: 1.8.0.111

**OS version**: CentOS 7.

**Description of the problem including expected versus actual behavior**:

We're running queries with filters on an ElasticSearch cluster. The query returns documents that have values that are not allowed by the filter. The attached es_trace.txt contains a representation of the `curl` commands as they would be used on the command line. We're using elastalert by yelp to try to alert when certain fields are out of range or generally, when nodes are loaded too much or other problems appear. elastalert does not use curl directly. When it's used in debug mode, it only prints out the HTTP requests it does as curl commands.

The relevant parts are the following:
**Steps to reproduce**:
 1. A query with the range filter is run on an ElasticSearch cluster.
```
                  "range": {
                    "Metrics.cpu/node_utilization.value": {
                      "gte": 0.8,
                      "lte": 1.0
                    }
                  }
```
2. The cluster returns a document with values outside of the defined range
```
    "cpu/node_utilization": {
        "value": 0.522
    }
```
**Provide logs (if relevant)**:

Attached [es_trace.txt](https://github.com/elastic/elasticsearch/files/621983/es_trace.txt) shows compatible CURL commands.
Attached [heapster-mapping-formatted.txt](https://github.com/elastic/elasticsearch/files/621982/heapster-mapping-formatted.txt) shows the mapping the indice uses.

elastalert rule (Represented as `curl` command in es_trace.txt):
```
name: CPU usage for master node ip-10-0-0-50.eu-west-1.compute.internal
type: frequency
index: heapster-cpu-*
timestamp_field: CpuMetricsTimestamp
num_events: 1
timeframe:
    minutes: 15

filter:
- and:
   - term:
       "MetricsTags.type" : "node"
   - term:
       "MetricsTags.hostname.raw": "ip-10-0-0-50.eu-west-1.compute.internal"
   - range:
       "Metrics.cpu/node_utilization.value":
         gte: 0.800
         lte: 1.000
```

elastalert output and the matched document:
```
INFO:elastalert:CPU usage for master node ip-10-0-0-50.eu-west-1.compute.internal

At least 1 events occurred between 2016-10-31 00:00 UTC and 2016-10-31 00:15 UTC

CpuMetricsTimestamp: 2016-10-31T00:15:00Z
Metrics: {
    "cpu/limit": {
        "value": 110
    }, 
    "cpu/node_allocatable": {
        "value": 1000
    }, 
    "cpu/node_capacity": {
        "value": 1000
    }, 
    "cpu/node_reservation": {
        "value": 0.51
    }, 
    "cpu/node_utilization": {
        "value": 0.522
    }, 
    "cpu/request": {
        "value": 510
    }, 
    "cpu/usage": {
        "value": 1424597826878037
    }, 
    "cpu/usage_rate": {
        "value": 522
    }
}
MetricsTags: {
    "host_id": "i-0a7fdff8610772107", 
    "hostname": "ip-10-0-0-50.eu-west-1.compute.internal", 
    "labels": "beta.kubernetes.io/arch:amd64,beta.kubernetes.io/instance-type:m3.medium,beta.kubernetes.io/os:linux,controller:true,failure-domain.beta.kubernetes.io/region:eu-west-1,failure
-domain.beta.kubernetes.io/zone:eu-west-1a,kubernetes.io/hostname:ip-10-0-0-50.eu-west-1.compute.internal", 
    "nodename": "ip-10-0-0-50.eu-west-1.compute.internal", 
    "type": "node"
}
_id: 143be7ec-9eff-11e6-9941-2aa42b43b130
_index: heapster-2016.10.31
_type: cpu
```
