### ISSUE TITLE
[TEST] Incorrect order for the `warnings` clause in the YAML tests

### ISSUE THREAD

**Issue by karmi** [elastic/elasticsearch#21979]
As part of 1e58740 (and other commits), support for a `warnings` clause has been added to the YAML test definitions. However, the example in the README, and the usage in test files has an incorrect order -- it precedes the _operation_ in the `do` section:

```yaml
- do:
        warnings:
            - '[index] is deprecated'
            - ...
        get:
            index:    test
            type:    test
            id:        1
```

The `warnings` clause should come _after_ the `get` operation here (as opposed to the `catch` clause, where it makes sense to list it first, respecting the usual programming language notation).

-----

/cc @elastic/es-clients
