### ISSUE TITLE
Getting all snapshots with a secondary only azure repository takes a long time

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#23480]
**Elasticsearch version**: 5.2.1
**Plugins installed**: `repository-azure`

I created an azure storage account with [Read-access geo-redundant storage (RA-GRS)](https://docs.microsoft.com/en-us/azure/storage/storage-redundancy#read-access-geo-redundant-storage).
Then I configure `elasticsearch.yml` with:

```yml
cloud:
    azure:
        storage:
            my_account:
                account: ACCOUNT
                key: KEY
```

Then:

```
PUT _snapshot/primary
{
  "type": "azure",
  "settings": {
    "account": "my_account",
    "container": "container"
  }
}
GET _snapshot/primary/_all
```

This takes less than a second.

```
PUT _snapshot/secondary
{
  "type": "azure",
  "settings": {
    "account": "my_account",
    "container": "container",
    "location_mode": "secondary_only"
  }
}
GET _snapshot/secondary/_all
```

This takes something like 5 minutes.

This seems to be a regression from 5.1 series.
