### ISSUE TITLE
es crashes with "Native controller process has stopped - no new native processes can be started"

### ISSUE THREAD

**Issue by samuelcolvin** [elastic/elasticsearch#25067]
Running elastic search with docker as suggested in the docs (except only one elasticsearch instance), more details in compose file [here](https://github.com/tutorcruncher/morpheus/blob/master/docker-compose.yml#L16-L31).

everything appears to be running fine, then elastic search gives one log messages and crashes:

```
[2017-06-05T23:39:30,361][INFO ][o.e.x.m.j.p.NativeController] Native controller process has stopped - no new native processes can be started
```

I've had this error followed by a crash quite a few time today while testing a new setup. Details are all on the most recent crash as I have most details for that one.

**Elasticsearch version**: docker `docker.elastic.co/elasticsearch/elasticsearch:5.4.1`

**Plugins installed**: just standard docker image - xpack

**JVM version** (`java -version`):just standard docker image

**OS version** (`uname -a` if on a Unix-like system): host os `Ubuntu 16.04.1 LTS`

**Description of the problem including expected versus actual behavior**:

The only actions occurring on the server just be the crash was a new docker container coming up and checking an elasticsearch index existed index.

**Steps to reproduce**:

Not yet sure what correlates with the crash, I'll give more details if I can.

**Provide logs (if relevant)**:

```
[2017-06-05T23:09:13,423][INFO ][o.e.c.r.a.AllocationService] [QsSRzjs] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.monitoring-es-2-2017.06.05][0]] ...]). 
[2017-06-05T23:39:30,361][INFO ][o.e.x.m.j.p.NativeController] Native controller process has stopped - no new native processes can be started 
[2017-06-05T23:40:20,298][INFO ][o.e.n.Node               ] [] initializing ... 
```

These logs just show that elasticsearch gave no log messages before the crash, then restarts 50 seconds after the crash.

**Comment by jasontedor** [comment]
I do not think that that log message is the problem, rather I think that your processes are being killed, perhaps by the system OOM killer. I think that you need to investigate this on your end. Since we reserve GitHub for verified bug reports and feature requests, I'm going to close this issue. If you need additional help, please ask on the [forum](https://discuss.elastic.co). We can reopen this issue if a verified bug is discovered here.

**Comment by samuelcolvin** [comment]
I subisquently got lots of errors, notable in the logs `java.io.IOException: Cannot allocate memory`.

The server has 16GB of memory but elastic search was constrained to 1GB as per the default docker compose example.

In the end I removed
```
    - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
```

and so far crashes seem to haved stopped. fingers crossed.

**Comment by gertcuykens** [comment]
I have the same issue running docker on mac, a empty elasticsearch should be able to run on the default 1g and not crash and run your cpu through the roof.

<img width="798" alt="screen shot 2017-06-14 at 16 07 34" src="https://user-images.githubusercontent.com/863731/27138746-82f8d800-5121-11e7-825a-679090106454.png">

**Comment by samuelcolvin** [comment]
I haven't had another crash (AFAIK) of elasticsearch since I removed the memory limits.

For me there's definitely some problem with es running on docker with the default setup, eg. with memory constraint.

Will be interesting to see if anyone actually looks into this or bothers to reply.

**Comment by gertcuykens** [comment]
I suspect docker doesn't like ES file system management. And bumping up the ram just make it use the filesystem less until you really pushing it. Try pushing your server to the limit, I suspect it will crash again as soon as the file system can't handle it anymore under docker.

**Comment by samuelcolvin** [comment]
@jasontedor is that possible?

If so it's pretty serious.

I'm using a docker volume mounted at `/usr/share/elasticsearch/data` so in theory the filesystem should look to ES as if it were running on the host.

**Comment by samuelcolvin** [comment]
Also if this is the case, either ES or docker should definitely give some kind of error message when crashing.

**Comment by gertcuykens** [comment]
they mention something here on node stability and swap files https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Comment by samuelcolvin** [comment]
Ok, I've researched this a bit more. I think think the problem is actually that ES was hitting the memory limit set by docker.

The suggested setup (which I used at first without thinking) was
```yaml
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
```
In other works "the container gets 1g, the max java heap size is 512mb". But I think the ES container might sometimes need more than 512mb of extra RAM.

For example I now have

```yaml
    - "ES_JAVA_OPTS=-Xms7g -Xmx7g"
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
    mem_limit: 8g
```

and docker stats shows
```
CPU %        MEM USAGE / LIMIT     MEM %    NET I/O             BLOCK I/O    PIDS
1.35%        7.493GiB / 8GiB       93.66%   4.63kB / 3.52kB     0B / 659kB   90
```

**Comment by gertcuykens** [comment]
Still expect error message out of memory or something :P And definitely not a cpu going A wall and die silently :) My fix to not crash on first query was `docker run -d -p 9200:9200 -e "http.host=0.0.0.0" -e "bootstrap_memory_lock=true" --ulimit memlock=-1:-1 -v ~/.data/:/usr/share/elasticsearch/data/ --name ES docker.elastic.co/elasticsearch/elasticsearch:5.4.1`

**Comment by samuelcolvin** [comment]
Are you sure the CPU load is not because the container is constantly restart?

**Comment by gertcuykens** [comment]
I can reproduce the cpu explode by doing this, but ES doesn't crash anymore

docker run --rm -it -v ~/.pipeline/:/usr/share/logstash/pipeline/ --link ES:elasticsearch docker.elastic.co/logstash/logstash:5.4.1

`~/.pipeline/input.conf`
```
input {
  heartbeat {
    interval => 5
    message  => 'Hello from Logstash 💓'
  }
}

output {
  elasticsearch {
    hosts    => [ 'elasticsearch' ]
    user     => 'elastic'
    password => 'changeme'
  }
}
```

**Comment by gertcuykens** [comment]
If i wait long enough doing the above ES craches anyway... so I am back to square one, it just takes longer to crash now with `-e "bootstrap_memory_lock=true" --ulimit memlock=-1:-1`

**Comment by kozchris** [comment]
I'm also seeing this issue using Elastic with Docker on a Mac.

**Comment by everaldo** [comment]
I've solved limiting ES container memory, as stated on this link:

https://github.com/10up/wp-local-docker/issues/6

ES_JAVA_OPTS: "-Xms750m -Xmx750m"

**Comment by martin-g** [comment]
The freshly released Elasticsearch 7.0.0 now fails in Docker with:

```
elasticsearch    | ERROR: [1] bootstrap checks failed
elasticsearch    | [1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
...
elasticsearch    | {"type": "server", "timestamp": "2019-04-11T08:50:36,014+0000", "level": "INFO", "component": "o.e.x.m.p.NativeController", "cluster.name": "docker-cluster", "node.name": "e3ba2e1dd40c",  "message": "Native controller process has stopped - no new native processes can be started"  }
elasticsearch exited with code 78
```

Here is my docker-compose config:
```
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    command: elasticsearch
    environment:
      - cluster.initial_master_nodes[0]=localhost
      - cluster.name=demo-es
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - /store2/demo/es/data:/usr/share/elasticsearch/data
      - /store2/demo/es/logs:/usr/share/elasticsearch/logs
    networks:
      - esnet
    healthcheck:
      test: curl -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
```

Even though I have `discovery.type=single-node` it still tries to find master nodes or seeds.
Anyone knows what is the proper syntax to pass `cluster.initial_master_nodes` as environment variable. My attempt above does not work, neither `- cluster.initial_master_nodes="[localhost]".
