### ISSUE TITLE
Elasticsearch 2.3.4 snapshot not working with AWS S3 bucket

### ISSUE THREAD

**Issue by Kalesberg** [elastic/elasticsearch#26164]
**Our Elasticsearch server details**:

**Elasticsearch version**: 2.3.4

**Plugins installed**: [marvel, license, cloud-aws]

**JVM version** (`1.8`):

**OS version** (Linux ubuntu 4.9.15-x86_64-linode81):

**Problem**:
Our server has millions of documents with 3 indices on 5 nodes. We are going to make some changes to our ES server and before that we need to backup the database.
The server nodes are hosted on Linode.com and we provided correct bucket name, region and endpoint to the aws configuration.
However, when we are actually call snapshot api we get this error:
```
{
    "error": {
        "root_cause": [
            {
                "type": "amazon_s3_exception",
                "reason": "amazon_s3_exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: C4C59458A3683CD4)"
            }
        ],
        "type": "snapshot_creation_exception",
        "reason": "[s3repo:snapshot_1] failed to create snapshot",
        "caused_by": {
            "type": "i_o_exception",
            "reason": "i_o_exception: Unable to upload object meta-snapshot_1.dat",
            "caused_by": {
                "type": "amazon_s3_exception",
                "reason": "amazon_s3_exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: C4C59458A3683CD4)"
            }
        }
    },
    "status": 500
}
```

**More details of the issue**:

 API call endpoint: `http://xxxxxx:9200/_snapshot/<repository>/snapshot_1` with PUT request
 Request params: 
```
 {
       "indices": "index_1,index_2",
       "ignore_unavailable": true,
       "include_global_state": false
 }
```
 

**One thing to note**:
Our domain is https supported. But if i access the elasticsearch server with ip and https protocol, i get ERR_SSL_PROTOCOL_ERROR
`This site can't provide a secure connection`
This might be a reason?

Any of your help will be much appreciated

**Comment by dadoonet** [comment]
Can you share your `elasticsearch.yml` settings? Replace any secret/access key with `XXXX`

**Comment by Kalesberg** [comment]
Hi @dadoonet , here are extraction from our ES settings
```
cluster.name: xxxxxxxx

bootstrap.mlockall: true

network.bind_host: 0.0.0.0
network.publish_host: 192.168.207.135

http.max_content_length: 1024mb

discovery.zen.ping.unicast.hosts: ["127.0.0.1", "192.168.160.41", "192.168.192.31", "192.168.148.35", "192.168.197.172"]
discovery.zen.minimum_master_nodes: 3

marvel.agent.exporters:
  id1:
    type: http
    host: ["http://192.168.183.120:9200"]

cloud:
  aws:
    access_key: xxxxxxxxxxxxxxxxx
    secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    s3:
      endpoint: <bucket_name>.s3.amazonaws.com
      signer: S3SignerType
```

**Comment by dadoonet** [comment]
Can you remove the signer?

**Comment by Kalesberg** [comment]
Hi
i added it as it was not working either

**Comment by dadoonet** [comment]
Any chance you can upgrade to latest 2.4.6 version and see if it fixes it?

May be you can try with same credentials on a test platform?

**Comment by Kalesberg** [comment]
to upgrade to the newer version, we are required to backup the data first
Honestly, we do not have any snapshots at this situation and it is not good. So backup comes before everything else for our project. Hope it makes sense

Btw, does the https relate to this problem?
Our site domain is https but connect ES server with http
Is this right?

**Comment by dadoonet** [comment]
> So backup comes before everything else for our project. Hope it makes sense

Yeah but can you test on a test cluster your credentials? I mean a similar configuration that you have in production but with no specific data in it?

> Btw, does the https relate to this problem?

I don't know and I don't believe so. The problem you have is the communication from elasticsearch node to AWS API. Not the other way. Did you check BTW that [all required permissions](https://www.elastic.co/guide/en/elasticsearch/plugins/2.3/cloud-aws-repository.html#cloud-aws-repository-permissions) are set?

**Comment by Kalesberg** [comment]
i did not check the link you specified
I did not set such configurations as i am not that much familiar with s3

I am just provided s3 bucket name and did all the stuff that is elasticsearch-level not s3 related stuff

**Comment by dadoonet** [comment]
So check that you have the required S3 permissions.

**Comment by Kalesberg** [comment]
```
Yes it has full access on S3


[4:48] 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}

it can create any bucket and all actions are granted
```

This is the reply from server administrator

**Comment by dadoonet** [comment]
Great. Could you run a test on another local server with the same credentials?

A test similar to https://github.com/elastic/elasticsearch/issues/23354#issuecomment-282348492

Then share exactly what you did and the result.

**Comment by Kalesberg** [comment]
Hi again

I tested with my local machine ES data but i still get signature inconsistency error.

**My local ES information**
- Elasticsearch 5.5.1 with 2 indices
- configured the elasticsearch.yml file with same aws configuration as the live server with s3 repository plugin installed.
```
cloud:
    aws:
        access_key: <access key>
        secret_key: <secret key>
        s3:
            signer: S3SignerType
```
- I opened Kibana and sent this request
```
PUT _snapshot/s3repo
{
  "type": "s3",
  "settings": {
    "bucket": <bucket name>,
    "endpoint": <endpoint url>
  }
}
```
and this is the error i get:
```
{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[s3repo] path  is not accessible on master node"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[s3repo] path  is not accessible on master node",
    "caused_by": {
      "type": "i_o_exception",
      "reason": "Unable to upload object tests-6kHJreWsQumEaBBKy3ruvw/master.dat-temp",
      "caused_by": {
        "type": "amazon_s3_exception",
        "reason": "The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 27AEE9B846B865F9)"
      }
    }
  },
  "status": 500
}
```
