### ISSUE TITLE
Failed to get watch, Failed to get monitoring watch on docker

### ISSUE THREAD

**Issue by afreeland** [elastic/elasticsearch#27413]
**Elasticsearch version** (`bin/elasticsearch --version`):  5.6.3

**Plugins installed**: 
```
elasticsearch1    | [2017-11-16T20:20:52,340][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [aggs-matrix-stats]
elasticsearch1    | [2017-11-16T20:20:52,340][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [ingest-common]
elasticsearch1    | [2017-11-16T20:20:52,340][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [lang-expression]
elasticsearch1    | [2017-11-16T20:20:52,340][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [lang-groovy]
elasticsearch1    | [2017-11-16T20:20:52,340][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [lang-mustache]
elasticsearch1    | [2017-11-16T20:20:52,341][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [lang-painless]
elasticsearch1    | [2017-11-16T20:20:52,341][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [parent-join]
elasticsearch1    | [2017-11-16T20:20:52,341][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [percolator]
elasticsearch1    | [2017-11-16T20:20:52,341][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [reindex]
elasticsearch1    | [2017-11-16T20:20:52,341][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [transport-netty3]
elasticsearch1    | [2017-11-16T20:20:52,341][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded module [transport-netty4]
elasticsearch1    | [2017-11-16T20:20:52,341][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded plugin [ingest-geoip]
elasticsearch1    | [2017-11-16T20:20:52,341][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded plugin [ingest-user-agent]
elasticsearch1    | [2017-11-16T20:20:52,341][INFO ][o.e.p.PluginsService     ] [xfJwVNH] loaded plugin [x-pack]
```

**Container**
Docker Community Edition (Version 17.10.0-ce-win36 (13788)) on Windows SQL Server 2016
ElasticSearch containers from [elastic.co](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)
**The page is now saying 6.0 but when I used it, literally a few days ago, it was 5.6.3**

**Description of the problem including expected versus actual behavior**:
I recently deployed a [Linux SQL Server](https://hub.docker.com/r/microsoft/mssql-server-linux/) container which required 3.25GB of RAM.  I went ahead and allocated more resources to the docker container...so from the docker defaults like CPU = 2 got increased to 28 and Memory got increased to 55,296MB. Decided to bump everything up since this server is primarily just serving up docker containers now.  After I did this I restarted docker and went ahead to utilize my docker-compose script to stand up ES cluster (2 node) and Kibana.  Everything appears to initialize fine and can be hit via REST API directly against ES and Kibana loads showing a green status for both nodes

![image](https://user-images.githubusercontent.com/3135030/32914690-73aef45a-cae4-11e7-9a73-ecbff96908d8.png)
**Not sure why memory still shows 990mb as the limit...it is much higher in the docker compose script

After a period of time ES appears to get a java error and brings down the two ES docker containers and leaves Kibana running but failing to connect.

It is a massive stack trace but I will try list some of the high level below
```
elasticsearch1    | [2017-11-16T20:08:41,940][ERROR][o.e.x.w.t.a.g.TransportGetWatchAction] [xfJwVNH] failed to get watch [F2hXGdeLRfCjMaae49WP7Q_elasticsearch_cluster_status]
elasticsearch1    | java.lang.IllegalStateException: watch store not started
elasticsearch1    |     at org.elasticsearch.xpack.watcher.watch.WatchStore.ensureStarted(WatchStore.java:417) ~[?:?]
elasticsearch1    |     at org.elasticsearch.xpack.watcher.watch.WatchStore.get(WatchStore.java:159) ~[?:?]
elasticsearch1    |     at org.elasticsearch.xpack.watcher.WatcherService.getWatch(WatcherService.java:157) ~[?:?]
```

```
elasticsearch1    | [2017-11-16T20:08:41,991][ERROR][o.e.x.m.e.l.LocalExporter] failed to get monitoring watch [F2hXGdeLRfCjMaae49WP7Q_elasticsearch_cluster_status]
elasticsearch1    | java.lang.IllegalStateException: watch store not started
elasticsearch1    |     at org.elasticsearch.xpack.watcher.watch.WatchStore.ensureStarted(WatchStore.java:417) ~[?:?]
elasticsearch1    |     at org.elasticsearch.xpack.watcher.watch.WatchStore.get(WatchStore.java:159) ~[?:?]
elasticsearch1    |     at org.elasticsearch.xpack.watcher.WatcherService.getWatch(WatcherService.java:157) ~[?:?]
```

```
elasticsearch1    | [2017-11-16T20:08:43,560][ERROR][o.e.x.w.t.a.g.TransportGetWatchAction] [xfJwVNH] failed to get watch [F2hXGdeLRfCjMaae49WP7Q_elasticsearch_version_mismatch]
elasticsearch1    | java.lang.IllegalStateException: watch store not started
elasticsearch1    |     at org.elasticsearch.xpack.watcher.watch.WatchStore.ensureStarted(WatchStore.java:417) ~[?:?]
```

```
elasticsearch1    | [2017-11-16T20:08:43,623][ERROR][o.e.x.m.e.l.LocalExporter] failed to get monitoring watch [F2hXGdeLRfCjMaae49WP7Q_elasticsearch_version_mismatch]
elasticsearch1    | java.lang.IllegalStateException: watch store not started
elasticsearch1    |     at org.elasticsearch.xpack.watcher.watch.WatchStore.ensureStarted(WatchStore.java:417) ~[?:?]
```

```
elasticsearch1    | [2017-11-16T20:08:43,714][ERROR][o.e.x.w.t.a.g.TransportGetWatchAction] [xfJwVNH] failed to get watch [F2hXGdeLRfCjMaae49WP7Q_kibana_version_mismatch]
elasticsearch1    | java.lang.IllegalStateException: watch store not started
elasticsearch1    |     at org.elasticsearch.xpack.watcher.watch.WatchStore.ensureStarted(WatchStore.java:417) ~[?:?]
```

Kibana then starts to freak out and gives the following
```
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:46Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nPOST http://elasticsearch1:9200/.reporting-*/esqueue/_search?ve
rsion=true => read ECONNRESET"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:46Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch1:9200/"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:46Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:46Z","tags":["error","elasticsearch","monitoring-ui"],"pid":1,"message":"Request error, retrying\nHEAD http://elasticsearch1:9200/ => read ECONNRESET"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:46Z","tags":["warning","elasticsearch","monitoring-ui"],"pid":1,"message":"Unable to revive connection: http://elasticsearch1:9200/"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:46Z","tags":["warning","elasticsearch","monitoring-ui"],"pid":1,"message":"No living connections"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:46Z","tags":["status","plugin:monitoring@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - No Living connections","prev
State":"green","prevMsg":"Ready"}
elasticsearch1 exited with code 137
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch1:9200/"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:xpack_main@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Elastic
search at http://elasticsearch1:9200.","prevState":"green","prevMsg":"Ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:graph@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Elasticsearc
h at http://elasticsearch1:9200.","prevState":"green","prevMsg":"Ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:reporting@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Elastics
earch at http://elasticsearch1:9200.","prevState":"green","prevMsg":"Ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:security@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Elasticse
arch at http://elasticsearch1:9200.","prevState":"green","prevMsg":"Ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:searchprofiler@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Ela
sticsearch at http://elasticsearch1:9200.","prevState":"green","prevMsg":"Ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:ml@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Elasticsearch a
t http://elasticsearch1:9200.","prevState":"green","prevMsg":"Ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:tilemap@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Elasticsea
rch at http://elasticsearch1:9200.","prevState":"green","prevMsg":"Ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:watcher@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Elasticsea
rch at http://elasticsearch1:9200.","prevState":"green","prevMsg":"Ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:upgrade@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Elasticsea
rch at http://elasticsearch1:9200.","prevState":"green","prevMsg":"Ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","plugin:elasticsearch@5.6.3","error"],"pid":1,"state":"red","message":"Status changed from green to red - Unable to connect to Elas
ticsearch at http://elasticsearch1:9200.","prevState":"green","prevMsg":"Kibana index ready"}
kibana_1          | {"type":"log","@timestamp":"2017-11-16T20:08:47Z","tags":["status","ui settings","error"],"pid":1,"state":"red","message":"Status changed from green to red - Elasticsearch plugin is red","prevState"
:"green","prevMsg":"Ready"}
```

**Steps to reproduce**:

I am unsure what is causing this issue to be able to reproduce.  I went ahead and adjusted docker CPU and Memory which caused docker to restart itself...which caused an unfriendly exiting of the containers but once docker restarted I ran the `docker-compose up` script to get things moving.  It worked find, I felt good, and then it would fail...I restart it works, and then fails =(

**Provide logs (if relevant)**:

docker-compose script
```
version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch1
    environment:
      - xpack.security.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 25g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - xpack.security.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 25g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch1:9200
    ports:
      - "5601:5601"
    networks:
      - esnet
    volumes:
      - kdata1:/usr/share/kibana/config
    depends_on:
      - elasticsearch1

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  kdata1:
    driver: local

networks:
  esnet:
```

I am fairly new to ElasticSearch so perhaps this is something obvious in my configs...however, my development containers were always very solid and never experienced this issue.  This is actually getting used by a few of our applications so would love to get this things running smoothly again =)
