### ISSUE TITLE
Installations and "apt update" fails - apt repo - Debian (Ubuntu 16.04)

### ISSUE THREAD

**Issue by cailen** [elastic/elasticsearch#28674]
Hello,

I have for weeks now been getting this error when trying to do
`apt update`:

`The repository 'https://artifacts.elastic.co/packages/6.x/apt stable Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details.`

This does not seem to be getting resolved. I've tried removing and re-adding your key, removing the repo and re-adding the repo, and nothing works. I basically have about 250 servers that have to have everything removed in order to work. 

Here are the exact steps I use to install these repos (this is in Ansible, but you get the point):

```
- name: Remove old Elastic Repo - Debian
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ filebeat_major_version }}/apt stable main"
    state: absent
- name: Remove old Elastic Key - Debian
  apt_key:
    id: D88E42B4
    state: absent
- name: Adding the Elasticsearch Key - Debian
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Adding the Elasticsearch Repo - Debian
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
```

Your assistance is greatly appreciated.
