### ISSUE TITLE
Environment Variable Syntax

### ISSUE THREAD

**Issue by gpthome** [elastic/elasticsearch#28940]
I am trying to deploy and use a simple elasticsearch Docker container in OpenShift.  I am following the ES documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docker.html#docker-cli-run

OpenShift 3.5 follows specific syntax regarding environment variable names.  It requires that a variable name be an alphanumeric (a-z and 0-9) string beginning with a letter that may contain underscores.  "discovery.type" does not follow these rules.  

I have also seen many articles describe that the syntax of environment variables should follow alpha-numeric and underscores as well (no periods).

Are you aware of such a convention?  Is there an opportunity to change the name of environment variables to use underscores and not periods?

Thanks for your time.

**Comment by jasontedor** [comment]
This issue would better be handled on the [elastic/elasticsearch-docker](https://github.com/elastic/elasticsearch-docker) repository.

**Comment by dawi** [comment]
There is also no proper solution to this in GitLab.

GitLab exports variables defined in their pipeline via bash export.
https://gitlab.com/gitlab-org/gitlab-foss/issues/42214

So it seems that there is still no other solution then to create a custom elasticsearch docker image, just to set a few variables. :/

**Comment by jasontedor** [comment]
@dawi You can also pass settings via the command line, so you set the command to `[ "bin/elasticsearch", "-Ediscovery.type=single-node" ]`.

**Comment by dawi** [comment]
@jasontedor Thanks, you are right.

Minimal example for future readers:

```
integration-tests:
  stage: Integration Tests
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  services:
    - name: elasticsearch:7.5.0
      alias: elasticsearch
      command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]
  script:
    - curl "http://elasticsearch:9200/_nodes/stats/jvm"

```
