### ISSUE TITLE
Document use of action.auto_create_index in relation to Shield

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29709]
*Original comment by @nellicus:*

Setting `action.auto_create_index: false` would prevent indices creation despite shield privilege `create_index` being granted. 

it'd be useful to have this documented in **shield documentation** where a config like this, would still prevent a index from being created:

if you have:
1) index `abc` not existing
2) action.auto_create_index: false is set in elasticsearch.yml
3) roles.yml containing:

```
myrole:
 indices:
  - names:
        - 'abc'
  - privileges: ["create_index|,"index"]
```

when user with role `myrole` tries to index a document to document to index `abc`
