### ISSUE TITLE
[Monitoring] HTTP Exporter should support proxy settings / path

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29715]
*Original comment by @pickypg:*

Currently, the HTTP Exporter very loosely supports proxy paths (subpaths after the URL), but it does not support a proxy host or port. With LINK REDACTED, `proxy.base_path` will exist in order to continue to support a mechanism (base paths) that has silently existed since 2.0.

``` yaml
xpack.monitoring.exporters._http:
  type: http
  host: "localhost:9200"
  proxy:
    host: someproxy
    port: 8200
    base_path: /some/path
```

We should provide additional settings to support proxies.
