### ISSUE TITLE
add a higher level authentication cache

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29930]
*Original comment by @jaymode:*

Today we cache authentication credentials (hashed and salted) in per realm caches. This is problematic when we have many realms because authentication will still occur on realms in the chain before the cached one and with LDAP realms this means network connections and added latency.

For example take the following config:

``` yaml
shield:
  authc:
    realms:
      default:
        type: esusers
        order: 0
      ldap1:
        type: ldap
        order: 1
        ...
      ldap2:
        type: ldap
        order: 2
        ...
      active_directory:
        type: active_directory
        order: 3
```

If a active directory user tries to authenticate, then they will go through the chain and finally authenticate at the AD realm. On the next authentication attempt, the chain is traversed and each realm is tried until the AD realm is hit and we can find the user in the cache. This can kill performance and responsiveness of applications.

From @uboness one option is:

> grouping realms by supported token type and put caches per group
