### ISSUE TITLE
tags appears in lower case

### ISSUE THREAD

**Issue by Misakiri** [elastic/elasticsearch#31612]
**Elasticsearch version** (`bin/elasticsearch --version`): elasticsearch 6.3.0

**Plugins installed**: []

**JVM version** (`java -version`): oracle-java8 8u171-1~webupd8~0

**OS version** (`uname -a` if on a Unix-like system): ubuntu 16.04.4 LTS

**Description of the problem including expected versus actual behavior**:
When sent an event with filebeat that has a tag with lower and uper case, in elasticsearch appear as lower case

Filebeat example:
![screenshot](https://user-images.githubusercontent.com/20046498/41975605-8262d19c-7a1b-11e8-950d-6514a661b422.png)

Kibana received:
![screenshot](https://user-images.githubusercontent.com/20046498/41975614-8b40be46-7a1b-11e8-824c-1c9ab359afa9.png)

**Comment by danielmitterdorfer** [comment]
I tried to reproduce this with Elasticsearch, Kibana and Filebeat 6.3.0 with the following filebeat configuration (I kept all defaults for Elasticsearch and Kibana):

```yml
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/system.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

# The tags of the shipper are included in their own field with each
# transaction published.
tags: ["aCamelCasedTag"]

setup.kibana:
  host: "localhost:5601"

output.elasticsearch:
  hosts: ["localhost:9200"]
```

After staring Filebeat, the tag appeared in Kibana as specified (i.e. as `aCamelCasedTag`). This might (for example) be an issue with your index template so you should check your Filebeat configuration / start from a fresh configuration and check whether this still reproduces.

If your problem persists I suggest that you [open a topic in the Filebeat Discuss forum](https://discuss.elastic.co/c/beats/filebeat). The Beats team is active there as well and can help out resolving this.
