### ISSUE TITLE
Add proxy mode to RemoteClusterConnection

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#31840]
Today we assume we can use the internal structure of a remote cluster to make additional connections. Yet, this might not work if the remote cluster is inside a cloud-env or behind a proxy. We can't use a seed node and then sniff / discover from there using the cluster state of the remote cluster. 

One way to solve this would be a proxy mode for remote connections that doesn't sniff the remote cluster at all but uses N connections to a proxy using dummy discovery nodes internally. Configuration wise this could look like this:

```YAML
search:
    remote:
        cluster_one: 
            seeds: 127.0.0.1:9300
            proxy_mode: true
            num_connections: 10
```

This would translate to connecting to 10 dummy DiscoveryNodes using the same seed which can then round robin or whatever to connect to nodes. Each of these dummies would use a single channel profile. It's quite a different way of connecting but should work just fine for CCS/CCR purposes.

/cc @tbrooks8 @bleskes 

Relates to #31835
