### ISSUE TITLE
CORS - elasticsearch not available

### ISSUE THREAD

**Issue by wardv** [elastic/elasticsearch#31967]
**Elasticsearch version:** docker.elastic.co/elasticsearch/elasticsearch:6.3.1

**Description of the problem including expected versus actual behavior**:
Adding CORS parameters to the elasticsearch.yml file stops elasticsearch from coming up without errors in log.

**Steps to reproduce**:
1.  Use the following docker-compose.yml:
```
version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    environment:
      - cluster.name=schedule
    networks:
      - elastic_net
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - /path/to/local/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    container_name: kibana
    networks:
      - elastic_net
    ports:
      - 5601:5601
volumes:
  esdata1:
    driver: local

networks:
  elastic_net:
```
2.  The /path/to/local/elasticsearch.yml has all lines commented out except for the following:
```
http.cors.enabled: true
http.cors.allow-origin: /http?://localhost(:[0-9]+)?/
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type, Content-Length
```
3.  Bring up docker instances
`docker-compose up`
 
In the logs you will see that Kibana can't connect to Elasticsearch:

`kibana           | {"type":"log","@timestamp":"2018-07-11T14:10:46Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana           | {"type":"log","@timestamp":"2018-07-11T14:10:46Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}`

Also, trying to connect from a browser won't work:
http://localhost:9200/myindex/mytype/_search
returns ERR_CONNECTION_REFUSED
