### ISSUE TITLE
how to Improve performance of ES v6.2.2

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#32277]
![image](https://user-images.githubusercontent.com/9798724/43067341-b4b3cc7c-8e99-11e8-853e-a211bcf06b16.png)

follow up is info of CPU/MEM/Network.

ES version:6.2.2
CPU Core：4
MEM：4G
ES Ram:2G

stand-alone Pressure measurement
update (upsert)api: 1500~2000 event / s

Cluster Pressure measurement (3 Nodes)
update (upsert)api: 600~1000 event / s

elasticsearch.yml config:
```yml
cluster.name: elasticsearch
node.name: elasticsearch-11
bootstrap.memory_lock: true
bootstrap.system_call_filter: false
http.port: 9200
http.compression: true
transport.tcp.port: 9300
transport.tcp.compress: true
http.cors.enabled: true 
http.cors.allow-origin: "*"
discovery.zen.ping_timeout: 10s 
discovery.zen.fd.ping_retries: 3 
discovery.zen.fd.ping_interval: 3s 
discovery.zen.fd.ping_timeout: 30s
indices.fielddata.cache.size: 30%
indices.query.bool.max_clause_count: 100000
```

how to Improve performance?
