### ISSUE TITLE
Unexpected basic auth prompt with SPNEGO (kerberos) enabled in browser

### ISSUE THREAD

**Issue by robgil** [elastic/elasticsearch#32699]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.4

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**: With kerberos enabled, basic auth still has first priority and issues a popup for user/pass in the browser. Moving kerberos to order 0 doesn't change this behavior.

**Steps to reproduce**:
_elasticsearch.yml_
```
xpack.security.audit.enabled: true
xpack.security.audit.outputs: [ logfile ]
xpack.security.enabled: true
xpack:
  security:
    authc:
      realms:
        kerberos:
            type: kerberos
            order: 0
            keytab.path: /Users/rgil/Downloads/elasticsearch-6.4.0/config/elasticsearch.test.keytab
            remove_realm_name: true
            krb.debug: true
            enabled: true
```
_role mapping_
```
{
  "roles" : [ "superuser"],
  "enabled": true,
  "rules" : {
    "field" : { "username" : "*" }
  }
}
```
After hitting cancel on the basic auth, the SPNEGO auth passes just fine. 

With SPNEGO enabled, I would expect no authentication popups/prompts

For Firefox `firefox network.negotiate-auth.trusted-uris` needs to be set correctly for the service principal being used (in my testing I used `elasticsearch.test`)

Configuration for kerberos is using FreeIPA

Client OS is OSX (_not_ MIT kerberos)

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

- Create keytab
- Configure /etc/krb5.conf on server (hosting elasticsearch)
- Grant permissions to service principal
- Configure ES
- Set Role
- kinit <user>@<realm>
- `curl -s --negotiate -u : -b ~/cookiejar.txt -c ~/cookiejar.txt  http://elasticsearch.test:9200/_xpack/security/_authenticate|jq` to validate
- Test in browser with proper configuration mentioned above 

**Provide logs (if relevant)**:
