### ISSUE TITLE
org.elasticsearch.action.search.SearchPhaseExecutionException while loading snapshot

### ISSUE THREAD

**Issue by pieterlukasse** [elastic/elasticsearch#33350]
**Elasticsearch version**
5.6.10 using docker. See yaml section from `docker-compose` below:
```
services:
  es-ot:
    networks:
    - ot-net
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    ports:
    - "9200:9200"
    restart: always
    volumes:
    - /media/pieter/b250/opentargets/esdata5:/usr/share/elasticsearch/data/
    environment:
     - ES_JAVA_OPTS=-Xms6g -Xmx6g
     - repositories.url.allowed_urls=https://storage.googleapis.com/*
     - xpack.security.enabled=false
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
```

**Plugins installed**: []
See dockerfile

**JVM version**
See dockerfile

**OS version** 
See dockerfile

**Description of the problem including expected versus actual behavior**:

While restoring a snapshot into a new elasticsearch installation, I get the following error:
```
es-ot_1    | [2018-09-03T10:36:54,814][WARN ][r.suppressed             ] path: /18.08_evidence-data*/_search, params: {index=18.08_evidence-data*, timeout=10m}
es-ot_1    | org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
es-ot_1    | 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:272) ~[elasticsearch-5.6.10.jar:5.6.10]
es-ot_1    | 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:130) ~[elasticsearch-5.6.10.jar:5.6.10]
es-ot_1    | 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:241) ~[elasticsearch-5.6.10.jar:5.6.10]
es-ot_1    | 	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:107) ~[elasticsearch-5.6.10.jar:5.6.10]
es-ot_1    | 	at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:205) ~[elasticsearch-5.6.10.jar:5.6.10]
es-ot_1    | 	at org.elasticsearch.action.search.InitialSearchPhase$1.doRun(InitialSearchPhase.java:184) [elasticsearch-5.6.10.jar:5.6.10]
es-ot_1    | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:674) [elasticsearch-5.6.10.jar:5.6.10]
es-ot_1    | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.10.jar:5.6.10]
es-ot_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
es-ot_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
es-ot_1    | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
**Steps to reproduce**:

1) Register the repo to take the 18.08 snapshot from https://storage.googleapis.com/open-targets-data-releases :
 
```
curl -XPUT 'localhost:9200/_snapshot/ot_repo?verify=false&pretty' -H 'Content-Type: application/json' -d'
{
  "type": "url",
  "settings": {
	"url": "https://storage.googleapis.com/open-targets-data-releases/18.08/18.08_snapshot/"
   }
}
'
```

2) Get snapshot name with:

```
curl -i -H "Accept: application/json" http://localhost:9200/_snapshot/ot_repo/_all?pretty
```
This returns something like:

```
{
  "snapshots" : [
    {
      "snapshot" : "curator-20180827215825",
      "uuid" : "JySZfV8aSt6rV52xvC8Pkw",
      "version_id" : 5061099,
      "version" : "5.6.10",
      "indices" : [
        "18.08_mp-data",
...
      ],
      "state" : "SUCCESS",
...
      }
    }
  ]
}
```

3) Trigger the snapshot restore, using the snapshot name (in this example `curator-20180827215825`):

```
curl -XPOST 'localhost:9200/_snapshot/ot_repo/curator-20180827215825/_restore?pretty'
```

4) After snapshot loading is done, the error posted above will appear in the ES logs.
