### ISSUE TITLE
Remote Cluster should be optionally optional on start time

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#34018]
We currently have a way to indicate that it's OK if a remote connection is not available when making a search. We do however require a remote cluster to be reachable when starting a node. IMO we should have an option to indicate the the connection is not reliable and that it's OK to start a node. I see people wanting to decouple dependency of the availability of one cluster on another. 

I think something like this in the yml file should work:

```
cluster:
    remote:
        cluster_one: 
            seeds: 127.0.0.1:9301
            skip_unavailable: true
```

/cc @javanna
