### ISSUE TITLE
geo_shapes stopped indexing in 6.4.1

### ISSUE THREAD

**Issue by Destroy666x** [elastic/elasticsearch#34047]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Plugins installed**: []

**JVM version** (`java -version`): official Docker image

**OS version** (`uname -a` if on a Unix-like system): official Docker image

**Description of the problem including expected versus actual behavior**:

After upgrading from 6.3.2 to 6.4.1, many `geo_shape`s stopped importing.

**Steps to reproduce**:

 1. Index has a field defined like this (FOSElastica bundle YML configuration):
```
    shape:
        type: 'geo_shape'
        tree: 'quadtree'
        precision: '10m'
        distance_error_pct: 0.001
```
 2. Indexing many shapes in 6.4.1 that worked in 6.3.2 results in `caused failed to parse` error.
 3. Adding `ignore_malformed: true` doesn't seem to help.

It looks like there was some sort of undocumented BC break regardless of the shapes being fully proper. If you want I can provide you an example of a shape.
