### ISSUE TITLE
Support to exclude (big) query results from .watcher-history

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/elasticsearch#36719]
**Describe the feature**:

When running my [aggregated_issues_in_logs watch](https://github.com/elastic/examples/pull/240) over a large number of documents the watch finds and aggregates a large number of documents that are then indexed into a new index in ES. The issues is that the whole watch run with all results is written to `.watcher-history-*` as one document. This results in very big documents (`result.input.payload` and `result.transform.payload`). The practical issue with this is that the watch history list in Kibana (Management -> Elasticsearch -> Watcher -> Watches -> log_issues) is unable to show more than one watch execution.

It would be helpful if some "filter_path"/"exclude_filter_path" could be specified in the watch definition which should end up in `.watcher-history-*`.

**Comment by albertzaharovits** [comment]
@ypid-geberit I think this fits better in the Kibana realm. I am thinking of a way of interpreting the contents of the watch metadata, where you would store the path filtering. This sounds kludgy, but maybe they have a better idea. Can you please open a feature request there https://github.com/elastic/kibana ? I am going to close this.

**Comment by ypid-geberit** [comment]
@albertzaharovits I still think this should be implemented in Elasticsearch. I also had this idea of using a metadata field to specify path filtering, example:

```YAML
---

# yamllint disable rule:line-length rule:comments-indentation

metadata:
  comment: 'Test watch'
  watcher_history_exclude_filter_path: 'result.input.payload,result.transform.payload'


throttle_period: '0s'

trigger:
  schedule:

input:
  search:

condition:

transform:

actions:
```

(Yes, YAML is awesome, also for watch definitions. Ref: https://github.com/elastic/examples/pull/239)

But this has the issue that metadata is now evaluated as setting so I would instead propose:

```YAML
---

# yamllint disable rule:line-length rule:comments-indentation

metadata:
  comment: 'Test watch'

watcher_history_exclude_filter_path: 'result.input.payload,result.transform.payload'

trigger:
  schedule:

input:
  search:

actions:
```

What do you have in mind to implement this in Kibana? I only have one idea to midigate this in KIbana which is "Index Patterns" -> "Source Filters" (`result.*.payload,result.*.body,result.actions,input.search.request`). Is that something you mean?

The reason I suggested to implement this in the watch definition is that it is specific to the watch in my case. For some watches, I find it useful to have everything in the history (development and staging watches), for other watches (productive) which write their output to other indices in ES anyway I don’t want to have it duplicated in `.watcher-history-*` (we are talking about hundreds of MiB of `.watcher-history-*` per day in our environment).
