### ISSUE TITLE
ElasticSearch.yml configuration for active directory setup

### ISSUE THREAD

**Issue by JamesRick102** [elastic/elasticsearch#36858]
Use Case: The examples provided on the documents is not clear.

For example - using below document link:
https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-ad-realm.html

Following is from the customer:
The feedback here is to make it clear that the realm name means nothing, you can call it whatever you want.
```
xpack:

  security:

    authc:

      realms:

        active_directory: - this is where the confusion stemmed, instead if we said realm_1 or {InsertRealmNameHere}

          type: active_directory

          order: 0

          domain_name: ad.example.com

          url: ldaps://ad.example.com:636

          bind_dn: es_svc_user@ad.example.com
```

The problem came when the customer added two active directory realms. The customer thought that they needed to share that namespace across both. As soon as we fixed that they didn't have any more issues.

The customer is requesting documentation update on this matter.
