### ISSUE TITLE
snowball filter remove last character `e`

### ISSUE THREAD

**Issue by tom10271** [elastic/elasticsearch#41294]
**Elasticsearch version** (`bin/elasticsearch --version`):
`Version: 6.6.2, Build: oss/tar/3bd3e59/2019-03-06T15:16:26.864148Z, JVM: 1.8.0_171`

**Plugins installed**: []
```
analysis-kuromoji
analysis-nori
analysis-smartcn
```

**JVM version** (`java -version`):
```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Darwin MacBook-Air.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64
```

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1.
PUT `http://localhost:9200/posts_eg`
```json
{
    "mappings": {
        "post": {
            "properties": {
                "title": {
                    "type": "text",
                    "analyzer": "post_name_analyzer"
                }
            }
        }
    },
    "settings": {
        "index": {
            "number_of_shards": "5",
            "analysis": {
            	"filter": {
            		"my_snowball": {
            			"type": "snowball",
            			"language" : "English"
            		}
            	},
                "analyzer": {
                    "post_name_analyzer": {
                        "filter": [
                            "my_snowball"
                        ],
                        "type": "custom",
                        "tokenizer": "whitespace"
                    }
                }
            }
        }
    }
}
```

 2.
POST `http://localhost:9201/posts_eg/_analyze`

```json
{
	"field": "title",
	"text": "asd-the"
}
```

 3.
Result, `e` got removed.
```json
{
    "tokens": [
        {
            "token": "asd-th",
            "start_offset": 0,
            "end_offset": 7,
            "type": "word",
            "position": 0
        }
    ]
}
```

Test and result:
```json 
{
    "a-he": "a-h",
    "a-e": "a-e",
    "f-he": "f-he",
    "fast-he": "fast-h",
    "fast-thet": "fast-thet"
}
```

**Comment by tom10271** [comment]
It seems when `text` starts with any consonants then the last e will be removed.

**Comment by colings86** [comment]
@romseygeek Could you take a look at this one?

**Comment by romseygeek** [comment]
From looking through the snowball algorithm (http://snowball.tartarus.org/algorithms/english/stemmer.html) this looks like expected behaviour - see in particular step 5.  Why do you think this is incorrect behaviour @tom10271?  Are you getting unexpected matches?

**Comment by tom10271** [comment]
My problem is when user search `Off-White`, a famous brand, in the site I work on which used by millions of users per month, ES cannot handle it for me. Off-White will return no result.


We were using ES 1.7, it is working. And when you go to `http://snowballstem.org/demo.html` and select English and test with those I gave, it is working fine I think

**Comment by romseygeek** [comment]
I think this is to do with the hyphen.  You're using the `whitespace` tokenizer, which leaves the hyphen intact, so the snowball stemmer sees the phrase `off-white` as a single token and therefore long enough to apply step 5.  If you enter `offwhite` into the demo site you'll see that it gets stemmed.  You can either use the standard tokenizer, which splits tokens on hyphens, or if they're important then you can insert a `word-delimiter` filter which will keep the original token but also break it into constituent parts.

Don't forget that stemming also needs to be applied at query time - I'm guessing the problem here is that you're indexing the phrase `Off-White` but people are searching for `off white`?

**Comment by tom10271** [comment]
I have tried to add `word_delimiter_graph` with `preserve_original: true` but it is still not working

```yaml
                    analysis:
                        analyzer:
                            post_name_analyzer:
                                type: custom
                                tokenizer: whitespace
                                filter:
                                    - lowercase
                                    - post_synonym
                                    - worddelimiter
                                    - snowball
                                    - post_asciifolding
                        filter:
                            worddelimiter:
                                type: word_delimiter_graph
                                catenate_numbers: true
                                catenate_words: true
                                preserve_original: true
                            post_asciifolding:
                                type: asciifolding
                                preserve_original: true
```
