### ISSUE TITLE
Upgrading to ES 7.0 in Elastic Cloud SAML gives error

### ISSUE THREAD

**Issue by mitchelldavis44** [elastic/elasticsearch#41984]
We're currently on Elastic cloud version 6.7.2 and we're attempting to upgrade to ES 7.0.1.  It is requiring that we change our SAML configuration and remove the "type" attribute.  When I do that I get an error when attempting to save with "'xpack.security.authc.realms.saml': is not allowed".  I searched the docs for any help and unfortunately, it seems the docs are not updated and do not reflect the latest changes.  See here -> [(https://www.elastic.co/guide/en/cloud/current/ec-securing-clusters-SAML.html)](url)

I've attached our config below (obviously taking out our SAML addresses), is there something I'm doing wrong?

```
xpack:
  security:
    authc:
      realms:
        saml:
          saml1:
            order: 2
            attributes.principal: "nameid:persistent"
            attributes.groups: "groups" 
            idp.metadata.path: "https://samladdress" 
            idp.entity_id: "https://samladdress" 
            sp.entity_id: "https://samladdress:9243/" 
            sp.acs: "https://samladdress:9243/api/security/v1/saml"
            sp.logout: "https://samladdress:9243/logout"
```

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.  Log into elastic cloud
 2.  Choose cluster
 3.  Attempt to update to 7.0.1

**Provide logs (if relevant)**:
