### ISSUE TITLE
CI Failure in UpgradeClusterClientYamlTestSuiteIT 80_data_frame_jobs_crud 

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#47928]
This 7.x intake build failed:

https://gradle-enterprise.elastic.co/s/kzvdbodjnn42w/console-log?task=:x-pack:qa:rolling-upgrade:v7.4.1%23twoThirdsUpgradedTest#L6

```
org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT > test {p0=mixed_cluster/80_data_frame_jobs_crud/Test put continuous data frame transform on mixed cluster} FAILED
    java.lang.AssertionError: Failure at [mixed_cluster/80_data_frame_jobs_crud:172]: count didn't match expected value:
                             count: expected Integer [1] but was Integer [0]

        Caused by:
        java.lang.AssertionError: count didn't match expected value:
                                 count: expected Integer [1] but was Integer [0]
REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.4.1#twoThirdsUpgradedTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/80_data_frame_jobs_crud/Test put continuous data frame transform on mixed cluster}" -Dtests.seed=A4FAD98D4AD891A2 -Dtests.security.manager=true -Dtests.locale=vi-VN -Dtests.timezone=Asia/Phnom_Penh -Dcompiler.java=12 -Druntime.java=8 -Dtests.rest.suite=mixed_cluster
```

This test was reported failing in #47693 but the commit in question, ba62eb3dce438b40f85040c0f5ab3295f5fee53c, is a descendant of 5dd6bd6f494dea2145e4034128fbbcfd90aee3f7 (i.e. #47898, the fix for #47693) so this seems to be a different issue.

**Comment by droberts195** [comment]
@hendrikmuhs do you think this will be fixed by #47923?  (That was merged as the commit after ba62eb3dce438b40f85040c0f5ab3295f5fee53c where this failure occurred.)

**Comment by hendrikmuhs** [comment]
yes, I think so, the test:

```
  - do:
      data_frame_transform_deprecated.get_transform_stats:
        transform_id: "mixed-simple-continuous-transform"
  - match: { count: 1 }
  - match: { transforms.0.id: "mixed-simple-continuous-transform" }
```

The call to `_stats` has the same problem not seeing the new named index, so the alias fixes this one, too.
