### ISSUE TITLE
Create index API does not support Content-Type: application/yaml

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/elasticsearch#48571]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 7.4.1, Build: default/rpm/fc0eeb6e2c25915d63d871d344e3d0b45ea0ea1e/2019-10-22T17:16:35.176724Z, JVM: 1.8.0_212

**Plugins installed**: []

**JVM version** (`java -version`):

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (build 1.8.0_212-b4 suse-34.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux linux-vimy 4.4.180-102-default #1 SMP Mon Jun 17 13:11:23 UTC 2019 (7cfa20a) x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

YAML support seems to not cover the Create Index API? I don’t see anything wrong with the following. Similar (YAML) syntax works against Search APIs for example (#48572).

**Steps to reproduce**:

```Shell
curl -u 'elastic:changeme' 'http://localhost:9200/log_test-ip-aggr_author=ypid__v1_2019-10-28?pretty' -XPUT -H 'Content-Type: application/yaml' -d '
---
mappings:
  properties:
    destination.ip:
      type: "ip"
'

```

**Provide logs (if relevant)**:

```yaml
---
error:
  root_cause:
  - type: "not_x_content_exception"
    reason: "Compressor detection can only be called on some xcontent bytes or compressed\
      \ xcontent bytes"
  type: "not_x_content_exception"
  reason: "Compressor detection can only be called on some xcontent bytes or compressed\
    \ xcontent bytes"
status: 500
```
