### ISSUE TITLE
Value script in terms aggregation fails when trying to access IP field

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/elasticsearch#48572]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 7.4.1, Build: default/rpm/fc0eeb6e2c25915d63d871d344e3d0b45ea0ea1e/2019-10-22T17:16:35.176724Z, JVM: 1.8.0_212

**Plugins installed**: []

**JVM version** (`java -version`):

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (build 1.8.0_212-b4 suse-34.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux linux-vimy 4.4.180-102-default #1 SMP Mon Jun 17 13:11:23 UTC 2019 (7cfa20a) x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Terms aggregations support value scripts to change the output of the aggregation. For datatypes like keywords or long, this works fine. However, for the IP datatype, if fails.

Related: #27788 (Same error)

**Steps to reproduce**:

 1. ```Shell
    curl -u 'elastic:changeme' 'http://localhost:9200/log_test-ip-aggr_author=ypid__v1_2019-10-28?pretty' -XPUT -H 'Content-Type: application/json' -d '
    {
      "mappings": {
        "properties": {
          "destination.ip": {
            "type": "ip"
          }
        }
      }
    }'

 2. ```Shell
    curl -u 'elastic:changeme' 'http://localhost:9200/log_test-ip-aggr_author=ypid__v1_2019-10-28/_doc/1?pretty' -XPOST  -H 'Content-Type: application/yaml' -d '{"destination.ip":"203.0.113.23"}'`
    ```
 3. ```Shell
    curl -u 'elastic:changeme' 'http://localhost:9200/log_test-ip-aggr_author=ypid__v1_2019-10-28/_search?pretty' -XPOST  -H 'Content-Type: application/yaml' -d "
    ---
    aggs:
      ip:
        terms:
          field: 'destination.ip'
          script:
            source: '_value'
    "
    ```

**Provide logs (if relevant)**:

```YAML
---
error:
  root_cause: []
  type: "search_phase_execution_exception"
  reason: ""
  phase: "fetch"
  grouped: true
  failed_shards: []
  caused_by:
    type: "illegal_argument_exception"
    reason: "encoded bytes are of incorrect length"
    caused_by:
      type: "unknown_host_exception"
      reason: "addr is of illegal length"
status: 400
```
