### ISSUE TITLE
reference/ccr/apis/get-ccr-stats/line_94 docs test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#48700]
```
java.lang.AssertionError: 
Failure at [reference/ccr/apis/get-ccr-stats:75]: $body didn't match expected value:
                         $body: 
               auto_follow_stats: 
            auto_followed_clusters: 
                                   0: 
                          cluster_name: same [remote_cluster]
            last_seen_metadata_version: same [11613]
          time_since_last_check_millis: same [0]
    number_of_failed_follow_indices: same [0]
    number_of_failed_remote_cluster_state_requests: same [3]
    number_of_successful_follow_indices: same [3]
         recent_auto_follow_errors: 
                                   0: 
                 auto_follow_exception: 
                               caused_by: 
                                 caused_by: 
                                   caused_by: 
                                        reason: same [[node-0][127.0.0.1:36317][cluster:monitor/xpack/in...]
                                          type: same [node_disconnected_exception]
                                      reason: same [could not determine the license type for cluster [...]
                                        type: same [exception]
                                    reason: same [can not fetch remote cluster state as the license ...]
                                      type: same [status_exception]
                                  reason: same [ElasticsearchStatusException[can not fetch remote ...]
                                    type: same [exception]
                          leader_index: same [my_auto_follow_pattern]
                             timestamp: same [1572451902549]
                    follow_stats: 
                           indices: 
                                   0: 
                                 index: same [follower_index]
                                shards: 
                                       0: 
                                bytes_read: same [0]
                      failed_read_requests: same [0]
                     failed_write_requests: same [0]
                  follower_aliases_version: same [0]
                follower_global_checkpoint: same [-1]
                            follower_index: same [follower_index]
                  follower_mapping_version: same [0]
                       follower_max_seq_no: same [-1]
                 follower_settings_version: same [0]
                     last_requested_seq_no: same [-1]
                  leader_global_checkpoint: same [-1]
                              leader_index: same [leader_index]
                         leader_max_seq_no: same [-1]
                           operations_read: same [0]
                        operations_written: same [0]
                 outstanding_read_requests: same [0]
                outstanding_write_requests: same [0]
                           read_exceptions: same [empty list]
                            remote_cluster: same [remote_cluster]
                                  shard_id: same [0]
                  successful_read_requests: same [0]
                 successful_write_requests: same [0]
               time_since_last_read_millis: same [-1]
            total_read_remote_exec_time_millis: same [0]
                    total_read_time_millis: same [0]
                   total_write_time_millis: same [0]
              write_buffer_operation_count: same [0]
                write_buffer_size_in_bytes: same [0]
      received [1] more entries than expected
```

See last line (^).

Build url: https://gradle-enterprise.elastic.co/s/6vk2bsh6vsdem/tests/jbm2x6tnwtxku-etwxtlodvtjas

This test failed [3 times](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:"test%20%7Byaml%3Dreference%2Fccr%2Fapis%2Fget-ccr-stats%2Fline_94%7D"'),sort:!(time,desc))) already today.
