### ISSUE TITLE
ReplicaShardAllocatorSyncIdIT.testFullClusterRestartPerformNoopRecovery failed on master 

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#51750]
Log:  https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/3424/console
Build Scans: https://gradle-enterprise.elastic.co/s/c5muqklxtniog

REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.gateway.ReplicaShardAllocatorSyncIdIT.testFullClusterRestartPerformNoopRecovery" \
  -Dtests.seed=1B893998BA12C55E \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-DZ \
  -Dtests.timezone=Asia/Famagusta \
  -Dcompiler.java=13

**Does not** reproduce for me. May be just an intermittent error.

stacktrace
```
Expected: <0>
     but: was <62>
java.lang.AssertionError: 

Expected: <0>
     but: was <62>

```
