### ISSUE TITLE
Regression  - ssl.trust no longer working - "unable to find valid certification path to requested target"

### ISSUE THREAD

**Issue by AndyHunt66** [elastic/elasticsearch#52153]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.0 
(also affects 7.4.0+)

**Description of the problem including expected versus actual behavior**:
[This pr](https://github.com/elastic/elasticsearch/pull/45272) and it's [backport](https://github.com/elastic/elasticsearch/pull/45836) have caused `xpack.notification.email.account.<name>.smtp.ssl.trust` to not be recognised any more.

The following config works for versions 6.8.4, 7.0.0,7.1.0,7.2.0,7.3.2, but fails for versions 7.4.0+, 7.5.0 with the message: 
`unable to find valid certification path to requested target`

```
xpack.notification.email.account:
   smtp1:
       profile: standard
       email_defaults:
           from: Elasticsearch@example.email.com
       smtp:
           ssl.trust: example.email.com
           auth: false
           starttls.enable: true
           host: example.email.com
           port: 25
```

It's unclear if this is the new intended behaviour, or if this is an unwanted side-effect of #45272

**Steps to reproduce**
1 - setup smtp configuration as above, then create a watcher that fires an email via smtp

**Provide logs (if relevant)**:

Watch result:
```
   "actions": [
      {
        "id": "email_administrator",
        "type": "email",
        "status": "failure",
        "error": {
          "root_cause": [
            {
              "type": "messaging_exception",
              "reason": "failed to send email with subject [lwatch] via account [smtp1]"
            }
          ],
          "type": "messaging_exception",
          "reason": "failed to send email with subject [watch] via account [smtp1]",
          "caused_by": {
            "type": "messaging_exception",
            "reason": "Could not convert socket to TLS",
            "caused_by": {
              "type": "s_s_l_handshake_exception",
              "reason": "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
              "caused_by": {
                "type": "validator_exception",
                "reason": "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
                "caused_by": {
                  "type": "sun_cert_path_builder_exception",
                  "reason": "unable to find valid certification path to requested target"
                }
              }
            }
          }
        }
      }
    ]
```
