### ISSUE TITLE
[BUG] Problem to set path.logs on elasticsearch docker image

### ISSUE THREAD

**Issue by georgesouzafarias** [elastic/elasticsearch#54384]
**Elasticsearch version** : 7.6.1

**JVM version** : openjdk version "13.0.2" 2020-01-14

**OS version** : Linux master1 3.10.0-1062.18.1.el7.x86_64 #1 SMP Wed Mar 18 11:05:28 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description**:

Greetings,

I am building an elasticsearch cluster with 3 masters, each host running imagem elasticsearch:7.6.1 on docker standalone.

Everything looks good, but I am having a problem when I try to set up path.logs. I would like to bind the elasticsearch logs of the container to dir /var/log/elasticsearch of the host, my idea with that, is collecting this logs with filebeat and/or debug in the future.

I have tried all kind of configuration and the elasticsearch does not generate any log, the only one is gc.log configured in log4j2.properties.

Thanks in advance.

**_cat/nodes**

```
192.168.0.14 13 97  2 0.13 0.49 0.49 dim - Master2
192.168.0.13 20 96 10 0.95 0.99 0.79 dim * Master1
192.168.0.15 21 96  1 0.30 0.27 0.28 dim - Master3
```

**docker info**

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 5
 Server Version: 19.03.1-ol
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc version: 4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.18.1.el7.x86_64
 Operating System: Oracle Linux Server 7.7
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 10.858GiB
 Name: master1
 ID: GXGT:VR57:DQ2K:BPIB:ZGUG:TDPH:JIUE:VGFK:NSTD:MV4V:454R:YKVR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

Registries:
```

**Systemd Daemon**

**/etc/systemd/system/elasticsearch.service**

```
[Unit]
Description=elasticsearch Container
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
ExecStartPre=-/usr/bin/docker stop elasticsearch
ExecStartPre=-/usr/bin/docker rm elasticsearch
ExecStartPre=/usr/bin/docker pull elasticsearch:7.6.1
ExecStart= /usr/bin/docker run --rm --name elasticsearch --ulimit memlock=-1:-1 --label co.elastic.logs/module=elasticsearch \
--network host --env-file /etc/elasticsearch/elasticsearch.env -v /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml \
-v /data:/usr/share/elasticsearch/data -v /var/log/elasticsearch/:/usr/share/elasticsearch/logs elasticsearch:7.6.1

[Install]
WantedBy=multi-user.target
```

**/etc/elasticsearch/elasticsearch.env**

``` ES_JAVA_OPTS=-Xms1975m -Xmx1975m ```

**/etc/elasticsearch/elasticsearch.yml**

```
cluster.name: my_cluster

# ------------------------------------ Node ------------------------------------
node.name: Master1

#Server Roles
node.master: true
node.ml: false
node.data: false

# ----------------------------------- Paths ------------------------------------

path:
  logs: /usr/share/elasticsearch/logs
  data: /usr/share/elasticsearch/data

# ----------------------------------- Network ------------------------------------

# Set the bind address to a specific IP (IPv4 or IPv6):
network.host: {IP}
http.host: {IP}
http.publish_host: {IP}
http.port: 9200

# --------------------------------- Discovery ----------------------------------

discovery.seed_hosts: [master1, master2, master3]
cluster.initial_master_nodes: [master1, master2, master3]
discovery.zen.minimum_master_nodes: 1

# --------------------------------- Security ----------------------------------
xpack.security.enabled: false
xpack.security.transport.ssl.enabled: false

```

**ls -l /var/log/elasticsearch/**

```
-rw-rw-r--. 1 1000 0   6493 Mar 29 00:16 gc.log
-rw-rw-r--. 1 1000 0   1471 Mar 29 00:16 gc.log.00
-rw-rw-r--. 1 1000 0   6137 Mar 29 00:16 gc.log.01
```
