### ISSUE TITLE
Policy name for beats not working anymore in 7.6.1

### ISSUE THREAD

**Issue by phlegx** [elastic/elasticsearch#54629]
In packetbeat.yml I used to have this configuration to map all indices to my default ilm policy:

```
setup: 
  ilm:
    enabled: auto
    overwrite: true
    policy_name: default-metric-beats-ilm
```
Actually this was working but after upgrading to `7.6.1` the new indices of packetbeat (and my other beats) are no more linked to this policy.

Has there something changed. Do I need to set this differently now?
