### ISSUE TITLE
Elasticsearch container indices are not sync after docker stack deploy

### ISSUE THREAD

**Issue by yuchen9459** [elastic/elasticsearch#55385]
**Elasticsearch version** : elasticsearch: 7.0.1

**Kibana version**: kibana:7.0.1

**Expected behavior**:
The Elasticsearch and Kibana docker container can be successfully deployed after `docker stack deploy`, and index pattern can be created based on the incoming data.

**Actual behavior**: 
Two containers are created for the elasticsearch service, and the indices are not sync even though the Elasticsearch indices folder are already mounted from local driver. Therefore, the Kibana dashboard cannot successfully retrieved the correct index from Elasticsearch to create the index pattern.

**Steps to reproduce**:
1. `Docker-compose.yml`
```
version: '3.2'
services:
  elasticsearch:
    image: elastic/elasticsearch:7.0.1
    networks:
      - elastic
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    volumes:
      - data_es:/usr/share/elasticsearch/data
    deploy:
      mode: global
      endpoint_mode: dnsrr
    environment:
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      discovery.type: single-node

  kibana:
    image: elastic/kibana:7.0.1
    networks:
      - elastic
    ports:
      - 5601:5601
    deploy:
      mode: global
    depends_on:
      - elasticsearch

volumes:
  data_es:
    driver: local

networks:
  elastic:
    external: true

```
2. Run command to start the es-stack:
` docker stack deploy -c docker-compose.yml es-stack`
