### ISSUE TITLE
Consistent response for has privileges API when requesting undefined privileges

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#55840]
The [has privileges](https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-has-privileges.html#security-api-has-privileges-example) API currently gives back inconsistent responses when querying against undefined application privileges.

Though it could be argued that undefined behaviour is reasonable for undefined privileges, we would prefer to have consistency whenever possible. A few guidelines would be:

* When user has the match all permission, either directly via `*` or a `all` privilege defined as `actions: ["*"]`, we should return `true` regardless whether the queried privilege exists or not.
* Otherwise, we return `false` for undefined privileges
* Ensure the same response is returned for the same privileges regardless of how the query is constructed or any other unrelated information.
* If there is any other case that does not fit above situation, we prefer to return `false`.

Here is an example of the current inconsistency. Assuming we have the following application privileges:
```yaml
app-1:
  read:
    actions: ["a:b:c"]
  write:
    actions: ["x:y:z"]
```

When the user role is defined as:
```yaml
applications: 
  - application: "app-1"
    privileges: ["read", "check"]
    resources: ["foo"]
```

The has privileges call for `app-1` and `check` returns `false`.

However, when the user role is defined as:
```yaml
applications:
  - application: "app-1"
    privileges: ["check"]
    resources: ["foo"]
```
The same call returns `true`. The reason is that we check equality before empty:
https://github.com/elastic/elasticsearch/blob/f8413eb07ae200fc49732f2343008affdc93ac62/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/permission/ApplicationPermission.java#L179-L190
