### ISSUE TITLE
Incorrect log warning when exporting monitoring via HTTP without authentication

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#56810]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.x

**Description of the problem including expected versus actual behavior**:

With the following external monitoring cluster without security enabled (http, not https):

```
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
xpack.monitoring.exporters:
  id1:
    type: http
    host: ["host:9200"]
    use_ingest: false
```

The incorrect warning `exporter [id1] is not using https, but using user authentication with plaintext username/password!` is logged.
