### ISSUE TITLE
UNC paths in `path.repo` are prepended with `path.home`

### ISSUE THREAD

**Issue by rossiya** [elastic/elasticsearch#57630]
**Elasticsearch version** (`bin/elasticsearch --version`): 

- `Version: 7.7.0, Build: default/docker/81a1e9eda8e6183f5237786246f6dced26a10eaf/2020-05-12T02:01:37.602180Z, JVM: 14`

- `Version: 7.5.2, Build: default/docker/8bec50e1e0ad29dad5653712cf3bb580cd1afcdf/2020-01-15T12:11:52.313576Z, JVM: 13.0.1`

(replicated on multiple versions)

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
Following directions for using UNC on Registering a Snapshot Repository on https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html, suggests setting

> The path.repo setting supports Microsoft Windows UNC paths as long as at least server name and share are specified as a prefix and back slashes are properly escaped.
> `path.repo: ["\\\\MY_SERVER\\Snapshots"]`

This results in UNC path being prepended with `path.home` and it fails to reach the server.

**Steps to reproduce**:
`docker-compose.yml` set as:
```
version: '2.2'
services:
  dev-es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: dev-es01
    environment:
      - node.name=dev-es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=dev-es02,dev-es03
      - cluster.initial_master_nodes=dev-es01,dev-es02,dev-es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dev-data01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 7200:9200
    networks:
      - elastic
  dev-es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: dev-es02
    environment:
      - node.name=dev-es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=dev-es01,dev-es03
      - cluster.initial_master_nodes=dev-es01,dev-es02,dev-es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dev-data02:/usr/share/elasticsearch/data
    ports:
      - 7201:9200
    networks:
      - elastic
  dev-es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: dev-es03
    environment:
      - node.name=dev-es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=dev-es01,dev-es02
      - cluster.initial_master_nodes=dev-es01,dev-es02,dev-es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dev-data03:/usr/share/elasticsearch/data
    ports:
      - 7202:9200
    networks:
      - elastic
  dev-kib01:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: dev-kib01
    ports:
      - 7601:5601
    environment:
      ELASTICSEARCH_URL: http://dev-es01:7200
      ELASTICSEARCH_HOSTS: http://dev-es01:7200
    networks:
      - elastic
    depends_on:
      - dev-es01
      - dev-es02
      - dev-es03
  dev-ls01:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: dev-ls01
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 7300:9300
    networks:
      - elastic    
    depends_on:
      - dev-es01
      - dev-es02
      - dev-es03
volumes:
  dev-data01:
    driver: local
  dev-data02:
    driver: local
  dev-data03:
    driver: local
networks:
  elastic:
    driver: bridge
```
Configured elasticsearch.yml as such:
```
cluster.name: "docker-cluster"
network.host: 0.0.0.0
path.repo: ["/", "\\\\10.10.10.10\\elastic"]
```

Unfortunately, this yields in path.repo being set as the below, where an the UNC path is prepended with `/usr/share/elasticsearch/`
```
curl 10.10.10.11:7200/_nodes?pretty -s |grep "\"repo\"" -B3 -A4
        "path" : {
          "logs" : "/usr/share/elasticsearch/logs",
          "home" : "/usr/share/elasticsearch",
          "repo" : [
            "/",
            "/usr/share/elasticsearch/\\\\10.10.10.10\\elastic"
          ]
        },
```
Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. start cluster with the above config
     `docker-compose up -d`
 2. validate if `path.repo` was set correctly
     `curl 10.10.10.11:7200/_nodes?pretty -s |grep "\"repo\"" -B3 -A4`

**Provide logs (if relevant)**:
