### ISSUE TITLE
ES Kuromoji Analyzer incorrect segmentation for numbers

### ISSUE THREAD

**Issue by HarshadRanganathan** [elastic/elasticsearch#58384]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.1

**Plugins installed**: [analysis-icu, analysis-kuromoji, discovery-ec2, repository-s3]

**JVM version** (`java -version`): 12.0.1 (bundled jdk)

**OS version** (`uname -a` if on a Unix-like system): Linux amzn2.x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

When numbers of a font variant subtype are part of the text, kuromoji analyzer segments each number as a separate token. It should rather club them as one single token.

**Steps to reproduce**:

1. Send below request to analyze API 

```
GET _analyze
{
  "text": "新橋６－２０－１",
  "analyzer": "kuromoji"
}
```

2. Analyze API returns below tokens where the number "20" as part of request in a different font variant is split as two tokens "2" & "0".

```
{
  "tokens" : [
    {
      "token" : "新橋",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "word",
      "position" : 0
    },
    {
      "token" : "6",
      "start_offset" : 2,
      "end_offset" : 3,
      "type" : "word",
      "position" : 1
    },
    {
      "token" : "2",
      "start_offset" : 4,
      "end_offset" : 5,
      "type" : "word",
      "position" : 2
    },
    {
      "token" : "0",
      "start_offset" : 5,
      "end_offset" : 6,
      "type" : "word",
      "position" : 3
    },
    {
      "token" : "1",
      "start_offset" : 7,
      "end_offset" : 8,
      "type" : "word",
      "position" : 4
    }
  ]
}
```
3. Due to above segmentation, below sample query will not return a match. Changing below query to have a space between the numbers e.g. "2 0" will return a match.

```
{
  "query": {
    "bool": {
      "filter": [
        {
          "match": {
            "address": {
              "query": "20",
              "operator": "AND",
              "prefix_length": 0,
              "max_expansions": 50,
              "fuzzy_transpositions": true,
              "lenient": false,
              "zero_terms_query": "NONE",
              "auto_generate_synonyms_phrase_query": true,
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
}
```

4. icu_analyzer works as expected for the same text where the tokens are as below:

Analyze Query:
```
GET _analyze
{
  "text": "新橋６－２０－１",
  "analyzer": "icu_analyzer"
}
```

Analyze Response:

```
{
  "tokens" : [
    {
      "token" : "新橋",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "<IDEOGRAPHIC>",
      "position" : 0
    },
    {
      "token" : "6",
      "start_offset" : 2,
      "end_offset" : 3,
      "type" : "<NUM>",
      "position" : 1
    },
    {
      "token" : "20",
      "start_offset" : 4,
      "end_offset" : 6,
      "type" : "<NUM>",
      "position" : 2
    },
    {
      "token" : "1",
      "start_offset" : 7,
      "end_offset" : 8,
      "type" : "<NUM>",
      "position" : 3
    }
  ]
}
```

**Comment by jimczi** [comment]
Thanks for reporting @HarshadRanganathan
Full-width numbers are recognized as symbols by the IPADIC so it is a good practice to normalize the input using the `icu_normalizer` first. The `kuromoji_normalize` example analyzer defined in [`#58385`](https://github.com/elastic/elasticsearch/issues/58385#issuecomment-648677602) splits numbers correctly:

```yaml
POST test/_analyze
{
  "analyzer": "kuromoji_normalize",
  "text": "新橋６－２０－１"
}

{
    "tokens": [
        {
            "token": "新橋",
            "start_offset": 0,
            "end_offset": 2,
            "type": "word",
            "position": 0
        },
        {
            "token": "6",
            "start_offset": 2,
            "end_offset": 3,
            "type": "word",
            "position": 1
        },
        {
            "token": "20",
            "start_offset": 4,
            "end_offset": 6,
            "type": "word",
            "position": 2
        },
        {
            "token": "1",
            "start_offset": 7,
            "end_offset": 8,
            "type": "word",
            "position": 3
        }
    ]
}
```
I am closing this issue as duplicate of #58385, it's a configuration/docs issue, not a bug.
