### ISSUE TITLE
ES Kuromoji Tokenizer incorrect segmentation of font variant subtype

### ISSUE THREAD

**Issue by HarshadRanganathan** [elastic/elasticsearch#58385]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.1

**Plugins installed**:  [analysis-icu, analysis-kuromoji, discovery-ec2, repository-s3]

**JVM version** (`java -version`): 12.0.1 (bundled jdk)

**OS version** (`uname -a` if on a Unix-like system): Linux amzn2.x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Sample text: ｏｆ
Expected tokens: ["of"]
Actual tokens: ["o","f"]

**Steps to reproduce**:

1. Send below request to analyze API

```
GET _analyze
{
  "text": "一般社団法人Ａｒｔ　ａｎｄ　Ｃｕｌｔｕｒｅ　ｏｆ　Ｊａｐａｎ",
  "analyzer": "kuromoji",
  "explain": true
}
```

2. Analyze API returns below tokens where Ａｒｔ　ａｎｄ　Ｃｕｌｔｕｒｅ Ｊａｐａｎ are normalized and segmented as expected.

However, ｏｆ is normalized and segmented as two tokens "o" and "f" rather than as single token "of".

```
{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "org.apache.lucene.analysis.ja.JapaneseAnalyzer",
      "tokens" : [
        {
          "token" : "一般",
          "start_offset" : 0,
          "end_offset" : 2,
          "type" : "word",
          "position" : 0,
          "baseForm" : null,
          "bytes" : "[e4 b8 80 e8 88 ac]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "名詞-一般",
          "partOfSpeech (en)" : "noun-common",
          "positionLength" : 1,
          "pronunciation" : "イッパン",
          "pronunciation (en)" : "ippan",
          "reading" : "イッパン",
          "reading (en)" : "ippan",
          "termFrequency" : 1
        },
        {
          "token" : "社団",
          "start_offset" : 2,
          "end_offset" : 4,
          "type" : "word",
          "position" : 1,
          "baseForm" : null,
          "bytes" : "[e7 a4 be e5 9b a3]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "名詞-一般",
          "partOfSpeech (en)" : "noun-common",
          "positionLength" : 1,
          "pronunciation" : "シャダン",
          "pronunciation (en)" : "shadan",
          "reading" : "シャダン",
          "reading (en)" : "shadan",
          "termFrequency" : 1
        },
        {
          "token" : "法人",
          "start_offset" : 4,
          "end_offset" : 6,
          "type" : "word",
          "position" : 2,
          "baseForm" : null,
          "bytes" : "[e6 b3 95 e4 ba ba]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "名詞-一般",
          "partOfSpeech (en)" : "noun-common",
          "positionLength" : 1,
          "pronunciation" : "ホージン",
          "pronunciation (en)" : "hojin",
          "reading" : "ホウジン",
          "reading (en)" : "hōjin",
          "termFrequency" : 1
        },
        {
          "token" : "art",
          "start_offset" : 6,
          "end_offset" : 9,
          "type" : "word",
          "position" : 3,
          "baseForm" : null,
          "bytes" : "[61 72 74]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "名詞-一般",
          "partOfSpeech (en)" : "noun-common",
          "positionLength" : 1,
          "pronunciation" : null,
          "pronunciation (en)" : null,
          "reading" : null,
          "reading (en)" : null,
          "termFrequency" : 1
        },
        {
          "token" : "and",
          "start_offset" : 10,
          "end_offset" : 13,
          "type" : "word",
          "position" : 4,
          "baseForm" : null,
          "bytes" : "[61 6e 64]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "名詞-固有名詞-組織",
          "partOfSpeech (en)" : "noun-proper-organization",
          "positionLength" : 1,
          "pronunciation" : null,
          "pronunciation (en)" : null,
          "reading" : null,
          "reading (en)" : null,
          "termFrequency" : 1
        },
        {
          "token" : "culture",
          "start_offset" : 14,
          "end_offset" : 21,
          "type" : "word",
          "position" : 5,
          "baseForm" : null,
          "bytes" : "[63 75 6c 74 75 72 65]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "名詞-固有名詞-組織",
          "partOfSpeech (en)" : "noun-proper-organization",
          "positionLength" : 1,
          "pronunciation" : null,
          "pronunciation (en)" : null,
          "reading" : null,
          "reading (en)" : null,
          "termFrequency" : 1
        },
        {
          "token" : "o",
          "start_offset" : 22,
          "end_offset" : 23,
          "type" : "word",
          "position" : 6,
          "baseForm" : null,
          "bytes" : "[6f]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "記号-アルファベット",
          "partOfSpeech (en)" : "symbol-alphabetic",
          "positionLength" : 1,
          "pronunciation" : "オー",
          "pronunciation (en)" : "o",
          "reading" : "オー",
          "reading (en)" : "o",
          "termFrequency" : 1
        },
        {
          "token" : "f",
          "start_offset" : 23,
          "end_offset" : 24,
          "type" : "word",
          "position" : 7,
          "baseForm" : null,
          "bytes" : "[66]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "記号-アルファベット",
          "partOfSpeech (en)" : "symbol-alphabetic",
          "positionLength" : 1,
          "pronunciation" : "エフ",
          "pronunciation (en)" : "efu",
          "reading" : "エフ",
          "reading (en)" : "efu",
          "termFrequency" : 1
        },
        {
          "token" : "japan",
          "start_offset" : 25,
          "end_offset" : 30,
          "type" : "word",
          "position" : 8,
          "baseForm" : null,
          "bytes" : "[6a 61 70 61 6e]",
          "inflectionForm" : null,
          "inflectionForm (en)" : null,
          "inflectionType" : null,
          "inflectionType (en)" : null,
          "keyword" : false,
          "partOfSpeech" : "名詞-固有名詞-組織",
          "partOfSpeech (en)" : "noun-proper-organization",
          "positionLength" : 1,
          "pronunciation" : null,
          "pronunciation (en)" : null,
          "reading" : null,
          "reading (en)" : null,
          "termFrequency" : 1
        }
      ]
    }
  }
}
```

**Comment by jimczi** [comment]
These full-width characters (`ｏ`, `ｆ`) are recognized as symbols by default in the [IPADIC](https://github.com/taku910/mecab/blob/3a07c4eefaffb4e7a0690a7f4e5e0263d3ddb8a3/mecab-ipadic/Symbol.csv#L53) model that is used by the `kuromoji_tokenizer` to split the sentence.
It is generally a good practice to perform normalization before tokenization using the `icu_normalizer` in order to avoid these kind of misalignments. 
I am replacing the `>bug` label  with `>docs` since I think this should be fixed with configuration. The following analyzer should split the sentence correctly thanks to the icu pre-normalization:
<details><summary>kuromoji_normalize</summary>
<p>

```yaml
{
    "settings": {
        "index": {
            "analysis": {
                "tokenizer": {
                    "tokenizer_ja": {
                        "type": "kuromoji_tokenizer"
                    }
                },
                "analyzer": {
                    "kuromoji_normalize": {
                        "char_filter": [
                            "icu_normalizer"
                        ],
                        "tokenizer": "kuromoji_tokenizer",
                        "filter": [
                            "kuromoji_baseform",
                            "kuromoji_part_of_speech",
                            "cjk_width",
                            "ja_stop",
                            "kuromoji_stemmer"
                        ]
                    }
                }
            }
        }
    }
}
```

</p>
</details>

<details><summary>Testing kuromoji_normalize</summary>
<p>

```yaml
{
  "analyzer": "kuromoji_normalize",
  "text": "一般社団法人Ａｒｔ　ａｎｄ　Ｃｕｌｔｕｒｅ　ｏｆ　Ｊａｐａｎ"
}

{
    "tokens": [
        {
            "token": "一般",
            "start_offset": 0,
            "end_offset": 2,
            "type": "word",
            "position": 0
        },
        {
            "token": "社団",
            "start_offset": 2,
            "end_offset": 4,
            "type": "word",
            "position": 1
        },
        {
            "token": "法人",
            "start_offset": 4,
            "end_offset": 6,
            "type": "word",
            "position": 2
        },
        {
            "token": "art",
            "start_offset": 6,
            "end_offset": 9,
            "type": "word",
            "position": 3
        },
        {
            "token": "and",
            "start_offset": 10,
            "end_offset": 13,
            "type": "word",
            "position": 4
        },
        {
            "token": "culture",
            "start_offset": 14,
            "end_offset": 21,
            "type": "word",
            "position": 5
        },
        {
            "token": "of",
            "start_offset": 22,
            "end_offset": 24,
            "type": "word",
            "position": 6
        },
        {
            "token": "japan",
            "start_offset": 25,
            "end_offset": 30,
            "type": "word",
            "position": 7
        }
    ]
}
````
