### ISSUE TITLE
Should we ignore mapping properties on disabled objects

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#58702]
Today it is possible to define an object with properties in a mapping even if `enabled` is set to `false`:

```yaml
"object": {
  "type": "object",
  "enabled": false,
  "properties": {
    "field": {
      "type": "keyword"
    }
  }
}
```

That can be confusing when building queries or aggregations since the field `object.field` is considered as part of the mapping even though its parent is disabled.
The `enabled` option cannot be updated on an existing mapping so defining properties on a disabled object upfront seems unlikely. However with the addition of #58521 we will allow to disable parts of mappings through composable templates, which should trigger this inconsistency in mappings more often.

I opened this issue to discuss whether we should ignore `properties` entirely when an object is disabled ? 
If keeping the original mapping is more important, we should at least ensure that the inner fields don't appear in the  output of `_field_caps` since these fields are not present in the index.
