### ISSUE TITLE
auto_shrink_voting doesn't work if it destroy half nodes of cluster

### ISSUE THREAD

**Issue by Shihta** [elastic/elasticsearch#58712]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 7.7.1, Build: oss/docker/ad56dce891c901a492bb1ee393f12dfff473a423/2020-05-28T16:30:01.040088Z, JVM: 14.0.1

**Plugins installed**: not sure, I used the official oss-version of docker image

**JVM version** (`java -version`): openjdk 14.0.1 2020-04-14

**OS version** (`uname -a` if on a Unix-like system): Linux 76d70b9af3f8 4.15.0-52-generic

**Description of the problem including expected versus actual behavior**:

I think if I enable the `auto_shrink_voting_configuration`, the cluster can elect a new master node if there are still more than 3 nodes in this cluster.
Therefore, I create a cluster with 6 nodes and then destroy 3 nodes of them (include master node). The cluster dead.
I try to get the nodes info by `curl http://10.103.3.74:9201/_cat/nodes`. I get
```
{
  "error": {
    "root_cause": [
      {
        "type": "master_not_discovered_exception",
        "reason": null
      }
    ],
    "type": "master_not_discovered_exception",
    "reason": null
  },
  "status": 503
}
```

I try to find the log through the command `docker logs`, it shows
```
{"type": "server", "timestamp": "2020-06-30T03:30:49,238Z", "level": "WARN", "component": "o.e.d.SeedHostsResolver", "cluster.name": "es-docker-cluster", "node.name": "es01", "message": "failed to resolve host [es06]", "cluster.uuid": "FkkVbqSjTkeqPFYA4WItAA", "node.id": "vPAwL-APQOqYxQqFwF4oPg" ,
"stacktrace": ["java.net.UnknownHostException: es06",
"at java.net.InetAddress$CachedAddresses.get(InetAddress.java:800) ~[?:?]",
"at java.net.InetAddress.getAllByName0(InetAddress.java:1495) ~[?:?]",
"at java.net.InetAddress.getAllByName(InetAddress.java:1354) ~[?:?]",
"at java.net.InetAddress.getAllByName(InetAddress.java:1288) ~[?:?]",
"at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:532) ~[elasticsearch-7.7.1.jar:7.7.1]",
"at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:474) ~[elasticsearch-7.7.1.jar:7.7.1]",
"at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:822) ~[elasticsearch-7.7.1.jar:7.7.1]",
"at org.elasticsearch.discovery.SeedHostsResolver.lambda$resolveHostsLists$0(SeedHostsResolver.java:144) ~[elasticsearch-7.7.1.jar:7.7.1]",
"at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) ~[elasticsearch-7.7.1.jar:7.7.1]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]"] }
```

However, this situation doesn't happen in the **non-oss** version.
Actually, I'm not sure if this situation is a bug or just an unsupported commercial feature.

**Steps to reproduce**:

1. My docker-compose file is shown as the follows:
```
version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es01
    environment:
      - cluster.auto_shrink_voting_configuration=true
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03,es04,es05,es06
      - cluster.initial_master_nodes=es01,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9200

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es02
    environment:
      - cluster.auto_shrink_voting_configuration=true
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03,es04,es05,es06
      - cluster.initial_master_nodes=es01,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9200

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es03
    environment:
      - cluster.auto_shrink_voting_configuration=true
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es04,es05,es06
      - cluster.initial_master_nodes=es01,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9203:9200

  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es04
    environment:
      - cluster.auto_shrink_voting_configuration=true
      - node.name=es04
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es05,es06
      - cluster.initial_master_nodes=es01,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9204:9200

  es05:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es05
    environment:
      - cluster.auto_shrink_voting_configuration=true
      - node.name=es05
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es04,es06
      - cluster.initial_master_nodes=es01,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9205:9200

  es06:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es06
    environment:
      - cluster.auto_shrink_voting_configuration=true
      - node.name=es06
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es04,es05
      - cluster.initial_master_nodes=es01,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=false
      - node.ingest=false
      - cluster.remote.connect=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9206:9200
```

2. Launch the cluster by `docker-compose up`
3. stop 3 nodes which include master node by `docker stop`
4. The cluster dead if you choose **oss-version** of docker image. However, it will alive if you choose **non-oss** docker image.

**Provide logs (if relevant)**:
