### ISSUE TITLE
Regresion in 7.8.0 lucene query "_exists_:non_existing_field_in_mapping" "Rewrite first" exception

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/elasticsearch#58737]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 7.8.0, Build: default/rpm/757314695644ea9a1dc2fecd26d1a43856725e65/2020-06-14T19:35:50.234439Z, JVM: 11.0.7

**Plugins installed**: []

None.

**JVM version** (`java -version`):

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-suse-3.42.4-x8664)
OpenJDK 64-Bit Server VM (build 11.0.7+10-suse-3.42.4-x8664, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux xxx 4.12.14-197.45-default #1 SMP Thu Jun 4 11:06:04 UTC 2020 (2b6c749) x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Querying using the [query string query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) for `_exists_:non_existing_field_in_mapping` results in an exception. Up until ES 7.7, it just said no search hits.

**Steps to reproduce**:

 1. ```Shell
    curl "http://localhost:9200/test/_doc" -XPOST -H 'Content-Type: application/yaml' -d '{"test": 23}'`
    ```
 2. ```Shell
    curl "http://localhost:9200/test/_search" -H 'Content-Type: application/yaml' -d '
    query:
      query_string:
        query: "_exists_:test_something"
    '
    ```

**Provide logs (if relevant)**:

```YAML
---
error:
  root_cause:
  - type: "query_shard_exception"
    reason: "failed to create query: Rewrite first"
    index_uuid: "nxucOP6VSl6JKLZ0mYt7wQ"
    index: "test"
  type: "search_phase_execution_exception"
  reason: "all shards failed"
  phase: "query"
  grouped: true
  failed_shards:
  - shard: 0
    index: "test"
    node: "mr1vscKBTwCFEJ4W885sKg"
    reason:
      type: "query_shard_exception"
      reason: "failed to create query: Rewrite first"
      index_uuid: "nxucOP6VSl6JKLZ0mYt7wQ"
      index: "test"
      caused_by:
        type: "illegal_state_exception"
        reason: "Rewrite first"
status: 400
```
