### ISSUE TITLE
[Elasticsearch][Ingest Pipeline Processors] If conditions in processors are not precompiled on PUT (errors appear on ingest)

### ISSUE THREAD

**Issue by P1llus** [elastic/elasticsearch#58864]
There is plenty of different scenarios for using conditionals under processors. Discussing some of them on slack there seems to be a few unintended situations in terms of error handling and checking.

When creating any sort of processor in ingest pipelines(only tested in yml format) that is created on a beats module, which is setup during `./filebeat setup`(or similar in other beats), the PUT of the pipeline does not return any syntax error in the if conditions itself.

During ingestion of any event, if there is any typos at all, the error will be produced there instead. Here is a niche case with weird behaviour:

Lets say you have a large pipeline, it has tens or hundred(s) of processors, and a single one has a typo ending the name with "?" like this:
(Ends with ?)
```
 - set:
    field: event.action
    value: '{{json.category}}'
    if: ctx.json?.category.? != null`
```
The result of this will actually be that any processor above this will run successfully, and any processor below including this one will not run. BUT the document will be indexed and the error message that is supposed to be triggered by the below is actually empty. So it is created, the error is triggered, but the error message itself is a null string:
```
on_failure:
  - set:
      field: error.message
      value: '{{_ingest.on_failure_message}}'
```

Other cases might include calculating the length of a variable, since it's not know before ingestion, even with the syntax error, it will successfully PUT the pipeline onto the cluster instead of throwing syntax error.

This is similar to another issue that has been reported, in which if you forget to add a "?" to any of the variables used in if conditions on fields that might not always exist, like:
(Missing ? on ipAddress)
```
  - append:
      field: related.ip
      value: '{{json.evidence.ipAddress}}'
      if: ctx.json?.evidence.ipAddress != null
```
The above will return an error related to nothing being able to run GetClass on Object null, though does not reference the processor, line number or anything else, so if you have a single typo somewhere then good luck! :)
