### ISSUE TITLE
OIDC and SAML documentation feedback

### ISSUE THREAD

**Issue by InbarShimshon** [elastic/elasticsearch#60135]
## Description 

These doc improvements are based on SF00575547 in which these feedbacks were raised.

1) OIDC - the documentation is lacking clarity
We do not state that this must be added on all ES nodes including ML nodes - we should be more explicit in stipulating this in our external documentation
```
xpack: 
  security: 
    authc: 
      realms: 
        oidc: 
          oidc1:
            order: 2
            rp.client_id: "600b406e-1973-4b52-b403-3618b2c697c5"
            rp.response_type: code
            rp.redirect_uri: "https://dd03d9e6718e49549713844c652905f3.westeurope.azure.elastic-cloud.com:9243/api/security/oidc/callback"
            op.issuer: "https://login.microsoftonline.com/f6ef6357-0061-40a6-a292-e2f30e1ef991/v2.0"
            op.authorization_endpoint: "https://login.microsoftonline.com/f6ef6357-0061-40a6-a292-e2f30e1ef991/oauth2/v2.0/authorize"
            op.token_endpoint: "https://login.microsoftonline.com/f6ef6357-0061-40a6-a292-e2f30e1ef991/oauth2/v2.0/token"
            op.jwkset_path: "https://login.microsoftonline.com/f6ef6357-0061-40a6-a292-e2f30e1ef991/discovery/v2.0/keys"
            op.userinfo_endpoint: "https://graph.microsoft.com/oidc/userinfo"
            op.endsession_endpoint: "https://login.microsoftonline.com/f6ef6357-0061-40a6-a292-e2f30e1ef991/oauth2/v2.0/logout"
            rp.post_logout_redirect_uri: "https://dd03d9e6718e49549713844c652905f3.westeurope.azure.elastic-cloud.com:9243/logged_out"
            claims.principal: name
            claims.groups: groups
```

## Acceptance Test Criteria

List all the ATC of each action and its intended result. 
As a user, when [action (e.g., viewing, clicking, selecting, etc.)] the [insert the expected result]. 
If the doc issue includes a procedure, number the steps in sequential order.  

2) I think it would be very helpful to have a section on "Life examples" for big 3-5 OIDC providers (Google, Microsoft, Amazon) ti cover most common set-ups to strealine the guideliens for users. 

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.
