### ISSUE TITLE
Increase the ability of JSON processor to parse JSON

### ISSUE THREAD

**Issue by wajika** [elastic/elasticsearch#61307]
I've seen that Filebeat processors can have JSON depth set, and if ElasticSearch Processor can add the same functionality, it can solve a number of problems.

```
processors:
    - decode_json_fields:
        fields: ['message']
        target: json
        max_depth: 4
```

https://discuss.elastic.co/t/is-there-a-way-to-set-analysis-for-a-field/244242
