### ISSUE TITLE
Shard rebalance not obeying cluster_concurrent_rebalance

### ISSUE THREAD

**Issue by gibrown** [elastic/elasticsearch#6141]
During full cluster restart relocating shards steadily increased and did not respond to setting cluster.routing.allocation.cluster_concurrent_rebalance. This behavior is pretty clearly cause by having disk.threshold_enabled set.

- 00:30: Relocating shards was around 86 causing us to get tight on disk space (a node ran out of space and we deleted a number of shards with rm before restarting it).
- 00:57: Set cluster_concurrent_rebalance to 10 (trying to limit relocating shards)
- 01:00 Set to 4 (after realizing it was already set to 6 in the config).
- 01:33 Set to 2 (in case something had changed and it was now per node not for the whole cluster)
- 02:00 Relocating shards hit its peak of ~140

![image](https://cloud.githubusercontent.com/assets/820871/2953053/8521b826-da4c-11e3-8b56-749eca93943a.png)

I'm guessing there is an interaction with disk threshold and/or shard allocation. We're seeing a lot of disk space taken up by old shards that haven't yet been cleaned up (note this is from 03:38):

![image](https://cloud.githubusercontent.com/assets/820871/2953176/4722b9f4-da50-11e3-8469-b661b9d9ff9f.png)

System config:
- 175 primary shards (plus 2 replicas per shard) = 525 shards total
- 36 data nodes (3 master nodes).
- Total disk space in cluster is 26TB. Total of all primaries is about 4.6TB (x3 = 13.8TB). Should be plenty of space.
- Some shards are pretty big. Max of about 45GB. Generally range from 15-40GB. 
- Just ran a full cluster restart to go from v0.90.12 to v1.1.1 (went pretty smoothly otherwise)
- Shard allocation awareness: DC = dfw, iad, sat; PARITY=0,1 (so 6 zones with 6 servers in each)

Relevant config settings:
```
cluster:
  routing:
    allocation:
      node_initial_primaries_recoveries: 8
      node_concurrent_recoveries: 15
      cluster_concurrent_rebalance: 6
      awareness.attributes: dc, parity
      disk.threshold_enabled: true

indices:
  recovery:
    max_bytes_per_sec: 100mb
    concurrent_streams: 5
```

```
{
  "cluster_name" : "es_glbl_cluster",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 39,
  "number_of_data_nodes" : 36,
  "active_primary_shards" : 175,
  "active_shards" : 469,
  "relocating_shards" : 135,
  "initializing_shards" : 56,
  "unassigned_shards" : 0
}
```
