### ISSUE TITLE
Google Cloud discovery not working

### ISSUE THREAD

**Issue by ggprod** [elastic/elasticsearch#67366]
Has anyone ever successfully used the Google Cloud discovery plugin successfully?  After testing and debugging for a week I can't get it working.

my elasticsearch.yml file:
```
path:
  data: /var/lib/elasticsearch
  logs: /var/log/elasticsearch
cloud:
  gce:
    project_id: my-project-id
    zone: ["us-east1-b", "us-east1-c", "us-east1-d"]
discovery:
  seed_providers: gce
  gce:
    tags: elasticsearch  # this tag should be set on the ES instances
node:
  name: ${HOSTNAME}
cluster:
  name: search
  initial_master_nodes:
    - search-node-1
network:
  host: ["_gce_", "_local_"]
http:
  port: 9200
transport:
  port: 9300
```

When I try to create a 3 node cluster (each node has the elasticsearch tag as specified) with one node in each zone (node hostnames search-node-1, search-node-2, search-node-3 all with this same config file) it always comes up as 3 separate clusters (each one being its own master).  I have verified the networking config (routes and firewall rules) and they are all reachable from each other over 9300
