### ISSUE TITLE
Configuration: Add an option for the script folder

### ISSUE THREAD

**Issue by benben** [elastic/elasticsearch#6766]
Since dynamic scripting is off by default since elasticsearch >=1.2 (which is good!), we have to move all our scripts to files in the `config/scripts` folder. It would be awesome to have an option to change that folder in the config to make it easier for using different folders in different environments. Best would be to set it through ENV variables `ELASTICSEARCH_SCRIPTS_FOLDER` and through the config file

```
path:
  logs: /var/log/elasticsearch
  data: /var/data/elasticsearch
  scripts: /my/custom/script/folder
```

thanks!
