### ISSUE TITLE
Stack logging in Docker prevents container recreation

### ISSUE THREAD

**Issue by thbkrkr** [elastic/elasticsearch#72702]
When deploying Elasticsearch in Docker with `ES_LOG_STYLE=file` to use stack logging (#65778), the container may end with the `CrashLoopBackOff` status if the container is ~restarted~ recreated.

### Step to reproduction with ECK on k8s:

- Deploy Elasticsearch using this manifest:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ananas
spec:
  version: 7.12.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_LOG_STYLE
            value: file
```

- Wait for ES to be deployed:

```sh
> k get es,pods
NAME                                                HEALTH   NODES   VERSION   PHASE   AGE
elasticsearch.elasticsearch.k8s.elastic.co/ananas   green    1       7.12.0    Ready   39s

NAME                      READY   STATUS    RESTARTS   AGE
pod/ananas-es-default-0   1/1     Running   0          42s
```

- Force a container restart:

```sh
> k exec ananas-es-default-0 -- kill -15 1
```

The container status then oscillates between `Error` and `CrashLoopBackOff`

```sh
> > k get es,pods
NAME                                                HEALTH    NODES   VERSION   PHASE             AGE
elasticsearch.elasticsearch.k8s.elastic.co/ananas   unknown           7.12.0    ApplyingChanges   4m49s

NAME                      READY   STATUS             RESTARTS   AGE
pod/ananas-es-default-0   0/1     CrashLoopBackOff   4          4m46s
```                                                                                                                                                                                                            

### What's going on?

The ES log reveals that `docker-entrypoint.sh` fails because `log4j2.file.properties` has already been moved.

```sh
> k logs ananas-es-default-0               
mv: cannot stat '/usr/share/elasticsearch/config/log4j2.file.properties': No such file or directory
```

Here is the culprit:

https://github.com/elastic/elasticsearch/blob/cbb2ca28261675be7c231c0e4e1d4f41dfeb3d52/distribution/docker/src/docker/bin/docker-entrypoint.sh#L67

Could we just replace the `mv` by a `cp -f`?
