### ISSUE TITLE
Could not find Java SE Runtime Environment and could not find libjava.so

### ISSUE THREAD

**Issue by BentCoder** [elastic/elasticsearch#73231]
Hi,

I am trying to install ES with docker on a new Mac OS M1 chip device but seeing the error below. Is there are known solution to this please? I couldn't find anything on the web.

**NOTE:** For example using `platform: linux/x86_64` in docker-compose for MySQL and Redis works fine. However, not for ES.

Thanks

**docker-compose.yaml**
```yaml
version: "3.7"
services:
  elastic:
    platform: linux/x86_64
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: "-1"
        hard: "-1"
```

**Error**
```bash
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:7.8.0
Creating elastic_1 ... done
Attaching to elastic_1
elastic_1      | Error: could not find libjava.so
elastic_1      | Error: Could not find Java SE Runtime Environment.
```

**OS**
```bash
Darwin macos.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64; ProductVersion 11.3.1; iOSSupportVersion 14.5
```

**Docker**
```bash
$ docker version
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
