### ISSUE TITLE
FileBeat Dissect-Tokenizer problems

### ISSUE THREAD

**Issue by SkytheK** [elastic/elasticsearch#73548]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.1

**Plugins installed**: [filebeat]

**JVM version** (`java -version`): 11.0.11

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 20.04

**Description of the problem including expected versus actual behavior**: FileBeat dissect-tokenizer problems

**Steps to reproduce**:

I need help because I don't know how to select only the part of the message where it says "NMAP ping sweep Scan". 
05/28-10:30:30:52.840974 [**] [1:10000004:1] "NMAP ping sweep Scan" [**] [Priority: 0] {TCP}

I got this in my filebeat.yml: 
```
 processors:
    - dissect:
        tokenizer: '"%{service.message}"'
        filed: "message"
        target_prefix: "message"
```

![image](https://user-images.githubusercontent.com/74800494/120166700-29605d80-c1fd-11eb-8dc2-213d44b3449a.png)
