### ISSUE TITLE
Could not find or load main class "-Xlog:disable"

### ISSUE THREAD

**Issue by Fossil01** [elastic/elasticsearch#76816]
Running three nodes on Swarm, trying to disable the GC log files by adding `      - ES_JAVA_OPTS="-Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=debug:stderr:utctime"` as an environment var but the containers won't start and error out with:

`Could not find or load main class "-Xlog:disable"`

Any ideas?

**Compose file:**

```yaml
version: "3.8"

networks:
    traefik-public:
      external: true

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - node.name={{.Node.Hostname}}
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=docker-02,docker-03,docker-04
      - cluster.name=REMOVED
      - ELASTIC_PASSWORD=REMOVED
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - ES_JAVA_OPTS="-Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=debug:stderr:utctime"
    networks:
      - elastic
    volumes:
      - /opt/docker/elasticsearch/data:/usr/share/elasticsearch/data
    deploy:
      mode: 'global'
      endpoint_mode: dnsrr
      update_config:
        order: start-first
      rollback_config:
        order: start-first
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
        - com.df.srcPort=9200
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.elastic.rule=Host(`elastic.removed.local`)
        - traefik.http.routers.elastic.entrypoints=http
        - traefik.http.services.elastic.loadbalancer.server.port=9200
    networks:
        - traefik-public

volumes:
    elasticsearch:
```
