### ISSUE TITLE
Validate if values of the SAML attributes defined in configuration are semantically correct

### ISSUE THREAD

**Issue by yelexin** [elastic/elasticsearch#82163]
**Kibana version:**
Public Cloud Version

**Elasticsearch version:**
Public Cloud Version

**Server OS version:**
Public Cloud Version

**Browser version:**
Chrome 92.0.4515.159

**Browser OS version:**
Chrome 92.0.4515.159

**Original install method (e.g. download page, yum, from source, etc.):**
No

**Describe the bug:**

SAML Request generated by Kibana is incorrect. The following is the SAML Request generated by Kibana(Credential information has been masked):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="https://xxx" Destination="https://xxx" ID="_637c27de948f0e4e8bc83aa17776a6354e1732b2" IssueInstant="2021-09-09T11:29:05.027Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0">
  <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://xxxxx:9243</saml2:Issuer>
  <saml2p:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" />
</saml2p:AuthnRequest>
```
According to the SAML specification: http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf in the 8.3 section, "urn:oasis:names:tc:SAML:2.0:attrname-format:basic" isn't proper for the NameIDPolicy element.
"urn:oasis:names:tc:SAML:2.0:attrname-format:basic" is in the 8.2 section and it is used for "Attribute Name Format" which is in the SAML Response rather than SAML Request.
Therefore, the SAML Request is considered invalid by some identity providers and rejected.

**Steps to reproduce:**

1. Edit the Elasticsearch configuration, and add the configuration as follows:
```yaml
xpack.security.authc:
  realms.saml.saml1:
    order: 2
    idp.metadata.path: 'https://nxoh8jpi.authing.cn/api/v2/saml-idp/614048a9b477b638144d4f72/metadata'
    idp.entity_id: 'https://ldmmbebkojmi.authing.cn'
    sp.entity_id: 'https://test-4452bb.kb.us-central1.gcp.cloud.es.io:9243'
    sp.acs: 'https://test-4452bb.kb.us-central1.gcp.cloud.es.io:9243/api/security/saml/callback'
    sp.logout: 'https://test-4452bb.kb.us-central1.gcp.cloud.es.io:9243/logout'
    attributes.principal: 'email'
    attributes.mail: 'email'
    attributes.groups: 'roles'
    attributes.name: 'username'
    nameid_format: 'urn:oasis:names:tc:SAML:2.0:attrname-format:basic'
```
2. Edit the Kibana configuration, and add the configuration as follows:
```yaml
xpack.security.authc.providers:
  saml.saml1:
    order: 0 # display order
    realm: 'saml1' # use saml1 which is configured in es to login
  basic.basic1: # user-password login method, optional
    order: 1
```
3. Go to the Elasticsearch login page, and click Log in with saml/saml1 button. When the browser is redirected to the external identity provider, it returns this error:
```json
{"error":"Error","error_description":{"statusCode":400,"error":"Bad Request","message":"SAML Request is invalid：NameIDPolicy.format: Unknown enum value urn:oasis:names:tc:SAML:2.0:attrname-format:basic"}}
```
The Elasticsearch url is [https://test-4452bb.kb.us-central1.gcp.cloud.es.io:9243](https://test-4452bb.kb.us-central1.gcp.cloud.es.io:9243), and you can try it.

**Expected behavior:**

The attribute "Format" in the NameIDPolicy of a SAML Request should conform with the SAML Specification. These are the possible values for "Format" attribute:
- urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
- urn:oasis:names:tc:SAML:2.0:nameid-format:entity
- urn:oasis:names:tc:SAML:2.0:nameid-format:kerberos
- urn:oasis:names:tc:SAML:1.1:nameid-format:WindowsDomainQualifiedName
- urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName
- urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
- urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified

You can just set the default "Format" value to "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified".
