### ISSUE TITLE
Setting logger.level to ERROR causes deprecation response headers to disappear

### ISSUE THREAD

**Issue by j-bennet** [elastic/elasticsearch#82239]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.0.0-SNAPSHOT
**Plugins installed**: []
**JVM version** (`java -version`): openjdk 11.0.13 2021-10-19
**OS version** (`uname -a` if on a Unix-like system): MacOS Big Sur 11.6.2

**Description of the problem including expected versus actual behavior**:

When setting `logger.level` to ERROR, this stops deprecation response headers from being returned.

I understand that most deprecations are emitted as `WARN`, only the ones removed in the next major are `CRITICAL`, and so `ERROR` log level suppresses the deprecation logger. However, suppressing not just the logging, but also response headers is unexpected, and should be either fixed or documented.

**Steps to reproduce**:

1. Start Elasticsearch in Docker using the following docker-compose file and the command `ES_VERSION=8.0.0-SNAPSHOT docker-compose up`:

```
version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "xpack.security.authc.api_key.enabled=true"
      - "ELASTIC_PASSWORD=changeme"
      - "action.destructive_requires_name=false"
      - "logger.level=ERROR"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data:
```

2. Attempt to create an index template (deprecated feature):

```
> curl -i -u elastic:changeme -X PUT http://localhost:9200/_template/tpl1 -H "Content-Type: application/json" -d '
{
  "index_patterns": ["foo*"],
  "settings": {"number_of_shards": 1}
}'
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/json
content-length: 21

{"acknowledged":true}%
```

Expected: warning header emitted.

Actual result: no warning header.
