### ISSUE TITLE
Failed to verify if  elasticsearch users are created or not  using ansible and API ELS

### ISSUE THREAD

**Issue by zenzedoon** [elastic/elasticsearch#84178]
### Elasticsearch Version

7.13.2

### Java Version

_bundled_

### OS Version

Debian 11

### Problem Description

After successful install of elasticsearch on the nodes with Ansible , a task is lanched to check if if users are exits or not  with using the module uri of ansible to inerract with the els api , but the result is failed and i got this error:
#####################
```
{
  "msg": "Unsupported parameters for (uri) module: ca_path Supported parameters include: attributes, backup, body, body_format, client_cert, client_key, content, creates, delimiter, dest, directory_mode, follow, follow_redirects, force, force_basic_auth, group, headers, http_agent, method, mode, owner, regexp, remote_src, removes, return_content, selevel, serole, setype, seuser, src, status_code, timeout, unix_socket, unsafe_writes, url, url_password, url_username, use_proxy, validate_certs",
  "invocation": {
    "module_args": {
      "url": "https://elsnode1:9200/_security/user/kibanauser",
      "method": "GET",
      "status_code": [
        200,
        404
      ],
      "user": "administrator",
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "force_basic_auth": true,
      "ca_path": "/etc/elasticsearch/certs/ca/ca.crt",
      "validate_certs": true,
      "url_username": "administrator",
      "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
    }
  },
  "_ansible_no_log": false,
  "changed": false
}
```
#####################
the ansible task is : 
```
**************
---
- name: Check if the user is already created
  uri:
    url: "{{ elasticsearch_api_uri }}/{{ elasticsearch_security_api }}/user/{{ item.username }}"
    method: GET
    status_code: [200, 404]
    user: "{{ elasticsearch_admin_username }}"
    password: "{{ elasticsearch_admin_password }}"
    force_basic_auth: "{{ elasticsearch_force_basic_auth }}"          # true
    ca_path: "{{ elasticsearch_configuration_certificates_directory }}/ca/ca.crt"
    validate_certs: true
  no_log: false
  register: useroutput
**************************
```
PS: The CA certificate was generated with the ansible role 

### Steps to Reproduce

rexecute the playbook that  check the existance of some users 
from the command line all is good 
but from ansible the task faild
