### ISSUE TITLE
'CURL_TIMEOUT' not updated on setting READINESS_PROBE_TIMEOUT

### ISSUE THREAD

**Issue by sunilkhokalay** [elastic/elasticsearch#84953]
### Elasticsearch Version

7.2.0

### Java Version

_bundled_

### OS Version

Linux da-eck-es-default-1 4.14.96-coreos-r1 #1 SMP Tue Feb 12 21:16:22 -00 2019 x86_64 x86_64 x86_64 GNU/Linu

### Problem Description

We have deployed the elastic stack with the elastic CR (CRD apiVersion: elasticsearch.k8s.elastic.co/v1) on a Kubernetes cluster (v1.16.8).

elastic controller-version: 1.0.0-beta1
elastic version: 7.2.0

Maybe due to load, the Readiness probe is failing as the probe is not responded within the default timeout of 3 seconds.

So, I had referred to this documentation: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-readiness.html

Updated my CR content as below
```
    podTemplate:
      spec:
        containers:
        - env:
          - name: READINESS_PROBE_TIMEOUT
            value: "10"
          name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12

```

After this update, the `readiness-probe-script.sh` which is from a configMap `my-elastic-es-scripts` which is created by the elastic operator is not updated with this timeout. 

`readiness-probe-script.sh` content is as below:

```
readiness-probe-script.sh:
----

#!/usr/bin/env bash
# Consider a node to be healthy if it responds to a simple GET on "/_cat/nodes?local"
CURL_TIMEOUT=3

# setup basic auth if credentials are available
if [ -n "${PROBE_USERNAME}" ] && [ -f "${PROBE_PASSWORD_FILE}" ]; then
  PROBE_PASSWORD=$(<$PROBE_PASSWORD_FILE)
  BASIC_AUTH="-u ${PROBE_USERNAME}:${PROBE_PASSWORD}"
else
  BASIC_AUTH=''
fi

# request Elasticsearch
ENDPOINT="${READINESS_PROBE_PROTOCOL:-https}://127.0.0.1:9200/_cat/nodes?local"
status=$(curl -o /dev/null -w "%{http_code}" --max-time $CURL_TIMEOUT -XGET -s -k ${BASIC_AUTH} $ENDPOINT)

# ready if status code 200
if [[ $status == "200" ]]; then
  exit 0
else
  exit 1
fi


```

### Steps to Reproduce

Bring up an elastic cluster with the setting above.

And try to increase the CURL_TIMEOUT in the configmap by changing the READINESS_PROBE_TIMEOUT environment variable.
