### ISSUE TITLE
Elastic User Password Not Generated on New Container

### ISSUE THREAD

**Issue by st11x** [elastic/elasticsearch#85047]
Hi,

This is my docker compose file.

```
version: '3'
services:
  elastic:
    image: elasticsearch:8.1.0
    ports:
      - 8200:9200
      - 8300:9300

    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
```

When I start up the container (docker-compose up -d), it does not generate the elastic user password and it also does not generate the Kibana token.

You can see the error in the log file

`Auto-configuration will not generate a password for the elastic built-in superuser, ...`

This is very similar to this issue

[Adds known issue for aarch64 pwd generation by jkakavas · Pull Request #83654 · elastic/elasticsearch (github.com)](https://github.com/elastic/elasticsearch/pull/83654)

But it is supposed to be fixed and I'm also not on ARM nor M1. I'm running on Ubuntu 20.04 x86_64. This is a Linux VM (virtualbox). No shared mounts from Windows. 

Log file from the container 

[elastic.log.zip](https://github.com/elastic/elasticsearch/files/8279037/elastic.log.zip)

**Comment by jkakavas** [comment]
The informational message (it's not an error, that's why we print it on `INFO` level and not on `ERROR` level) you are getting is: 
 `"Auto-configuration will not generate a password for the elastic built-in superuser, as we cannot  determine if there is a terminal attached to the elasticsearch process. You can use the `bin/elasticsearch-reset-password` tool to set the password for the elastic user."`
 
 You are running `docker-compose up` with `-d` which [means](https://docs.docker.com/compose/reference/up/) : "Detached mode: Run containers in the background".  When containers run in "Detached mode" then there is no terminal attached to the elasticsearch process and we don't proceed to generate and write out the password and enrollment token. 

You need to run `docker-compose up` _without_ `-d` , or you can use the CLI tools to get the password and kibana enrollment token: 

```
docker exec -ti elastic_1 /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic
docker exec -ti elastic_1 /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
```

I'm going to close this issue as this is expected behavior, if you don't mind. If you have further questions around configuration or how to use elasticsearch, you can reach out to our forums in https://discuss.elastic.co

**Comment by st11x** [comment]
Thank you for the explanation. I did use those scripts to reset the password and create the token. I was going to use the forums but was advised to create a new issue in issue 83654.

The instructions given at https://hub.docker.com/_/elasticsearch gave the example of running the container in detached mode, and did not warn that the password will not be generated. Hence, leading to the misunderstanding. 

Thanks

**Comment by jkakavas** [comment]
Thanks @st11x for bringing this to our attention! We will reach out to folks in hub.docker.com and update the example there so that it won't be confusing for folks any more.

**Comment by wpm** [comment]
On version 8.4.0 Running `docker compose up` without the `-d` switch does not automatically generate the security information.

I have the following `docker-compose.yml`.

```
services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
```

When I run `docker compose up` in the terminal I see the following message in the Kibana logs.

```
 "message":"Auto-configuration will not generate a password for the elastic built-in superuser, as we cannot  determine if there is a terminal attached to the elasticsearch process. You can use the `bin/elasticsearch-reset-password` tool to set the password for the elastic user.",
```

Also as of today, the [instructions on the Docker page](https://hub.docker.com/_/elasticsearch) still tell you to use the `-d` switch.

**Comment by wpm** [comment]
I have the following `docker-compose.yml` file.

```
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: es-node01
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kib-01
    ports:
      - "5601:5601"
```

When I run `docker compose up` (without the `-d`) I get the "Auto-configuration will not generate a password for the elastic built-in superuser..." log message and no security information is generated.

Everything works if I type the `docker run` commands directly as described in [Run Kibana on Docker for development](https://www.elastic.co/guide/en/kibana/8.4/docker.html#run-kibana-on-docker-for-dev).
