### ISSUE TITLE
index.lifecycle.parse_origination_date to allow for custom date formats

### ISSUE THREAD

**Issue by faph** [elastic/elasticsearch#85070]
### Description

As per these docs: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/ilm-settings.html#_index_level_settings, the `parse_origination_date` setting allows parsing of dates in index names using formats like `2022.01.31` only.

We would like to move away from using Curator for index management in favor of ILM. In Curator, we would be able to specify the date format like this:

```yaml
filters:
- filtertype: age
  source: name
  direction: older
  timestring: '%Y-%m'
  unit: days
  unit_count: 360
```

For example for a month-based index naming scheme.

Would it be possible to support a custom date format for index origination date parsing?
