### ISSUE TITLE
Node shutdown API: allocation_delay parameter is ignored

### ISSUE THREAD

**Issue by pebrc** [elastic/elasticsearch#85922]
### Elasticsearch Version

observed in 7.16.3 or later

### Java Version

_bundled_

### OS Version

Official Docker

### Problem Description

The node shutdown API supports a `allocation_delay` parameter that is supposed to control how long Elasticsearch will wait before reallocating shards. The default value for this parameter on node shutdowns of type restart is 5 minutes 

https://github.com/elastic/elasticsearch/blob/51c1f27b94d2e8bb55a76b07027a535267f895d6/server/src/main/java/org/elasticsearch/cluster/metadata/SingleNodeShutdownMetadata.java#L78

However it seems this parameter is ignored or ineffective as I observed shard relocations to consistently happen already after 1 minute which is the is the regular delayed allocation timeout.

I have tried both relying on the default value as well as setting the value explicitly.

This has also been observed by a ECK user as evident in this issue https://github.com/elastic/cloud-on-k8s/issues/5582

### Steps to Reproduce

* create a multi-node Elasticsearch cluster
* add sample data (I used Rally for that with 5 shards on three ES nodes with 1 replica each)
* take one node down for restart
* delay the restart of the node, i.e. do no boot it up again

If you want to reproduce my experiment on Kubernetes: 
1. Deploy ECK
2. Deploy the manifest reproduced below (adjust availability zones to your environment, or use another label to pin ES nodes to individual k8s nodes) 
3. `kubectl cordon`the node the `ns1` node set is deployed to
4.  apply a change that triggers a rolling restart of `ns1` (here the commented out metadata on the `ns1` node set) the Pod will stay pending due to the cordoned node
5. observe the reallocation of shards after 1 minute

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: shutdown-test
spec:
  version: 8.1.0 
  nodeSets:
  - name: ns1
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: e2e-default
        resources:
          requests:
            storage: 50Gi
    podTemplate:
#      metadata:
#        labels:
#          foo: bar
      spec:
         nodeSelector:
           failure-domain.beta.kubernetes.io/zone: europe-west1-b
  - name: ns2
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: e2e-default
        resources:
          requests:
            storage: 50Gi
    podTemplate:
      spec:
         nodeSelector:
           failure-domain.beta.kubernetes.io/zone: europe-west1-c
  - name: ns3
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: e2e-default
        resources:
          requests:
            storage: 50Gi
    podTemplate:
      spec:
         nodeSelector:
           failure-domain.beta.kubernetes.io/zone: europe-west1-d
```
