### ISSUE TITLE
[DOC]Consider adding API sample to create role for sql permission.

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#86711]
### Elasticsearch Version

8.2.0

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-security.html#sql-security-permissions has this sample for role and it needs to be defined in role_mapping.yml, which is not so useful.
Because as https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-roles.html says below, you can not verify it.

>You cannot view, edit, or remove any roles that are defined in the role mapping files by using the role mapping APIs.

```
cli_or_drivers_minimal:
  cluster:
    - "cluster:monitor/main"
  indices:
    - names: test
      privileges: [read, "indices:admin/get"]
    - names: bort
      privileges: [read, "indices:admin/get"]
```

Maybe it is better to replace with API example like this one.

https://discuss.elastic.co/t/is-there-a-way-to-change-the-default-security-roles/202749

### Steps to Reproduce

N/A
