### ISSUE TITLE
`xpack.security.enrollment.enabled` is missing from the docs

### ISSUE THREAD

**Issue by justincr-elastic** [elastic/elasticsearch#87296]
`xpack.security.enrollment.enabled` is missing from the `Security settings in Elasticsearch` documentation page.

I would have expected to find it in the `General security settings` section, but a search for the word `enrollment` has no results anywhere in the page

Here is a link to the page in 8.3 documentation.
- https://www.elastic.co/guide/en/elasticsearch/reference/8.3/security-settings.html#general-security-settings

**Comment by justincr-elastic** [comment]
If I start Elasticsearch 8.2.2 with the default elasticsearch.yml, Security-on-by-default auto-generates this configuration. Notice the second setting is `xpack.security.enrollment.enabled`. If a customer attempts to look up these auto-generated settings in Elasticsearch security settings documentation, the `xpack.security.enrollment.enabled` setting is missing.

```
#----------------------- BEGIN SECURITY AUTO CONFIGURATION -----------------------
#
# The following settings, TLS certificates, and keys have been automatically      
# generated to configure Elasticsearch security features on 01-06-2022 13:47:56
#
# --------------------------------------------------------------------------------

# Enable security features
xpack.security.enabled: true

xpack.security.enrollment.enabled: true

# Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/http.p12

# Enable encryption and mutual authentication between cluster nodes
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12
# Create a new cluster with the current node only
# Additional nodes can still join the cluster later
cluster.initial_master_nodes: ["DEMO-MACHINE"]

# Allow HTTP API connections from anywhere
# Connections are encrypted and require user authentication
http.host: 0.0.0.0

# Allow other nodes to join the cluster from anywhere
# Connections are encrypted and mutually authenticated
#transport.host: 0.0.0.0

#----------------------- END SECURITY AUTO CONFIGURATION -------------------------
```
