### ISSUE TITLE
JWTRealm Auto Rotating JWKS

### ISSUE THREAD

**Issue by nielsbox** [elastic/elasticsearch#87608]
### Elasticsearch Version

8.2.2

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

According to the docs the JWT Realm will re-fetch the key if the signature is not valid using the current loaded JWKSet.
But this does not happen, as seen here: https://github.com/elastic/elasticsearch/blob/76be7bcdc060a1031a05aa21b1cfc8627b5e7093/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtRealm.java#L427

**Docs Reference:**
https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#:~:text=elasticsearch%20automatically%20caches%20the%20retrieved%20jwk%20set%20to%20avoid%20unnecessary%20http%20requests%2C%20but%20will%20attempt%20to%20refresh%20the%20jwk%20upon%20signature%20verification%20failure%2C%20as%20this%20might%20indicate%20that%20the%20jwt%20provider%20has%20rotated%20the%20signing%20keys.

### Steps to Reproduce

1. Create a Google Cloud Service Account
2. When using this configuration (with Google's daily auto-rotating JWKSet)
```yaml
xpack:
    security:
        authc:
            realms:
                jwt:
                    jwt1:
                        order: 2
                        client_authentication.type: none
                        allowed_issuer: "https://accounts.google.com"
                        allowed_audiences: ["xxx"]
                        allowed_signature_algorithms: ["RS256"]
                        pkc_jwkset_path: "https://www.googleapis.com/oauth2/v3/certs"
                        claims.principal: sub
```
3. Create a role mapping with realm set to `jwt1` and the username to the ID of the service account in Google Cloud
4. After about a day this authentication will not work anymore

### Logs (if relevant)

No logs just 401's
