### ISSUE TITLE
Metricbeat aws module cloudwatch metricsets is ignoring tags

### ISSUE THREAD

**Issue by michal-lyson** [elastic/elasticsearch#88122]
### Elasticsearch Version

8.2.3

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 21.4.0

### Problem Description

According to the documentation: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-aws-cloudwatch.html

we can limit the number of aws cloudwath metrics fetched thanks to the tags. 

Tags were working fine for metricbeat version 7.x (e.g. 7.15.1) but after upgrading to version 8 all the metrics are fetched regardless of the configuration. 

### Steps to Reproduce

Use metricbeat version 8 (tested using 8.2.3) with configuration like this:

```
metricbeat.modules:
  - module: aws
    regions: eu-west-1
    period: 60s
    metricsets:
      - cloudwatch
    metrics:
      - namespace: AWS/EC2
        name: CPUUtilization
        statistic: ["Average"]
        resource_type: ec2:instance
        tags:
          - key: "Project"
            value: "test"
```

**Expected**: ec2 metrics are fetched only for instances with tag `Project:test`
**Actual**: All ec2 metrics are fetched
