### ISSUE TITLE
Elasticsearch + Kibana docker-compose does not auto-generate password for 'elastic' user or Kibana token 

### ISSUE THREAD

**Issue by ChrisHilborne** [elastic/elasticsearch#88272]
### Elasticsearch Version

8.3.1

### Installed Plugins

injest-attachement

### Java Version

see https://www.docker.elastic.co/r/elasticsearch/elasticsearch:8.3.1

### OS Version

5.18.6-arch1-1

### Problem Description

Hi! 

I'm having a very similar problem to that set out in [#85047](https://github.com/elastic/elasticsearch/issues/85047) - however contrary to the response that was given, no password or access token is produced even when I run `docker-compose -f docker-compose.yml up` without `-d`

### Steps to Reproduce

command to run:
`docker-compose -f docker-compose.yml` up`

docker-compose.yml:
```
version: '2.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    container_name: elasticsearch_831
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./elasticsearch-plugins.yml:/usr/share/elasticsearch/config/elasticsearch-plugins.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=elastic-docker
      - node.name=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    mem_limit: 4g
    cap_add:
      - IPC_LOCK

  kibana:
   image: docker.elastic.co/kibana/kibana:8.3.1
    container_name: kibana_831
    environment:
      - "SERVER_HOST=0.0.0.0"
      - ELASTICSEARCH_URL=https://elasticsearch_831
      - ELASTICSEARCH_HOST=https://elasticsearch_831  
     - elasticsearch.ssl.verificationMode=none  
      - LOGGING_VERBOSE=true
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks: 
      - elastic-net
    depends_on:
      - elasticsearch_831

networks:
  elastic-net:
```

kibana.yml:
```
server.name: kibana
server.host: "0"
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.reporting.kibanaServer.hostname: localhost
```

easticsearch-plugins.yml:
```
plugins:
  - id: ingest-attachment

```

### Logs (if relevant)

{"@timestamp":"2022-07-05T10:58:43.311Z", "log.level": "INFO", "message":"Auto-configuration will not generate a password for the elastic built-in superuser, as we cannot  determine if there is a terminal attached to the elasticsearch process. You can use the `bin/elasticsearch-reset-password` tool to set the password for the elastic user.", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.xpack.security.InitialNodeSecurityAutoConfiguration","elasticsearch.node.name":"node1","elasticsearch.cluster.name":"elastic-docker"}
