### ISSUE TITLE
Bool query with should and must_not wrapped in must sometimes returns all the documents

### ISSUE THREAD

**Issue by anti-social** [elastic/elasticsearch#89150]
### Elasticsearch Version

8.3.3

### Java Version

_bundled_

### OS Version

Linux 2097c0134805 5.18.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 15 Jul 2022 15:33:02 +0000 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

See steps to reproduce because the behavior is slightly tricky

### Steps to Reproduce

Prepare a test index:

```
# Create a test index
PUT http://localhost:9200/test-bool-query

# Index first document
POST http://localhost:9200/test-bool-query/_doc/1
Content-type: application/yaml

---
status: 0
kind: a

# Index second document
POST :http://localhost:9200/test-bool-query/_doc/2
Content-type: application/yaml

---
status: 1
kind: b
```

**Problem query that returns all the documents:**
```
# The query that should return single document
# It is important to filter in `must_not` by a non-existent value
POST http://localhost:9200/test-bool-query/_search
Content-type: application/yaml

---
query:
  bool:
    filter:
      bool:
        must:
        - bool: {must_not: {term: {status: 4}}}
        should:
        - term: {status: 0}
```

The above query works similarly against Elasticsearch `7.13`, but Elasticsearch `6.8` returns only one hit as expected.

Any change of the query makes it correct. For examples following queries return correct results:

```
# must_not with existence value
POST http://localhost:9200/test-bool-query/_search
Content-type: application/yaml

---
query:
  bool:
    filter:
      bool:
        must:
        - bool: {must_not: {term: {status: 1}}}
        should:
        - term: {status: 0}

# should with another field
POST http://localhost:9200/test-bool-query/_search
Content-type: application/yaml

---
query:
  bool:
    filter:
      bool:
        must:
        - bool: {must_not: {term: {status: 4}}}
        should:
        - term: {kind: "a"}

# Do not wrap must_not with must
POST http://localhost:9200/test-bool-query/_search
Content-type: application/yaml

---
query:
  bool:
    filter:
      bool:
        must_not: {term: {status: 4}}
        should:
        - term: {status: 0}
```
