### ISSUE TITLE
Apple silicon support for 5.x 

### ISSUE THREAD

**Issue by ostjen** [elastic/elasticsearch#89593]
Hey, I'm working on a project that uses elasticsearch v5 ... I know the M1 support was only added in 7.12.0, but is there any workaround to use older versions on m1?

my docker-compose file has this right now: 
```
elasticsearch:
    image: elasticsearch:5
    platform: linux/amd64
    environment:
      - discovery.type=single-node #bypass bootstrap checks
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
```

and every time I start the container, it instantly crashes :/
