### ISSUE TITLE
Allow date math rounding to round up and down

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#90605]
### Description

at the moment rounding for date maths always rounds "down" the date part, but round up the time part. 
For example for 2022 it would round down to 2022-01-01T23:59:59.
This issue is to consider allowing to round down and up separately.
so for round down 2022 to - 2022-01-01T00:00:00
and round up 2022 to - 2022-12-31T23:59:59

This will allow the following search query:
```
          query:
            range:
              date:
                gte: 1500 #1500-01-01T00:00:00
                lte: 1500 #1500-12-31T23:59:59
```
 to be interpreted as covering all year.

the same for:
```
       query:
            match:
              date:
                query: "1500"
```

**Comment by benwtrent** [comment]
@pgomulka is the main idea here that the behavior for rounding changes depending on the context in which its used?

This seems fairly brittle to me. Especially since:

```
          query:
            range:
              date:
                gte: 1500 #1500-01-01T00:00:00
                lte: 1500 #1500-12-31T23:59:59
```

Could be done by simply:
```
          query:
            range:
              date:
                gte: 1500
                lt: 1501
```

I would prefer consistent behavior unless there is a specific use case that is not easily doable with how things are now.

**Comment by romseygeek** [comment]
@benwtrent the issue is that at the moment this:
```
query:
            range:
              date:
                gte: 2000
                lte: 2000
```
doesn't return a document with a date of 2nd January 2000, which just seems plain wrong.

**Comment by pgomulka** [comment]
the date rang is context specific at the moment. Because  it applies rounding to upper bound, but does not to the lower one. This issue is about making two types of rounding - dedicated for up and dedicated for down bound

Currently this is how we interpret the query
```
          query:
            range:
              date:
                gte: 1500 #1500-01-01T00:00:00
                lte: 1500 #1500-01-01T23:59:59
```
which could be confusing because only documents with 1st Jan are returned
