### ISSUE TITLE
Explicitly configuring the `default` Transport profile silently overrides the typical settings

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#90964]
### Elasticsearch Version

current `main`, all supported versions of ES I'm aware of

### Installed Plugins

n/a

### Java Version

n/a

### OS Version

n/a

### Problem Description

The default Transport port uses an implicit Transport profile named `default`. Because Transport profiles can be configured using the `transport.profiles.<profile_name>.*` setting groups, the `default` Transport profile can be configured using the `transport.profiles.default.*` settings as well as the "usual" settings we would recommend for this, such as `transport.port`, `xpack.security.transport.filter.enabled`, etc.

At least in the case of Security's Transport filters, settings on the `transport.profiles.default.*` group silently override the `transport.*`/`xpack.security.transport.*` settings.

I haven't yet put in the time to figure out if this applies to *all* Transport settings, or just the Transport filters.

### Steps to Reproduce

1. Configure a node with a configuration similar to the following, with conflicting Transport filter settings between the "typical" settings and `transport.profiles.default.*`:
```yaml
# Port 9300 with `xpack.security.transport.*` filter
transport.host: [ local ]
transport.port: 9300
xpack.security.transport.filter.enabled: true

xpack.security.transport.filter.allow: [ "127.0.0.0/8" ]
xpack.security.transport.filter.deny: _all

# Ports 9501 & 9502 with `transport.profiles.default.*` filter
transport.profiles.default.xpack.security.filter.allow: [ "10.0.0.0/8" ]
transport.profiles.default.xpack.security.filter.deny: _all
```
2. Start the node.
3. Observe that the Transport filters configured using `transport.profiles.default.*` are in effect, while those configured using `xpack.security.transport.filter.*` are not.
