### ISSUE TITLE
Some precision loss when parsing big numbers in 8.5.0

### ISSUE THREAD

**Issue by jsoriano** [elastic/elasticsearch#91563]
### Elasticsearch Version

8.5.0

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

This issue is probably not so serious, but reporting just in case.

It looks like parsing big numbers has lost a bit of precision in 8.5.0, at least when converting with the convert processor.

Seen in `elastic-package` tests when updating from 8.4.1 to 8.5.0 in https://github.com/elastic/elastic-package/pull/1033.

### Steps to Reproduce

A couple of examples:

* The number represented as string `6920071768563516847`, when processed with:
  ```
  - convert:
    field: message
    target_field: example.float
    type: double
  ```
  Produces:
    * Before 8.5.0: `6.9200717685635164E18`
    * In 8.5.0: `6.920071768563516E18`
* The number represented as string `1.62461722E9`, when processed with:
   ```
  - convert:
     field: message
     target_field: example.float_as_long
     type: float
   ```
   Produces:
     * Before 8.5.0: `1.62461722E9`
     * In 8.5.0: `1.6246172E9`
