### ISSUE TITLE
Method too large: org/elasticsearch/painless/PainlessScript$Script.execute

### ISSUE THREAD

**Issue by OpakAlex** [elastic/elasticsearch#91921]
### Elasticsearch Version

7.9.2

### Java Version

_bundled_

### OS Version

docker

### Problem Description

When i use big script stored inside elasticsearch, and when i am trying to use it inside query filter script, i got error:
```
"lang":"painless","caused_by":{"type":"method_too_large_exception","reason":"method_too_large_exception: Method too large: org/elasticsearch/painless/PainlessScript$Script.execute ()Z"}}}}],"caused_by":{"type":"method_too_large_exception","reason":"method_too_large_exception: Method too large: org/elasticsearch/painless/PainlessScript$Script.execute ()Z"}}
```
But no way inside docs i can not see max script size which can be passed inside filter script?

Where i can see this info? We only have settings for max script inside store scripts.

So in general i dont know if it's a bug or just miss docs about this.

Thanks.

### Steps to Reproduce

config:
```
          elasticsearch.yml: |
            script:
              max_size_in_bytes: "10000000"
              context:
                field:
                  max_compilations_rate: "10000/10m"
                filter:
                  max_compilations_rate: "10000/10m"
```

Try script around 5k of lines painless code.
