### ISSUE TITLE
Unable to obtain auth details from logs when detaching (in terminal or ansible)

### ISSUE THREAD

**Issue by millerthegorilla** [elastic/elasticsearch#91943]
### Elasticsearch Version

8.5.1

### Installed Plugins

n/a

### Java Version

docker.io/library/   container

### OS Version

6.0.8-300.fc37.x86_64

### Problem Description

I am unable to find any way of obtaining the output of the elasticsearch command that is run in docker_entrypoint.sh, when running the command in detached mode using podman.
This occurs even when I send a tty via the -t switch to the podman run command.  It also occurs when I fork the command or use a bash subprocess.
In all cases, the following error is generated in the logs:

```
Auto-configuration will not generate a password for the elastic built-in superuser, as we cannot determine if there is a terminal attached to the elasticsearch process. You can use the bin/elasticsearch-reset-password tool to set the password for the elastic user."
```

This means that I am unable to use ansible or the shell to automatically start the container as part of a test suite.

I have opened an issue at podman-ansible, and I have asked a question on the elasticsearch forum [here](https://discuss.elastic.co/t/unable-to-output-container-password-details-when-using-ansible-with-podman/319563) and I have opened a stack overflow regarding obtaining output [here](https://stackoverflow.com/questions/74562872/unable-to-output-container-password-details-when-using-ansible-with-podman)

### Steps to Reproduce

in the shell:
```
podman pull docker.io/library/elasticsearch:8.5.1
podman run -dt --name "elastic_cont" --env "discovery.type=single-node" --env "ES_JAVA_OPTS=-Xms512m -Xmx512m" --pod django_forum_test_pod docker.io/library/elasticsearch:8.5.1
podman logs elastic_cont
```
ansible playbook
```yaml
  - name: Create Pod
    containers.podman.podman_pod:
      name: django_forum_test_pod
      publish: 8000:8000
- name: Create ElasticSearch Container
    shell: echo $( podman run -t --name "elastic_cont" --env "discovery.type=single-node" --env "ES_JAVA_OPTS=-Xms512m -Xmx512m" --pod django_forum_test_pod docker.io/library/elasticsearch:8.5.1 2>&1) &    # containers.podman.podman_container:
    containers.podman.podman_container:
      name: elastic_cont
      image: docker.io/library/elasticsearch:8.5.1 
      state: started
      recreate: true
      detach: true
      env:
        'discovery.type': 'single-node'
        'ES_JAVA_OPTS': '-Xms512m -Xmx512m'
      pod: django_forum_test_pod
      log_level: debug
      tty: true
    register: elastic_output
  - debug: var=elastic_output
  - name: output image info
    shell: echo {{ elastic_output }}
```

### Logs (if relevant)

Even when using the tty parameter of the ansible-podman-container, the logs report:

```
Auto-configuration will not generate a password for the elastic built-in superuser, as we cannot determine if there is a terminal attached to the elasticsearch process. You can use the bin/elasticsearch-reset-password tool to set the password for the elastic user."
```

There is no elastic user created, and when I exec into the container, the bin/elasticsearch-reset-password tool fails with:

```
ROR: Failed to reset password for the [elasticsearch] user
```
