### ISSUE TITLE
rate agg on tsdb counter field seems to return wrong data

### ISSUE THREAD

**Issue by ppisljar** [elastic/elasticsearch#94223]
### Elasticsearch Version

8.7

### Java Version

_bundled_

### OS Version

macos

### Problem Description

when running a rate aggregation on tsdb counter field the results i get don't seem correct. 

To test this i created a dataset with `bytes` field which logs the number of bytes transfered per document and `bytes_counter` which logs the ever increasing total of bytes transfered. There are no resets in the counter field. there is also a `request` field which is set as tsdb dimension.

Then i try to run the following: (for all below there is a date histogram aggregation on a top level)
- `rate (bytes)`
- `sum_bucket(high cardinality terms on my `request field`, rate(bytes))` which as expected gives me same results
- `sum_bucket(timeseries, rate(bytes_counter))` which unexpectedly gives me different results

![screenshot-localhost_5601-2023 03 01-12_33_33](https://user-images.githubusercontent.com/13629809/222128114-20ee06e0-030b-42b5-9563-7f3279ca3b1d.png)

full request:
```
{
  "aggs": {
    "4": {
      "date_histogram": {
        "field": "@timestamp",
        "calendar_interval": "1d",
        "time_zone": "Europe/Ljubljana",
        "min_doc_count": 1
      },
      "aggs": {
        "8": {
          "sum_bucket": {
            "buckets_path": "8-bucket>8-metric"
          }
        },
        "9": {
          "sum_bucket": {
            "buckets_path": "9-bucket>9-metric"
          }
        },
        "10": {
          "rate": {
            "field": "bytes_gauge",
            "unit": "second"
          }
        },
        "8-bucket": {
          "terms": {
            "field": "request",
            "order": {
              "_key": "desc"
            },
            "size": 500
          },
          "aggs": {
            "8-metric": {
              "rate": {
                "field": "bytes",
                "unit": "second"
              }
            }
          }
        },
        "9-bucket": {
          "time_series": {},
          "aggs": {
            "9-metric": {
              "rate": {
                "field": "bytes_counter",
                "unit": "second"
              }
            }
          }
        }
      }
    }
  },
  "size": 0,
  "fields": [
    {
      "field": "@timestamp",
      "format": "date_time"
    },
    {
      "field": "timestamp",
      "format": "date_time"
    },
    {
      "field": "utc_time",
      "format": "date_time"
    }
  ],
  "script_fields": {},
  "stored_fields": [
    "*"
  ],
  "runtime_mappings": {},
  "_source": {
    "excludes": []
  },
  "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "range": {
            "@timestamp": {
              "format": "strict_date_optional_time",
              "gte": "2023-02-03T04:00:00.000Z",
              "lte": "2023-02-08T04:00:00.000Z"
            }
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```

### Steps to Reproduce

already described above

**Comment by ppisljar** [comment]
interesting, in kibana lens counter rate can be calculated on the client side based on the results max aggregation gives us and when used with above bytes_counter rate it produces correct results.

**Comment by salvatore-campagna** [comment]
I tried to investigate this issue writing a YAML test. It would be nice to have confirmation that the sample dataset I used mimics well enough the one you are using:

```
---
"rate aggregation on counter field":
  - skip:
      version: " - 8.6.99"
      reason: "counter field support added in 8.7"
      features: close_to

  - do:
      indices.create:
        index: test-rate
        body:
          settings:
            index:
              mode: time_series
              routing_path: [ host ]
              time_series:
                start_time: 2021-04-28T00:00:00Z
                end_time: 2021-04-29T00:00:00Z
          mappings:
            properties:
              "@timestamp":
                type: date
              host:
                type: keyword
                time_series_dimension: true
              bytes_gauge:
                type : long
                time_series_metric: gauge
              bytes_counter:
                type: long
                time_series_metric: counter
              byes:
                type: long

  - do:
      bulk:
        refresh: true
        index: test-rate
        body:
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:00.000Z", "host": "one", "bytes_counter": 1000, "bytes_gauge": 1000, "bytes": 1000 }'
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:01.000Z", "host": "one", "bytes_counter": 1100, "bytes_gauge": 100, "bytes": 100 }'
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:02.000Z", "host": "one", "bytes_counter": 1200, "bytes_gauge": 100, "bytes": 100 }'
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:03.000Z", "host": "one", "bytes_counter": 1250, "bytes_gauge": 50, "bytes": 50 }'
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:04.000Z", "host": "one", "bytes_counter": 1310, "bytes_gauge": 60, "bytes": 60 }'
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:05.000Z", "host": "one", "bytes_counter": 1350, "bytes_gauge": 40, "bytes": 40 }'
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:06.000Z", "host": "one", "bytes_counter": 1420, "bytes_gauge": 70, "bytes": 70 }'
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:07.000Z", "host": "one", "bytes_counter": 1500, "bytes_gauge": 80, "bytes": 80 }'
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:08.000Z", "host": "one", "bytes_counter": 1520, "bytes_gauge": 20, "bytes": 20 }'
          - '{"index": {}}'
          - '{"@timestamp": "2021-04-28T18:50:09.000Z", "host": "one", "bytes_counter": 1550, "bytes_gauge": 30, "bytes": 30 }'

  - do:
      search:
        index: test-rate
        body:
          size: 0
          query:
            bool:
              filter:
                range:
                  "@timestamp":
                    gte: "2021-04-28T18:00:00.000Z"
                    lte: "2021-04-28T19:00:00.000Z"
          aggs:
            date_histogram:
              date_histogram:
                field: "@timestamp"
                fixed_interval: 1m
                time_zone: Europe/Ljubljana
                min_doc_count: 1
              aggs:
                8:
                  sum_bucket:
                    buckets_path: 8-bucket>8-metric
                9:
                  sum_bucket:
                    buckets_path: 9-bucket>9-metric
                10:
                  rate:
                    field: bytes_gauge
                    unit: second
                11:
                  rate:
                    field: bytes
                    unit: second
                8-bucket:
                  terms:
                    field: host
                    order:
                      _key: desc
                    size: 500
                  aggs:
                    8-metric:
                      rate:
                        field: bytes_gauge
                        unit: second
                9-bucket:
                  time_series: { }
                  aggs:
                    9-metric:
                      rate:
                        field: bytes_counter
                        unit: second

  - match: { hits.total.value: 10 }
  - length: { aggregations.date_histogram.buckets: 1 }
  - match: { aggregations.date_histogram.buckets.0.key_as_string: "2021-04-28T20:50:00.000+02:00" }
  - match: { aggregations.date_histogram.buckets.0.doc_count: 10 }
  - close_to: { aggregations.date_histogram.buckets.0.11.value: { value: 25.83, error: 0.01 } }
  - close_to: { aggregations.date_histogram.buckets.0.10.value: { value: 25.83, error: 0.01 } }
  - close_to: { aggregations.date_histogram.buckets.0.9.value: { value: 0.0611, error: 0.0001 } }
  - close_to: { aggregations.date_histogram.buckets.0.8.value: { value: 25.83, error: 0.01 } }
```

I also did the calculations manually to verify what is computed is correct (or at least expected).

* rate aggregation "11" is a rate aggregation on a numeric field (no counter or gauge). The result is just calculated taking the last value by timestamp (1550) and dividing it by the calendar interval (1m = 60 seconds). Indeed 1550 / 60 = 25.83. This is how rate aggregation works also in a non-time series database. When it is a child of a date histogram the `calendar_interval` is used to divide the sum of values in the date histogram bucket.
* fate aggregation "10": this is the same of the previous one, the only difference being that the field is a "gauge". This shows that rate aggregation on gauges work exactly as if the field is a normal numeric field in a non-time series index.
* rate aggregation "8": again the same as before, rate aggregation on gauge field.
* rate agrgegation "9": here we have the rate aggregation on a counter field which provides a different (expectedI would say) result calculated as follows: (counter last value in calendar interval - counter first value in calendar interval) / (timestamp of counter last value in calendar interval - timestamp of counter first value in calendar interval) which is: (1550 - 1000) / (2021-04-28T18:50:09.000Z - 2021-04-28T18:50:00.000Z) = 550 / 9 seconds = 550 / 9000 ms = 0.0611

So the difference is due to two reasons:
1. for the counter we do a difference calculation at the numerator while we don't do that for gauge or plain numeric fields
2. for the counter we do take the actual timestamps to calculate the time difference at the denominator instead of the full calendar interval.

Does this sound reasonable?
