### ISSUE TITLE
Type : IP is not supported as dimension field

### ISSUE THREAD

**Issue by agithomas** [elastic/elasticsearch#94380]
### Elasticsearch Version

8.7.0-SNAPSHOT

### Java Version

_bundled_

### OS Version

Ubuntu 18.08

### Problem Description

The problem was identified when i tried to include `host.ip` of type `ip` as dimension field. Inspite of annotating the field as dimension field, in the index template the field didn't receive 

`time_series_dimension": true ` . It mapping appears as below in index mapping.

```
"host": {
  "properties": {
    "ip": {
      "type": "ip"
    }
  }
},
```

To verify this, i created two additional fields, having field mappings (in `fields.yml`) as below

```
- name: influxdb.status
  type: group
  release: beta
  fields:
    - name: ip_field_iptype
      type: ip
      dimension: true
    - name: ip_field_keyword_type
      type: keyword
      dimension: true
```

On verification of component index template , below is my observation

**Dimension field mapping appears correctly when the type is `keyword`.** Please see below

    "influxdb": {
      "properties": {
        "status": {
          "properties": {
            "ip_field_keyword_type": {
              **"time_series_dimension": true,**
              "type": "keyword"
            },

**Dimension field mapping does not appears correctly when the type is `ip`.** Please see below
```
  "ip_field_iptype": {
    "type": "ip"
  },

```

### Steps to Reproduce

1. Update a package with field mapping  as below
```
    - name: ip_field_iptype
      type: ip
      dimension: true
    - name: ip_field_keyword_type
      type: keyword
      dimension: true
```
2. Check for the `time_series_dimension": true `  in field mapping
