### ISSUE TITLE
ES_TMPDIR not honored by docker-entrypoint.sh

### ISSUE THREAD

**Issue by margold** [elastic/elasticsearch#95542]
### Elasticsearch Version

8.7.0

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

directly using official elasticsearch:8.7.0 docker image

### Problem Description

Running the official docker image with a read-only root filesystem and writable volumes, and setting `ES_TMPDIR` to point to a writable volume, yields this error:

```
/usr/local/bin/docker-entrypoint.sh: line 84: cannot create temp file for here-document: Read-only file system
```

This suggests that the provided writable tmp dir is not used.

### Steps to Reproduce

Minimal `docker-compose.yml`. When run with `docker-compose up elasticsearch`, produces the error described above, and exists.

```
version: "3.7"

services:

  elasticsearch:
    image: elasticsearch:8.7.0
    read_only: true
    volumes:
      - ./container-data/elasticsearch:/usr/share/elasticsearch/data
      - ./container-data/es-tmp:/usr/share/elasticsearch/tmp
    environment:
      - "ES_TMPDIR=/usr/share/elasticsearch/tmp"
```

### Logs (if relevant)

/usr/local/bin/docker-entrypoint.sh: line 84: cannot create temp file for here-document: Read-only file system
