### ISSUE TITLE
Can't start 8.8 ECK cluster

### ISSUE THREAD

**Issue by khteh** [elastic/elasticsearch#95852]
### Elasticsearch Version

8.8

### Java Version

_bundled_

### OS Version

Ubuntu 23.04

### Problem Description

ECK 8.8 gets stuck in:
```
$ k get es -w
NAME        HEALTH    NODES   VERSION   PHASE             AGE
my-cluster   unknown           8.8.0     ApplyingChanges   3m10s
```
Error in `kubectl describe`:
```
    Message:               Cannot get compute and storage resources from Elasticsearch resource generation 2: cannot compute resources for NodeSet "master": no CPU request or limit set
```

### Steps to Reproduce

`kubectl apply -f` the following manifest:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: my-cluster
spec:
  version: 8.8.0
  auth:
    fileRealm:
      - secretName: elasticsearch-secret
  nodeSets:
    - name: master
      count: 3
      config:
        # most Elasticsearch configuration parameters are possible to set, e.g: node.attr.attr_name: attr_value
        #node.roles: ["master", "data", "ingest", "ml"]
        node.roles: ["master"]
        script.painless.regex.enabled: true
        http.cors.enabled: true
        http.cors.allow-origin: "*"
        #network.host: _site_ Forbidden: Configuration setting is reserved for internal use
        #node.name: ${HOSTNAME} Forbidden: Configuration setting is reserved for internal use
        bootstrap.memory_lock: true
        #xpack.security.transport.ssl.enabled: true Forbidden: Configuration setting is reserved for internal use
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              readinessProbe:
                exec:
                  command:
                    - bash
                    - -c
                    - /mnt/elastic-internal/scripts/readiness-probe-script.sh
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 12
                successThreshold: 1
                timeoutSeconds: 12
              env:
                - name: READINESS_PROBE_TIMEOUT
                  value: "10"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp2
    - name: data
      count: 2
      config:
        # most Elasticsearch configuration parameters are possible to set, e.g: node.attr.attr_name: attr_value
        #node.roles: ["master", "data", "ingest", "ml"]
        node.roles: ["data"]
        script.painless.regex.enabled: true
        http.cors.enabled: true
        http.cors.allow-origin: "*"
        #network.host: _site_ Forbidden: Configuration setting is reserved for internal use
        #node.name: ${HOSTNAME} Forbidden: Configuration setting is reserved for internal use
        bootstrap.memory_lock: true
        #xpack.security.transport.ssl.enabled: true Forbidden: Configuration setting is reserved for internal use
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              readinessProbe:
                exec:
                  command:
                    - bash
                    - -c
                    - /mnt/elastic-internal/scripts/readiness-probe-script.sh
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 12
                successThreshold: 1
                timeoutSeconds: 12
              env:
                - name: READINESS_PROBE_TIMEOUT
                  value: "10"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: gp2
```
