### ISSUE TITLE
error registering kibana privileges with elasticsearch for kibana-.kibana - POST /_security/privilege hangs

### ISSUE THREAD

**Issue by dlukyanov** [elastic/elasticsearch#98649]
### Elasticsearch Version

8.9.0

### Java Version

_bundled_

### OS Version

Linux b3865cfa1be4 5.15.49-linuxkit-pr #1 SMP Thu May 25 07:17:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

initial problem:
following the instruction to run elastic+kibana in docker
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_prepare_the_environment

however after startup kibana reports a lot of errors like:
`error registering kibana privileges with elasticsearch for kibana-.kibana: request timed out`

after debugging i minimized the steps to reproduce to following

### Steps to Reproduce

create file `docker-compose.yaml`:
```
version: '3'
name: elastic

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    volumes:
      - ./data_elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=false
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elastic
```

create the folder `data_elasticsearch` with just one file [body-502.json.gz](https://github.com/elastic/elasticsearch/files/12389411/body-502.json.gz)  (extract it)

it's a real content kibana sends to elastic

now after starting elasticsearch try to call following command from elascticsearch container/terminal:
```
curl -v -X POST -u elastic:elastic http://localhost:9200/_security/privilege -H "Expect:" -H "Content-Type: application/json" --data @$HOME/data/body-502.json
```

as a result curl just hangs

![image](https://github.com/elastic/elasticsearch/assets/7533327/923718f1-58ff-4d84-8d93-c919e87e8895)

I believe it's a source of the issue `error registering kibana privileges with elasticsearch for kibana-.kibana`
